(function(){if(!("object"===typeof window.L&&null!==window.L)){var h,g,o="",t=function(){if(null===g||"object"!==typeof g||0===g.length)g={};g[""]={};""!==o&&h.onEvent.addEvent(window,"beforeunload",function(){!0===g[""].modify&&(delete g[""],h.AJAX({url:o,async:!1,data:h.param.encode({languagePackageListJson:h.JSON.stringify(g)}),type:"post"}),g[""]={})})};h=getBacktrace=function(){var a="";try{a=(void 0).dont.exist}catch(c){c.stack&&((a=c.stack.split("\n"),h.browser.isChrome||h.browser.isMSIE?(a=
a[3],a=a.substr(0,a.lastIndexOf(":"))):h.browser.isFirefox&&(a=a[2]),a=a.substr(a.indexOf(":")+3).match(/^[^\/\\?#]+([^\?#]*)\/([^\?#]*).*:(\d+)$/i))?(a[1]=a[1].substr(h._rootUrl.length),""===a[2]&&(a[2]="index.php"),a=a[1]+"/"+a[2]+":"+a[3]):a="")}return a};window.L=h={_rootUrl:"",_adminUrl:void 0,getText:function(a,c){var d="";if("string"===typeof a&&""!==a){("object"!==typeof c||null===c)&&(c={});var b="string"===typeof c.key||"number"===typeof c.key?""+c.key:"";""!==o&&("object"!==typeof g[a]&&
(g[a]={}),"object"!==typeof g[a][b]&&(g[a][b]={}),null==g[a][b][0]&&(g[a][b][0]=""),g[a][b][2]="string"!==typeof c.file||!/^\d+$/.test(c.line)?getBacktrace():c.file+":"+c.line,g[a][b].jsModify=!0,g[""].modify=!0);"object"===typeof g[a]&&("object"===typeof g[a][b]&&g[a][b][0]?d=g[a][b][0]:"object"===typeof g[a][""]&&g[a][""][0]&&(d=g[a][""][0]))}return d?d:a},browser:{isMSIE:-1!=navigator.appVersion.indexOf("MSIE"),isFirefox:-1!=navigator.userAgent.indexOf("Firefox"),isChrome:-1!=navigator.userAgent.indexOf("Chrome"),
version:(navigator.userAgent.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/i)||[])[1]},onEvent:function(){var a=null,c=null,d={canDefault:!0,canBubble:!0},b=[],e={},j=function(){var a=document.addEventListener?{ready:"DOMContentLoaded",mouseenter:"mouseover",mouseleave:"mouseout"}:{ready:"readystatechange"};return function(c,b){return"ready"===b&&h.getWindow(c).document===c||a[b]&&("mouseenter"===b||"mouseleave"===b)?a[b]:b}}(),i=function(){d={canDefault:!0,canBubble:!0}},s=function(a,e){c=null;"object"===
h.param.getType(a)&&null===h.each(b,function(e){if(b[e]===a)return c=e})&&!0===e&&(b[c=b.length]=a);return c};return{addEvent:function(b,f,k,g){"ready"===b&&(k=f,f=b,b=document);"load"===b&&(k=f,f=b,b=window);if(!(null===s(b,!0)||"function"!==typeof k||"string"!==typeof f)){var p=h.getWindow(b),m=null;if(a=h.strVar(e,c+"."+f+".list[]")){for(var q in a)if(a[q]===k)return;a[g&&arguments.callee.caller===h.onEvent.fireEvent?"unshift":"push"](k)}else h.strVar(e,c+"."+f+".list[]",k);if("load"===f&&p===
b||"ready"===f&&p.document===b)m=p.document,"complete"===m.readyState&&k.call(m,{target:m,type:f,canDefault:!0,canBubble:!0});h.strVar(e,c+"."+f+".enFn")||(a=h.strVar(e,c+"."+f+".enFn",function(){var j={obj:m||b,objKey:c,type:f,init:function(){}};if("resize"===f&&b===h.getWindow(b))j.init=function(){if(!d.hasOwnProperty("target")&&j.callee.lastTimeStamp&&j.callee.lastTimeStamp+150>(new Date).getTime())return!1};else if(document.addEventListener&&("mouseenter"===f||"mouseleave"===f))j.init=function(a){for(a=
a.relatedTarget;a&&a!==j.obj;)a=a.parentNode;if(a===j.obj)return!1};j.callee=function(c){if((a=h.strVar(e,j.objKey+"."+j.type+".list[]"))&&!1!==j.init(c)){var b={},f={originalEvent:c,target:c.srcElement||j.obj};h.each(c,f);h.each(d,f,b);d.type||(f.type=j.type);i();for(var l=0,k=a.length;l<k;++l)"function"===typeof a[l]&&!1===a[l].call(j.obj,f)&&(f.canDefault=!1);!1===f.canDefault&&(c.preventDefault?c.preventDefault():c.returnValue=!1);!1===f.canBubble&&(c.stopPropagation?c.stopPropagation():c.cancelBubble=
!0);d=b;arguments.callee.lastTimeStamp=(new Date).getTime();arguments.callee.lastEvent=f}};return j.callee}()),b.addEventListener?b.addEventListener(j(b,f),a,!1):b.attachEvent("on"+j(b,f),a))}},removeEvent:function(a,b,d){"ready"===a&&(d=b,b=a,a=document);"load"===a&&(d=b,b=a,a=window);var i=[],g=0;if(null!==s(a))if("string"===typeof b){if("function"===typeof d&&(i=h.strVar(e,c+"."+b+".list[]")))for(var m in i)i[m]===d&&delete i[m],"function"===typeof i[m]&&++g;h.strVar(e,c+"."+b)&&(0===g?(i.splice(0,
i.length),d=e[c][b].enFn,delete e[c][b],a.removeEventListener?a.removeEventListener(j(a,b),d,!1):a.detachEvent("on"+j(a,b),d)):null==e[c][b].recycling&&(e[c][b].recycling=window.setTimeout(function(){var a=c+"."+b,d=null;return function(){if(d=h.strVar(e,a)){if("array"===h.param.getType(d.list))for(var c=d.list.length-1;-1<c;--c)"function"===typeof d.list[c]||d.list.splice(c,1);delete d.recycling}}}(),0)))}else for(m in d&&(d=b),e[c])arguments.callee(a,m,d)},fireEvent:function(b,f,k){"ready"===b&&
(k=f,f=b,b=document);"load"===b&&(k=f,f=b,b=window);if(!("object"!==h.param.getType(b)||"string"!==typeof f)){var g=h.getWindow(b),p=window.setTimeout(i,0),m=k?Boolean(k.canBubble):!1,q=k?!1!==k.canDefault:!0;d={target:b,type:f,canDefault:q,canBubble:m};"object"===h.param.getType(k)&&(delete k.canDefault,delete k.canBubble,h.each(k,d));if(b.dispatchEvent){var r=function(a){a.originalEvent&&a.originalEvent.stopPropagation()};h.onEvent.addEvent(g.document,f,r,!0)}h.onEvent.addEvent(b,f,function(a){if(a.originalEvent){q===
false&&(a.originalEvent.preventDefault?a.originalEvent.preventDefault():a.originalEvent.returnValue=false);m===false&&(a.originalEvent.stopPropagation?a.originalEvent.stopPropagation():a.originalEvent.cancelBubble=true)}h.onEvent.removeEvent(b,f,arguments.callee)},!0);if(q&&("click"===f||f===(g.document.activeElement===b?"blur":"focus"))&&b[f])b[f](),r&&h.onEvent.removeEvent(g.document,f,r);else{if(b.dispatchEvent)k=document.createEvent("Events"),k.initEvent(j(b,f),!0,!0),b.dispatchEvent(k),h.onEvent.removeEvent(g.document,
f,r);else try{b.fireEvent("on"+j(b,f))}catch(o){for(var n=b;n;)a={},"function"===typeof n["on"+f]&&h.onEvent.addEvent(n,f,function(a){var b=n["on"+f].call(n,a);h.onEvent.removeEvent(n,f,arguments.callee);return b},!0),null!==s(n)&&(a=h.strVar(e,c+"."+f+".enFn"))&&a({}),n=!1!==(a.lastEvent||{}).canBubble&&m?n.parentNode:null}i();window.clearTimeout(p)}}},getEventTarget:function(a,b){b||(b=window);var c=a;if(b.event)c=b.event.srcElement;else{var d=[];try{var e=arguments.callee.caller;do{var j=Object.prototype.toString.call(e.arguments[0]);
if("Event]"===j.substr(j.length-6)){c=e.arguments[0].target;break}else d[d.length]=e,e.__eached=!0}while((e=e.caller)&&!e.__eached)}catch(i){}h.each(d,function(a,b){delete b[a].__eached})}return c}}}(),strTranscoding:{textToHtml:function(a){var c=document.createElement("div");"undefined"===typeof c.innerText?c.textContent=a:c.innerText=a;return c.innerHTML.replace(/\"/ig,"&quot;").replace(/\'/ig,"&#039;").replace(/ /ig,"&nbsp;").replace(/\n/ig,"<br>")},htmlToText:function(a){var c=document.createElement("div");
c.innerHTML=a;return"undefined"===typeof c.innerText?(c.innerHTML=c.innerHTML.replace(/<br>/ig,"\n"),c.textContent):c.innerText}},AJAX:function(a){(function(a){var d=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");"object"===typeof a||(a={});"string"===typeof a.url||(a.url=window.location.href);"object"===typeof a.context||(a.context=window);"function"===typeof a.success||(a.success=function(){});!0===a.callbackState||(a.callbackState=!1);!1===a.async||
(a.async=!0);a.ajaxObj=d;"get"===a.type?(null!=a.data&&(a.url=-1!==a.url.indexOf("?")?"?"!==a.url.charAt(a.url.length-1)?a.url+("&"+a.data):a.url+a.data:a.url+("?"+a.data)),a.data=null):a.type="post";d.open(a.type,a.url,a.async);d.setRequestHeader("Content-Type","application/x-www-form-urlencoded");d.setRequestHeader("X-Requested-With","XMLHttpRequest");d.onreadystatechange=function(){(a.callbackState||d.readyState==4&&d.status===200)&&a.success.call(a.context,d.responseText,a)};d.send(a.data)})(a)},
param:{getType:function(){var a=Object.prototype.toString,c={"[object Array]":"array","[object Boolean]":"boolean","[object Date]":"date","[object Function]":"function","[object Number]":"number","[object Object]":"object","[object RegExp]":"regexp","[object String]":"string"};return function(d){return null==d?""+d:c[a.call(d)]||"object"}}(),getObjectLength:function(a,c){var d=0,b=h.param.getType(a);if("object"===b)for(var e in a)c?d+=1:/\d+/.test(e)&&e>=d&&(d=parseInt(e)+1);else if("string"===b||
"array"===b)d=a.length;return d},decode:function(a,c,d){"boolean"===typeof c&&(d=c,c=void 0);for(var a=a.split(c||"&"),c={},b,e,j,i=0,g=a.length;i<g;++i)if(b=a[i].split("="),b[1]||(b[1]=""),d&&(b[0]=decodeURIComponent(b[0].replace(/\+/g,"%20")),b[1]=decodeURIComponent(b[1].replace(/\+/g,"%20"))),e=b[0].match(/^([^\[\]]+)((?:\[[^\[\]]*\])*)$/),null!==e)if(e[2]){if(null==c[e[1]]||"object"!==typeof c[e[1]])c[e[1]]={};j=c[e[1]];e=e[2].substring(1,e[2].length-1).split("][");for(var l=0,f=e.length;l<f;++l){var k=
e[l]||h.param.getObjectLength(j);if(l+1===f)j[k]=b[1];else if(null==j[k]||"object"!==typeof j[k])j[k]={};j=j[k]}}else c[e[1]]||(c[e[1]]=b[1]);return c},encode:function(a,c,d,b){var e=[],b=""+(b||"");!1!==d&&(b=encodeURIComponent(b));"boolean"===typeof c&&(d=c,c=void 0);(function(a,b){var c=h.param.getType(a),g=e.length,f;c==="function"&&(a=a());if(!a&&a!==0)e[g]=(b||"0")+"=";else if(c==="array")for(var k=0,c=a.length;k<c;++k){f=b?"["+k+"]":k;d!==false&&(f=encodeURIComponent(f));arguments.callee(a[k],
(b||"")+f)}else if(c==="object")for(k in a){f=b?"["+k+"]":k;d!==false&&(f=encodeURIComponent(f));arguments.callee(a[k],(b||"")+f)}else e[g]=(b||"0")+"="+(d===false?""+a:encodeURIComponent(""+a));f===void 0&&(e[g]===void 0&&b)&&(e[g]=b+"=")})(a,b);temp=e.join(c||"&");return!1===d?temp:temp.replace(/%20/g,"+")}},JSON:function(){function a(a){d.lastIndex=0;return d.test(a)?'"'+a.replace(d,function(a){var c=b[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+
a+'"'}function c(b,d){var i,h,g,f=d[b];switch(typeof f){case "string":return a(f);case "number":return isFinite(f)?""+f:"null";case "boolean":case "null":return""+f;case "object":if(!f)return"null";g=[];if("[object Array]"===Object.prototype.toString.apply(f)){h=f.length;for(i=0;i<h;i+=1)g[i]=c(i,f)||"null";return h=0===g.length?"[]":"["+g.join(",")+"]"}for(i in f)Object.prototype.hasOwnProperty.call(f,i)&&(h=c(i,f))&&g.push(a(i)+":"+h);return h=0===g.length?"{}":"{"+g.join(",")+"}"}}var d=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
b={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return{stringify:function(a){try{return c("",{"":a})}catch(b){return a}},parse:function(a){try{return(new Function("return "+a))()}catch(b){return a}}}}(),cookie:{del:function(a,c,d){var b=h.param.getType(a),e=document.cookie.split("; ");a||(a="");d="string"!==typeof d?"path=/; ":""===d?"":"path="+d+"; ";if("regexp"===b){c=0;for(b=e.length;c<b;++c)a.test(decodeURIComponent(e[c].replace(/\+/g,"%20")))&&(document.cookie=
e[c].split("=")[0]+"=; "+d+"expires=Sat, 31 Jan 1970 16:00:00 GMT")}else if(a=encodeURIComponent(a.replace(/\+/g,"%20")),document.cookie=a+"=; "+d+"expires=Sat, 31 Jan 1970 16:00:00 GMT",!a||c){a&&-1===a.indexOf("%5B")&&(a+="%5B");for(var j=a.length,c=0,b=e.length;c<b;++c)a===e[c].substr(0,j)&&(document.cookie=e[c].split("=")[0]+"=; "+d+"expires=Sat, 31 Jan 1970 16:00:00 GMT")}},get:function(a,c,d){var b=h.param.getType(a),e=document.cookie.split("; "),j=[];if("regexp"===b)for(var c=!0,i=0,g=e.length;i<
g;++i)a.test(decodeURIComponent(e[i].replace(/\+/g,"%20")))&&(j[j.length]=e[i]);else if(a){var a=encodeURIComponent(a.replace(/\+/g,"%20")),i=a.length+1,l={};l[a]=i;l[a+"="]=i;l[a+";"]=i;c&&(-1===a.indexOf("%5B")?l[a+"%5B"]=i+2:l[a]=i-1);i=0;for(g=e.length;i<g;++i){a:{var a=e[i],f=void 0;for(f in l)if(a.substr(0,l[f])===f){a=!0;break a}a=!1}a&&(j[j.length]=e[i])}}else if(""!==a||!0===c)j=e;if(j.length){if(c||"regexp"===b){if(d)return h.param.decode(j.join("; "),"; ",!0);d={};i=0;for(g=j.length;i<
g;++i)c=j[i].split("="),d[decodeURIComponent(c[0].replace(/\+/g,"%20"))]=decodeURIComponent((c[1]||"").replace(/\+/g,"%20"));return d}return decodeURIComponent((j[0].split("=")[1]||"").replace(/\+/g,"%20"))}},set:function(a,c,d,b,e){a=h.param.encode(a,"; ",!0,b).split("; ");e&&h.cookie.del(b,!0,d);d="string"!==typeof d?"; path=/":""===d?"":"; path="+d;(c=""+c)&&/^\d+$/.test(c)?(b=new Date,b.setTime(b.getTime()+parseInt(c)),c="; expires="+b.toGMTString()):/^\d{4}-\d{1,2}-\d{1,2}(?: \d{1,2}:\d{1,2}:\d{1,2})?$/.test(c)?
(b=c.split(" "),b[0]=b[0].split("-"),b[1]=b[1]?b[1].split(":"):[0,0,0],c="; expires="+new Date(b[0][0],b[0][1],b[0][2],b[1][0],b[1][1],b[1][2])):c="";b=0;for(e=a.length;b<e;++b)document.cookie=a[b]+d+c}},strVar:function(a,c,d){var b;if("string"===typeof a)b=window;else if(b=a,a=c,c=d,"object"!==typeof b||null===b)return;d="undefined"===typeof c?!0:!1;if("string"===typeof a){for(var a=a.replace(/\\\\/g,"\u00e6\u00e6").replace(/\\\./g,"\u00e7").replace(/\\\[/g,"\u00e8").split("."),e=0,h=a.length;e<
h;++e)if(""!==a[e]){var i=!1;a[e]=a[e].replace(/\u00e6\u00e6/g,"\\\\").replace(/\u00e7/g,".");"[]"===a[e].substr(a[e].length-2)&&(i=!0,a[e]=a[e].substr(0,a[e].length-2));a[e]=a[e].replace(/\u00e8/g,"[");"[object Array]"===Object.prototype.toString.apply(b)&&/-\d+/.test(a[e])&&(a[e]=b.length+parseInt(a[e]),0>a[e]&&(a[e]=0));if(d){if("undefined"===typeof b[a[e]])return;b=b[a[e]];if(i&&"[object Array]"!==Object.prototype.toString.apply(b))return}else if(e+1===h){if(i)if("undefined"===typeof b[a[e]])b[a[e]]=
[c];else if("[object Array]"===Object.prototype.toString.apply(b[a[e]]))b[a[e]].push(c);else return;else b[a[e]]=c;b=c}else if("undefined"===typeof b[a[e]])b[a[e]]=i?[]:{},b=b[a[e]];else if("object"===typeof b[a[e]]&&null!==b[a[e]])b=b[a[e]];else return}return b}},getWindow:function(a){return a.window&&a.window===a.window.window&&a||(a=a.ownerDocument||a).defaultView||a.parentWindow},each:function(){var a=h.param.getType(arguments[0]),c=[0,arguments[0]],d=null;if(("array"===a||"object"===a)&&1<arguments.length){"function"===
typeof arguments[1]?(d=arguments[1],a=2):(arguments.callee.defaultFun||(arguments.callee.defaultFun=function(a,b){for(var c=2,d=arguments.length;c<d;++c)arguments[c][a]=b[a]}),d=arguments.callee.defaultFun,a=1);for(var b=a,a=arguments.length;b<a;++b)c[c.length]=arguments[b];for(b in arguments[0])if(c.splice(0,1,b),void 0!==(a=d.apply(window,c)))return a;return null}},openCom:function(a,c,d){var b={js:[],css:[],returnObj:null,onload:null};d||(d=window);if("wDate"===a)if(b.returnObj=function(){c&&"object"===
typeof c&&(c.obj?("INPUT"===c.obj.tagName&&!/\bWdate\b/.test(c.obj.className)&&(c.obj.className+=" Wdate"),d.L.onEvent.addEvent(c.obj,c.eventType||"click",function(){WdatePicker(c.params)})):d.WdatePicker(c.params));return WdatePicker},"function"!==typeof d.WdatePicker)a=document.createElement("script"),a.type="text",a.src=this._rootUrl+"/js/components/WDatePicker/WdatePicker.js",document.getElementsByTagName("head")[0].appendChild(a),b.js.push("/js/components/WDatePicker/WdatePicker.js");else return b.returnObj();
else if("zTree"===a){null==$.fn.zTree&&(b.js.push("/js/components/zTree/jquery.ztree.core.js"),b.css.push("/style/components/zTree/zTreeStyle.css"));if(a=this.strVar(c,"expand[]"))for(var e=0,g=a.length;e<g;++e)"excheck"===a[e]&&"_check"===this.strVar($.fn,"zTree.consts.id.CHECK")||"exedit"===a[e]&&"_edit"===this.strVar($.fn,"zTree.consts.id.EDIT")||b.js.push("/js/components/zTree/jquery.ztree."+a[e]+".js");if(b.js.length)b.returnObj=function(){return $.fn.zTree};else return $.fn.zTree}else if("tip"===
a||"oDialogDiv"===a||"oFM"===a||"oEditor"===a||"upload"===a)switch("function"!==typeof d.mouseDrag&&b.js.push("/include/oFileManager/js/mouseDrag.js"),"function"!==typeof d.oDialogDiv&&(b.js.push("/include/oFileManager/js/oDialogDiv.js"),b.onload=function(){d.oDialogDiv.initStatus=!0}),("function"!==typeof d.oDialogDiv||null==d.oDialogDiv.initStatus)&&b.css.push("/include/oFileManager/style/oDialogDiv.css"),a){case "tip":if("function"!==typeof d.oDialogDiv)b.returnObj=function(){return d.oDialogDiv.tip};
else return d.oDialogDiv.tip;break;case "oDialogDiv":if("function"!==typeof d.oDialogDiv)b.returnObj=function(){return d.oDialogDiv};else return d.oDialogDiv;break;case "oFM":if("function"!==typeof d.oFileManager)b.js.push("/include/oFileManager/js/jsCalloFileManager.js"),b.returnObj=function(){oFileManager.oFileManagerMainDir=h._rootUrl+"/include/oFileManager";return d.oFileManager};else return d.oFileManager;break;case "oEditor":d._ROOT_URL=this._rootUrl;d.oFileManagerMainDir="/include/oFileManager";
if("function"!==typeof d.oEditor)b.js.push("/include/oFileManager/js/jsCalloFileManager.js"),b.js.push("/include/oFileManager/include/oEditor/oEditor.js"),b.returnObj=function(){oFileManager.oFileManagerMainDir=h._rootUrl+"/include/oFileManager";return d.oEditor};else return d.oEditor;break;case "upload":if(d._ROOT_URL=this._rootUrl,d.oFileManagerMainDir="/include/oFileManager","function"!==typeof d.jsCalloEditorUploadify)b.css.push("/include/oFileManager/include/uploadify/css/uploadify.css"),b.js.push("/include/oFileManager/include/uploadify/scripts/jsCalloEditorUploadify.js"),
b.js.push("/include/oFileManager/include/uploadify/scripts/swfobject.js"),b.js.push("/include/oFileManager/include/uploadify/scripts/jqueryUploadify.js"),b.returnObj=function(){return d.jsCalloEditorUploadify};else return d.jsCalloEditorUploadify}else return;e=0;for(g=b.css.length;e<g;++e)this.AJAX({url:this._rootUrl+b.css[e],type:"get",async:!1,context:this,success:function(a,b){var c=d.document.createElement("div"),a=a.replace(/url\((\'|\"|)([\w\/\.]*)\1\)/ig,function(a,c,d){a=d.replace(/^(?:\.\/|\/)*((?:\.\.\/)+)/,
function(a,c){return b.url.replace(RegExp("(/[^/]+){"+(c.length/3+1)+"}$"),"")+"/"});return a='url("'+a+'")'});c.innerHTML='div<div><style type="text/css">'+a+"</style></div>";d.document.body.appendChild(c.getElementsByTagName("div")[0].firstChild)}});e=0;for(g=b.js.length;e<g;++e)this.AJAX({url:this._rootUrl+b.js[e],type:"get",async:!1,context:d,success:function(a){(d.execScript||function(a){d.eval.call(d,a)})(a)}});if("function"===typeof b.onload)b.onload();if(null!==b.returnObj)return b.returnObj()},
init:function(a,c){g=a;o=c;t();delete this.init},extension:{}}}})();
