function ofPlayerClass(i){this.Config={setInterval:{obj:null,list:[]},ofPlayerVar:{conf:{PlayCount:0},skin:{},list:{}},ready:{readied:!1,list:[]}};this.$=function(a){if("string"==typeof a)return document.getElementById(a);"function"==typeof a&&(this.Config.ready.readied?a.apply(this):this.Config.ready.list[this.Config.ready.list.length]=a);return a};this.setStyleCSS=function(a,b,c){0==document.styleSheets.length&&document.body.appendChild(document.createElement("style"));for(var d=document.styleSheets[document.styleSheets.length-
1],f=d.cssRules?d.cssRules:d.rules,e=null,h="",g=0;g<f.length;g++)if(f[g].selectorText==a){e=g;break}if(null==e){if(d.insertRule)d.insertRule(a+"{"+b+":"+c+"}",f.length);else for(g in e=a.split(","),e)d.addRule(e[g],b+":"+c,f.length);e=f.length}else h=f[e].style[b],f[e].style[b]=c;return{rulesObj:f,index:e,attribute:a,key:b,value:h}};this.is_array=function(a){return a&&"object"===typeof a&&"number"===typeof a.length&&"function"===typeof a.splice&&!a.propertyIsEnumerable("length")};this.ofPlayerAutoFn=
function(){var a=this.jsOfPlayerFn("getinfo","fileinfo"),b=this.jsOfPlayerFn("getinfo","playback");if(a&&b){var c=this.jsOfPlayerFn("getatt","bigPlay","y");"swf"==a.type&&0<c?(this.Config.ofPlayerVar.skin.bigPlayY=c,this.jsOfPlayerFn("adjust","bigPlay","y",-1E3)):"swf"!=a.type&&0>c&&this.jsOfPlayerFn("adjust","bigPlay","y",this.Config.ofPlayerVar.skin.bigPlayY);1E3>b.position?this.Config.ofPlayerVar.conf.PlayCountTime=!0:!0===this.Config.ofPlayerVar.conf.PlayCountTime&&b.position>a.duration-1E3&&
(this.Config.ofPlayerVar.conf.PlayCountTime=!1,this.Config.ofPlayerVar.conf.PlayCount++,isNaN(this.Config.ofPlayerVar.list[a.url+a.title+"Count"])&&(this.Config.ofPlayerVar.list[a.url+a.title+"Count"]=0),this.Config.ofPlayerVar.list[a.url+a.title+"Count"]++);a=this.Config.ready;a.readied||(a.readied=!0);if(a.list.length){a.readied=!0;for(b=0;b<a.list.length;b++)"function"==typeof a.list[b]&&a.list[b].apply(this);a.list=[]}}};this.startIntervalFn=function(){null==this.Config.setInterval.obj&&(this.Config.setInterval.obj=
setInterval(this.setIntervalFn.ofPlayerClassClosure(this),300))};this.stopIntervalFn=function(){this.Config.setInterval.obj&&clearInterval(this.Config.setInterval.obj)};this.setIntervalFn=function(){var a=this.Config.setInterval.list;if("function"===typeof JS_OFplayer)for(var b in a)if(0!=a[b].count){a[b].count--;try{a[b].fn.apply(this,a[b].vars.concat([b]))}catch(c){}}else a.splice(b,1)};this.insterIntervalFn=function(a,b,c){a&&(this.is_array(b)||(b=[]),isNaN(parseInt(c))&&(c=1),this.Config.setInterval.list[this.Config.setInterval.list.length]=
{fn:a,vars:b,count:c,customize:{}})};this.removeIntervalFn=function(a){var b=this.Config.setInterval.list;if("function"==typeof a)for(var c in b)b[c].fn==a&&b.splice(c,1);else b.splice(a,1)};this.getIntervalFn=function(a){var b=this.Config.setInterval.list,c=[];if("function"==typeof a){for(var d in b)b[d].fn==a&&(c[c.length]=b[d]);return c}return b[a]};this.setWidth=function(a,b){var c=this.$(this.ofPlayerObj.id);null!=c&&(embedObj=c.getElementsByTagName("embed")[0],null!=a&&(c.width=a,null!=embedObj&&
(embedObj.width=a)),null!=b&&(c.height=b,null!=embedObj&&(embedObj.height=b)),this.jsOfPlayerFn("event","normalScreen"))};this.jsOfPlayerFn=function(a,b,c,d){if(null!=a)return a=""+("JS_OFplayer('"+this.ofPlayerObj.id+"','"+a+"'"),null!=b&&(a+=",'"+b+"'",null!=c&&(a+=",'"+c+"'",null!=d&&(a+=",'"+d+"'"))),eval(a+");")};this.instance=function(a){if(this.ofPlayerObj.obj=this.$(a))null==this.ofPlayerObj.ofPlayerObj&&(a=document.createElement("div"),a.innerHTML=this.ofPlayerObj.html,this.ofPlayerObj.ofPlayerObj=
a.firstChild),this.ofPlayerObj.obj.appendChild(this.ofPlayerObj.ofPlayerObj),this.insterIntervalFn(this.ofPlayerAutoFn,"",-1),this.startIntervalFn()};this.removeOfPlayer=function(){this.stopIntervalFn();this.ofPlayerObj.ofPlayerObj.parentNode.removeChild(this.ofPlayerObj.ofPlayerObj)};this.init=function(a){try{version=Boolean(null!=navigator.plugins&&0<navigator.plugins.length?navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]:new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))}catch(b){version=
!1}!1===version?this.$(a.obj).innerHTML='<a target="_blank" href="http://get.adobe.com/flashplayer/"><img src="'+a.url.substr(0,a.url.length-28)+'/images/flashInstall.jpg"/></a>':(a.id=a.id?a.id:"ofPlayer_id"+(new Date).getTime(),a.width=a.width?a.width:"100%",a.height=a.height?a.height:"100%",a.wmode="transparent"==a.wmode?a.wmode:"opaque",a.html="",a.html+='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" ',a.html+='width="'+a.width+'" ',a.html+='height="'+a.height+'" ',a.html+='id="'+
a.id+'"',a.html+=">",a.html+='<param name="movie" value="'+a.url+'" />',a.html+='<param name="allowFullScreen" value="true" />',a.html+='<param name="allowScriptAccess" value="always" />',a.html+='<param name="quality" value="high" />',a.html+='<param name="wmode" value="'+a.wmode+'" />',a.html+='<param name="flashvars" value="'+a.vars+'" />',a.html+='<embed type="application/x-shockwave-flash" ',a.html+='width="'+a.width+'" ',a.html+='height="'+a.height+'" ',a.html+='name="'+a.id+'" ',a.html+='src="'+
a.url+'" ',a.html+='allowfullscreen="true" ',a.html+='allowscriptaccess="always" ',a.html+='quality="high" ',a.html+='wmode="'+a.wmode+'" ',a.html+='flashvars="'+a.vars+'"',a.html+="></embed>",a.html+="</object>",this.ofPlayerObj=a,this.ofPlayerObj.Config=this.Config,this.instance(a.obj))};null==Function.prototype.ofPlayerClassClosure&&(Function.prototype.ofPlayerClassClosure=function(a){var b=this;return function(){return b.apply(a)}});this.setStyleCSS("html,body","height","100%");this.init(i)};
