function examscoreInitExamscoreManage(){initResetArea({selection:"#examscore_search_param_div",id:"examscore_search_param_div"});window.L.openCom("wDate",{obj:$("#exam_begin_tm").get(0),params:{readOnly:!0}});window.L.openCom("wDate",{obj:$("#exam_end_tm").get(0),params:{readOnly:!0}});window.L.openCom("oDialogDiv")}function examscoreResetSearchParams(){resetArea("examscore_search_param_div");examscoreInitExamscoreManage()}
function examscoreSearchExamscoreList(){var b=examscoreGetSearchCondition(),a=$('table[_pagetabledataset="admin_examscore_examscoreCtl::displayCheckExamScoreList"]');window.L.extension.pageTable.classObj.params(a.get(0),b,!0)}
function examscoreGetSearchCondition(){return{exam_name:escape($.trim($("#exam_name").val())),exam_times:$("#exam_times").val(),user_name:$("#user_name").val(),exam_category:"3"==$("#exam_category").val()?"":$("#exam_category").val(),group_id:"0"==$("#group_id").val()?"":$("#group_id").val(),exam_begin_tm:$("#exam_begin_tm").val(),exam_end_tm:$.trim($("#exam_end_tm").val()),is_failed:$("#is_failed").val()}}
function examscoreUpdateScore(b){var a={},d="success",e="";if("selected"==b){var c,f=!1;$(":checkbox[name='es_cb']:checked").each(function(b){var g=$(this).val().split("_");f=!0;a[b]={};c=$(this).val().split("_");a[b].exam_id=c[0];a[b].user_id=c[1];a[b].exam_times=c[2];a[b].exam_score=parseFloat($("#es_text_"+g[0]+"_"+g[1]+"_"+g[2]).val());if(isNaN(a[0].exam_score))return d="failed",e=window.L.getText("\u8003\u8bd5\u6210\u7ee9\u5fc5\u987b\u4e3a\u6709\u6548\u7684\u6570\u5b57"),!1});f||(d="failed",
e=window.L.getText("\u8bf7\u81f3\u5c11\u9009\u4e2d\u4e00\u6761\u6570\u636e"))}else c=b.split("_"),a[0]={},a[0].exam_id=c[0],a[0].user_id=c[1],a[0].exam_times=c[2],a[0].exam_score=parseFloat($("#es_text_"+b).val()),isNaN(a[0].exam_score)&&(d="failed",e=window.L.getText("\u8003\u8bd5\u6210\u7ee9\u5fc5\u987b\u4e3a\u6709\u6548\u7684\u6570\u5b57"));"success"==d?(b=window.L._adminUrl+"/examscore/examscoreCtl.php?a=updateUserExamscore",a="params="+encodeURIComponent(L.JSON.stringify(a)),$.ajax({type:"POST",
async:!1,url:b,data:a,dataType:"json",success:function(a){"success"==a.res?oDialogDivInfo(window.L.getText("\u66f4\u65b0\u6210\u529f")):oDialogDivInfo(a.info)},error:function(){}})):oDialogDivInfo(e)}
function examscoreAlertDeleteScore(){var b=window.L.getText("\u6ce8\uff1a\u6b64\u64cd\u4f5c\u4e0d\u53ef\u6062\u590d")+'<br><a href="javascript:void(0)" onclick="examscoreDeleteScore(\'selected\')" class="btn2" >'+window.L.getText("\u5220\u9664\u9009\u4e2d\u6210\u7ee9")+'</a><a href="javascript:void(0)" onclick="examscoreDeleteScore(\'search\')" class="btn2" >'+window.L.getText("\u5220\u9664\u641c\u7d22\u6210\u7ee9")+'</a><a href="javascript:void(0)" onclick="alertCloseAlertDiv()" class="btn2" >'+
window.L.getText("\u5173\u95ed")+"</a>";window.L.openCom("oDialogDiv")&&(ALERT_DIV_MARK=oDialogDiv(window.L.getText("\u5220\u9664\u6210\u7ee9"),"text:"+b,"auto","auto",[1]))}
function examscoreDeleteScore(b){var a={params:{},del_method:"selected",del_condition:{}},d="success",e="",c=0;if("selected"==b){var f;$(":checkbox[name='es_cb']:checked").each(function(b){c++;a.params[b]={};f=$(this).val().split("_");a.params[b].exam_id=f[0];a.params[b].user_id=f[1];a.params[b].exam_times=f[2];a.params[b].exam_score=$("#es_text_"+$(this).val()).val()});void 0==a.params[0]&&(d="failed",e=window.L.getText("\u8bf7\u81f3\u5c11\u9009\u62e9\u4e00\u6761\u6570\u636e"))}else"search"==b?(a.del_method=
"search",a.del_condition=examscoreGetSearchCondition()):(f=b.split("_"),a.params[0]={},a.params[0].exam_id=f[0],a.params[0].user_id=f[1],a.params[0].exam_times=f[2],a.params[0].exam_score=$("#es_text_"+b).val());"success"==d?oDialogDiv(window.L.getText("\u786e\u5b9a\u5220\u9664\uff1f"),'text:<div style="width:200px; height:30px;">'+window.L.getText("\u786e\u8ba4\u5220\u9664\u6210\u7ee9")+"?</div>","auto","auto",[2,function(b){b&&(b=window.L._adminUrl+"/examscore/examscoreCtl.php?a=deleteUserExamscore",
a="params="+encodeURIComponent(L.JSON.stringify(a)),$.ajax({type:"POST",async:!1,url:b,data:a,dataType:"json",success:function(a){"success"==a.res?(oDialogDivInfo(window.L.getText("\u5220\u9664\u7528\u6237\u6210\u7ee9\u6210\u529f")),a=$('table[_pagetabledataset="admin_examscore_examscoreCtl::displayCheckExamScoreList"]'),""!=ALERT_DIV_MARK&&(alertCloseAlertDiv(),ALERT_DIV_MARK=""),window.L.extension.pageTable.classObj.pageClickFn(a.get(0),0)()):oDialogDivInfo(a.info)},error:function(){}}))}]):oDialogDivInfo(e)}
function examscoreAlertRemakeScore(){var b=window.L.getText("\u6ce8\uff1a\u6b64\u64cd\u4f5c\u4e0d\u53ef\u6062\u590d")+'<br><a href="javascript:void(0)" onclick="examscoreRemakeScore(\'selected\')" class="btn2" >'+window.L.getText("\u91cd\u7b97\u9009\u4e2d\u6210\u7ee9")+'</a><a href="javascript:void(0)" onclick="examscoreRemakeScore(\'search\')" class="btn2" >'+window.L.getText("\u91cd\u7b97\u641c\u7d22\u6210\u7ee9")+'</a><a href="javascript:void(0)" onclick="alertCloseAlertDiv()" class="btn2" >'+
window.L.getText("\u5173\u95ed")+"</a>";window.L.openCom("oDialogDiv")&&(ALERT_DIV_MARK=oDialogDiv(window.L.getText("\u91cd\u7b97\u6210\u7ee9"),"text:"+b,"auto","auto",[1]))}
function examscoreRemakeScore(b){var a={params:{},remake_method:"selected",remake_condition:{}},d="success",e="";if("selected"==b){var c;$(":checkbox[name='es_cb']:checked").each(function(b){a.params[b]={};c=$(this).val().split("_");a.params[b].exam_id=c[0];a.params[b].user_id=c[1];a.params[b].exam_times=c[2];a.params[b].papr_id=c[3];a.params[b].exam_score=$("#es_text_"+$(this).val()).val()});void 0==a.params[0]&&(d="failed",e=window.L.getText("\u8bf7\u81f3\u5c11\u9009\u62e9\u4e00\u6761\u6570\u636e"))}else"search"==
b?(a.remake_method="search",a.remake_condition=examscoreGetSearchCondition()):(c=b.split("_"),a.params[0]={},a.params[0].exam_id=c[0],a.params[0].user_id=c[1],a.params[0].exam_times=c[2],a.params[0].papr_id=c[3],a.params[0].exam_score=$("#es_text_"+b).val());"success"==d?(b=window.L._adminUrl+"/examscore/examscoreCtl.php?a=remakeUserExamScore",a="params="+encodeURIComponent(L.JSON.stringify(a)),$.ajax({type:"POST",async:!1,url:b,data:a,dataType:"json",success:function(a){"success"==a.res?(oDialogDivInfo(window.L.getText("\u91cd\u7b97\u6210\u529f")),
a=$('table[_pagetabledataset="admin_examscore_examscoreCtl::displayCheckExamScoreList"]'),""!=ALERT_DIV_MARK&&(alertCloseAlertDiv(),ALERT_DIV_MARK=""),window.L.extension.pageTable.classObj.pageClickFn(a.get(0),0)()):oDialogDivInfo(a.info)},error:function(){}})):oDialogDivInfo(e)}
function examscoreAlertExportScore(){var b='<a href="javascript:void(0)" onclick="examscoreExportScore(\'selected\')" class="btn2" >'+window.L.getText("\u5bfc\u51fa\u9009\u4e2d\u6210\u7ee9")+'</a><a href="javascript:void(0)" onclick="examscoreExportScore(\'search\')" class="btn2" >'+window.L.getText("\u5bfc\u51fa\u641c\u7d22\u6210\u7ee9")+'</a><a href="javascript:void(0)" onclick="alertCloseAlertDiv()" class="btn2" >'+window.L.getText("\u5173\u95ed")+"</a>";window.L.openCom("oDialogDiv")&&(ALERT_DIV_MARK=
oDialogDiv(window.L.getText("\u5bfc\u51fa\u6210\u7ee9"),"text:"+b,"auto","auto",[1]))}
function examscoreExportScore(b){var a={params:{},export_method:"selected",export_condition:{}},d="success",e="";if("selected"==b){var c;$(":checkbox[name='es_cb']:checked").each(function(b){a.params[b]={};c=$(this).val().split("_");a.params[b].exam_id=c[0];a.params[b].user_id=c[1];a.params[b].exam_times=c[2];a.params[b].exam_score=$("#es_text_"+$(this).val()).val()});void 0==a.params[0]&&(d="failed",e=window.L.getText("\u8bf7\u81f3\u5c11\u9009\u62e9\u4e00\u6761\u6570\u636e"))}else"search"==b&&(a.export_method=
"search",a.export_condition=examscoreGetSearchCondition());"success"==d?(a=encodeURIComponent(L.JSON.stringify(a)),$("#export_params").val(a),$("#examscore_export_form").submit()):oDialogDivInfo(e)}function examCategoryTreeShow(b,a,d){getTree({targetNameId:b,targetValueId:a,dataType:"exam_category",showRoot:d?d:!1})}function examGroupTreeShow(b,a,d){getTree({targetNameId:b,targetValueId:a,dataType:"group",showRoot:d?d:!1})}
function examAlertExamUserList(b,a,d){var e=window.L._adminUrl+"/examscore/examscoreCtl.php?";ALERT_DIV_MARK=oDialogDiv(window.L.getText("\u4eba\u5458\u5217\u8868"),"iframe:"+e+'{"get":{"a":"alertExamUserList"}, "post" : {"exam_id":"'+b+'","exam_times":"'+a+'","list_type":"'+d+'"}}',"800px","600px",[1],10,!0)}function exportExamUserList(b,a,d){window.open(window.L._adminUrl+"/examscore/examscoreCtl.php?a=exportExamUserList&exam_id="+b+"&exam_times="+a+"&list_type="+d)};
