var coursewareObj={beforeUnloadTip:function(a){if(arguments.callee.tipState)return a.originalEvent.returnValue=""}};
function updateImgPageTable(a){var c,b=L.extension.pageTable.classObj;c="coursewareImgAttPageTable"===a.id?$("#remoteUrl"):$("#lectureText");c.val($.trim(c.val()));if("img"===c.attr("coursewareType")&&""!==c.val()){var e=window.L.JSON.parse(c.val()),d;for(d in e)"string"===typeof e[d]&&(e[d]={src:e[d],disabled:!0});c.val(window.L.JSON.stringify(e));b.params(a,{id:a.id,strData:c.val()});b.load(a)}else b.params(a,{id:a.id},!0)}function maxImgPreview(){window.L.openCom("oDialogDiv").skinLayout()}
function qsnAddTag(a,c){"undefined"===typeof qsnAddTag.tagList[a]&&(qsnAddTag.tagList[a]=!0,$('<span id="tag_'+a+'"><a class="" href="#" onclick="return false;" >'+c+'</a><a class="icon_del" onclick="delQsnAddTag(\''+a+"')\"></a></span>").appendTo("#tagList"))}qsnAddTag.tagList={};$("#tagList > span").each(function(){qsnAddTag.tagList[this.id.split("_")[1]]=!0});function delQsnAddTag(a){$("#tag_"+a).remove();delete qsnAddTag.tagList[a]}
window.L.strVar("L.extension.pageTable.callback.initLoadList[]",window.L.strVar("L.extension.pageTable.callback.afterLoadList[]",function(a){var c=$("tfoot:first .content a",a),b=$("coursewareImgAttPageTable"===a.id?"#remoteUrl":"#lectureText"),e=function(e,a,d){var c=window.L.JSON.parse(b.val());c[a].disabled=d;e.childNodes[4].innerHTML=window.L.getText(d?"\u542f\u7528":"\u7981\u7528");b.val(window.L.JSON.stringify(c));return!1},d=function(e,a){var d=window.L.JSON.parse(b.val());d.splice(a,1);b.val(window.L.JSON.stringify(d));
return!1},g=function(e,a,d){var c=window.L.JSON.parse(b.val());!isNaN(a)&&0<=a?(a>=c.length&&(a=c.length-1),c.splice(a,0,c.splice(d,1)[0]),b.val(window.L.JSON.stringify(c)),updateImgPageTable(e)):window.L.openCom("tip")(window.L.getText("\u6392\u5e8f\u4f4d\u7f6e\u4e0d\u660e\u786e"))};c.eq(0).click(function(){$("tbody input:checkbox:checked",a).each(function(b){d(a,parseInt(this.getAttribute("key"),10)-b)});updateImgPageTable(a);return!1});c.eq(1).click(function(){$("tbody input:checkbox:checked",
a).each(function(){e(this.parentNode.parentNode,this.getAttribute("key"),!0)});return!1});c.eq(2).click(function(){$("tbody input:checkbox:checked",a).each(function(){e(this.parentNode.parentNode,this.getAttribute("key"),!1)});return!1});$('tbody input[class="input_sort"]',a).keypress(function(b){"13"==b.keyCode&&(b=parseInt(this.value,10)-1,g(a,b,this.getAttribute("key")))});var h=$('<div style="position: relative;"><div class="action_toolbar"><div class="inner_box"><div class="action_link"><a href="#">'+
window.L.getText("\u5220\u9664")+'</a><a href="#">'+window.L.getText("\u7981\u7528")+'</a><a href="#">'+window.L.getText("\u4e0a\u79fb")+'</a><a href="#">'+window.L.getText("\u4e0b\u79fb")+'</a></div></div><div class="action_toolbar_right"></div></div></div>'),f=h.get(0),i=h.find("a");i.eq(0).click(function(){d(a,$(this).parentsUntil("tbody").eq(-1).find("td:eq(0) input").attr("key"));updateImgPageTable(a);return!1});i.eq(1).click(function(){var a=window.L.JSON.parse(b.val()),d=$(this).parentsUntil("tbody").eq(-1),
c=d.find("td:eq(0) input").attr("key"),a=a[c].disabled;$(this).html(window.L.getText(a?"\u542f\u7528":"\u7981\u7528"));e(d.get(0),c,!a);return!1});i.eq(2).click(function(){var b=parseInt($(this).parentsUntil("tbody").eq(-1).find("td:eq(0) input").attr("key"),10);g(a,b-1,b);return!1});i.eq(3).click(function(){var b=parseInt($(this).parentsUntil("tbody").eq(-1).find("td:eq(0) input").attr("key"),10);g(a,b+1,b);return!1});$("tbody tr",a).hover(function(){if($(".action",this).length)try{var a=window.L.JSON.parse(b.val());
i.eq(1).html(window.L.getText(a[$(this).find("td:eq(0) input").attr("key")].disabled?"\u7981\u7528":"\u542f\u7528"));h.appendTo($(".action",this))}catch(e){}},function(){if($(".action",this).length)try{f.parentNode.removeChild(f)}catch(b){}});var j=function(b){var a,e=b[2];a="coursewareImgAttPageTable"===b[1]?$("#remoteUrl"):$("#lectureText");return function(d){var c=window.L.JSON.parse(a.val());c[e].src=d.substr((window.browseHome+window.coursewareAttFolder).length);a.val(window.L.JSON.stringify(c));
updateImgPageTable(document.getElementById(b[1]))}};$(a).find("input[type=file]").each(function(){window.L.openCom("upload")(this.id,j(this.id.split("_")),"jpg;gif;png",'<font color="#1A5F9B" size="13" >'+window.L.getText("\u66f4\u6362\u56fe\u7247")+"</font>",60,15,{auto:!0,queueID:!0,multi:!1,folder:window.coursewareAttFolder})});$(a).find("img").click(function(){window.L.openCom("oDialogDiv")("",'text:<img src="'+$(this).attr("bigImg")+'" onload="maxImgPreview()" />')})}));
$(function(){var a={onSelectOnce:function(b){var a=document.getElementById("remoteUrl");!1!==b&&($("input[name=coursewareType]").prop("disabled",!0),window.L.openCom("tip")(window.L.getText("\u6b63\u5728\u4e0a\u4f20\u8bf7\u7a0d\u540e"),!1));"img"===$("input[name=coursewareType]:checked").val()?(a.tempUrlList=window.L.JSON.parse(a.value),$.isArray(a.tempUrlList)||(a.tempUrlList=[])):a.tempUrlList=[]}};a.onComplete=a.onCancel=function(b,a){var d=$("input[name=coursewareType]:checked").val();"string"===
typeof b&&document.getElementById("remoteUrl").tempUrlList.push(("img"===d?b:unescape(b)).substr((window.browseHome+window.coursewareAttFolder).length));if(!0!==a&&0==$("#coursewareUpload").attr("fileCount")){var c="",c="img"===d?window.L.JSON.stringify(document.getElementById("remoteUrl").tempUrlList):document.getElementById("remoteUrl").tempUrlList.join(",");""!==$.trim(c)&&($("#remoteUrl").val(c).attr("coursewareType",d),$("input[name=coursewareType]:checked").parent().siblings().css("fontWeight",
"normal").end().css("fontWeight","bold"),updateImgPageTable(document.getElementById("coursewareImgAttPageTable")));$("input[name=coursewareType]").prop("disabled",!1);window.L.openCom("tip")()}};window.L.openCom("upload")("coursewareUpload",a,"",'<font color="#444444" size="13" >'+window.L.getText("\u70b9\u51fb\u4e0a\u4f20")+"</font>",60,15,{auto:!0,queueID:"coursewareUploadProgress",multi:!1,folder:window.coursewareAttFolder});$("#selectMediaFile").click(function(){a.onSelectOnce(!1);window.L.openCom("oFM")(function(b){a.onComplete(b.url,
!0);window.L.openCom("tip")(window.L.getText("\u6dfb\u52a0\u6210\u529f"),null,!1)},{closeCallBackFun:a.onComplete},"img"!==$("input[name=coursewareType]:checked").val(),{fileExt:this.getAttribute("fileext"),selectExt:this.getAttribute("fileext"),browseDir:window.coursewareAttFolder});return!1});$("#remoteUrl").focus(function(){window.L.openCom("tip")(window.L.getText("\u60a8\u6240\u586b\u5199\u7684\u975e\u7a7a\u8def\u5f84\u5c06\u66ff\u6362\u539f\u6765\u7684\u8bfe\u4ef6\u5730\u5740"),!1);$(this).attr("coursewareUrlText",
$.trim(this.value))}).blur(function(){window.L.openCom("tip")();this.value=$.trim(this.value);""!==this.value&&$(this).attr("coursewareUrlText")!==this.value&&($(this).attr("coursewareType",$("input[name=coursewareType]:checked").val()),$("input[name=coursewareType]:checked").parent().siblings().css("fontWeight","normal").end().css("fontWeight","bold"));$(this).removeAttr("coursewareUrlText")});$("input[name=localOrRemote]").click(function(){var b=$("#selectMediaFile"),a=$("#remoteUrl");"local"===
this.value?($("#coursewareUploadUploader").css("visibility","visible"),b.show(),a.hide()):(b.hide(),a.show(),window.setTimeout(function(){var b=document.getElementById("coursewareUploadUploader");b.style.visibility="hidden";b.updateSettings||window.setTimeout(arguments.callee,100)},0))});$("#delCoursewareAtt").click(function(){window.L.openCom("oDialogDiv")(window.L.getText("\u786e\u5b9a\u5220\u9664\u8bfe\u4ef6?"),"","auto","auto",[[window.L.getText("\u786e\u5b9a"),window.L.getText("\u53d6\u6d88")],
function(b){0===b&&($("input[name=coursewareType]:checked").parent().siblings().css("fontWeight","normal"),$("#remoteUrl").attr("coursewareType","none").val(""),updateImgPageTable(document.getElementById("coursewareImgAttPageTable")),$("input[name=coursewareType][value=none]").click().parent().siblings().css("fontWeight","normal").end().css("fontWeight","bold"))}]);return!1});$("input[name=coursewareType]").click(function(){var b=$("#selectMediaFile"),a=$("#coursewareTypeUploadBlock"),c=a.find(".thumb_default_upload:eq(0)"),
g=a.find(".right > div:eq(0)"),h=a.find("table:eq(0)"),f=function(b,a){window.L.openCom("upload").updateSettings("coursewareUpload",b,a)};if("none"===this.value){if("none"!==$("#remoteUrl").attr("coursewareType"))return $("#delCoursewareAtt").click(),!1;a.hide()}else a.show(),h.parent().hide(),$("input[name=localOrRemote]").parent().show(),f("multi",!1),"img"===this.value?(h.parent().show(),$("input[name=localOrRemote]").eq(1).parent().hide().end().end().eq(0).click(),f("multi",!0)):"youku"===this.value&&
$("input[name=localOrRemote]").eq(0).parent().hide().end().end().eq(1).click();switch(this.value){case "flv":g.html(window.L.getText("\u4e0a\u4f20FLV\u683c\u5f0f\u89c6\u9891(\u6700\u4f73\u5c3a\u5bf8\uff1a969 x 528 \u50cf\u7d20)\uff1a"));c.prop("className","thumb_default_upload");b.attr("fileExt","flv");f("fileExt","*.flv;");f("fileDesc",window.L.getText("\u73b0\u5728\u8bf7\u9009\u62e9\u4e00\u4e2a.flv\u6587\u4ef6"));break;case "swf":g.html(window.L.getText("\u4e0a\u4f20SWF\u683c\u5f0f\u89c6\u9891(\u6700\u4f73\u5c3a\u5bf8\uff1a969 x 528 \u50cf\u7d20)\uff1a"));
c.prop("className","thumb_default_upload thumb_swf");b.attr("fileExt","swf");f("fileExt","*.swf;");f("fileDesc",window.L.getText("\u73b0\u5728\u8bf7\u9009\u62e9\u4e00\u4e2a.swf\u6587\u4ef6"));break;case "mp3":g.html(window.L.getText("\u4e0a\u4f20MP3\u683c\u5f0f\u97f3\u9891\u6587\u4ef6\uff1a"));c.prop("className","thumb_default_upload thumb_music");b.attr("fileExt","mp3");f("fileExt","*.mp3;");f("fileDesc",window.L.getText("\u73b0\u5728\u8bf7\u9009\u62e9\u4e00\u4e2a.mp3\u6587\u4ef6"));break;case "youku":g.html(window.L.getText("\u586b\u5199\u4f18\u9177\u8fde\u63a5\u5730\u5740"));
c.prop("className","thumb_default_upload");b.attr("fileExt",".");f("fileExt","*.;");break;case "img":g.html(window.L.getText("\u4e0a\u4f20\u56fe\u7247\u683c\u5f0f\u7684\u6587\u6863\uff1a")),c.prop("className","thumb_default_upload thumb_default_doc"),b.attr("fileExt","jpg;png;gif"),f("fileExt","*.jpg;*.png;*.gif;"),f("fileDesc",window.L.getText("\u8bf7\u60a8\u9009\u62e9.jpg\u3001png\u6216.gif\u6587\u4ef6")),L.extension.pageTable.classObj.initCustomNav(document.getElementById("coursewareImgAttPageTable"))}});
$("input[name=coursewareType][value="+$("#remoteUrl").attr("coursewareType")+"]").click().parent().siblings().css("fontWeight","normal").end().css("fontWeight","bold");/\w+:\/\/.*/.test($("#remoteUrl").val())&&$("input[name=localOrRemote]:eq(1)").click();$("#calculationHours").click(function(){var b=$("#remoteUrl").val(),a=$("#remoteUrl").attr("coursewareType");if("mp3"===a||"flv"===a||"youku"===a){window.L.openCom("tip")(window.L.getText("\u6b63\u5728\u8ba1\u7b97\u8bf7\u7a0d\u7b49..."),!1);if("youku"===
a){if($.ajax({async:!1,url:"?a=getYoukuMediaId",type:"post",data:{url:b},success:function(a){b=a}}),alert(b),""!==b){window.L.openCom("tip")(window.L.getText("\u60a8\u6240\u9009\u62e9\u7684\u8bfe\u4ef6\u65e0\u6cd5\u8ba1\u7b97\u5b66\u65f6"));return}}else b=/^\w+:\/\/.+$/.test(b)?b:window.L._rootUrl+window.browseHome+window.coursewareAttFolder+b;this.disabled=!0;var c=new ofPlayerClass({url:window.L._rootUrl+"/include/oFileManager/include/player/ofplayer.swf",vars:"Ctn=false&SkinURL=skin/defaultSE.zip&Decoders=getYoukuVideo.swf&JSenable=true",
obj:document.getElementById("ofPlayerHours"),width:1,height:1});c.$(function(){c.jsOfPlayerFn("mute");c.jsOfPlayerFn("reload","type:"+a+";url:"+b)});c.insterIntervalFn(function(b){var a=this.jsOfPlayerFn("getinfo","playback");0<a.positionRemainS&&($("#coursewareHours").val(Math.round(100*((a.positionS+a.positionRemainS)/60))/100),this.removeOfPlayer(),b.disabled=!1,window.L.openCom("tip")())},[this],-1)}else if("img"===a){var g=0,b=window.L.JSON.parse(b),h;for(h in b)b[h].disabled&&++g;$("#coursewareHours").val(g)}else"none"===
a?$("#coursewareHours").val(0):window.L.openCom("tip")(window.L.getText("\u60a8\u6240\u9009\u62e9\u7684\u8bfe\u4ef6\u7c7b\u578b\u65e0\u6cd5\u8ba1\u7b97\u5b66\u65f6"))});$("input[name=lectureDiv]").click(function(){var b=$(this).parentsUntil(".tab_title").eq(-1);b.siblings("a").removeClass("current");b.addClass("current");$("#lectureTwoDiv").hide();$("#lectureOneDiv").hide();$("#"+this.value).show();L.extension.pageTable.classObj.initCustomNav(document.getElementById("lectureImgAttPageTable"))});window.L.openCom("oEditor")&&
(new oEditor({buttonList:"bold italic underline left center right justify ol ul fontSize fontFamily fontFormat indent outdent image upload link unlink forecolor bgcolor table subscript superscript strikethrough removeformat hr xhtml".split(" "),CustomConfig:{oFileManager:{quickUploadDir:{img:"/pictures/..quickUpload",media:"/media/..quickUpload",attachment:"/attachment/..quickUpload"},browseDir:{img:"/pictures",media:"/media",attachment:"/attachment"}}}})).panelInstance("lectureText");var c={onSelectOnce:function(){var b=
document.getElementById("lectureText");$("input[name=lectureDiv]").prop("disabled",!0);window.L.openCom("tip")(window.L.getText("\u6b63\u5728\u4e0a\u4f20\u8bf7\u7a0d\u540e"),!1);b.tempUrlList="img"===$(b).attr("coursewareType")?window.L.JSON.parse($(b).val()):[]}};c.onComplete=c.onCancel=function(b){"string"===typeof b&&document.getElementById("lectureText").tempUrlList.push(b.substr((window.browseHome+window.coursewareAttFolder).length));0==$("#lectureImgAttUpload").attr("fileCount")&&(b=window.L.JSON.stringify(document.getElementById("lectureText").tempUrlList),
$("#lectureText").attr("coursewareType","img").val(b),$("input[name=lectureDiv]:checked").parent().parent().siblings().css("fontWeight","normal").end().css("fontWeight","bold"),updateImgPageTable(document.getElementById("lectureImgAttPageTable")),$("input[name=lectureDiv]").prop("disabled",!1),window.L.openCom("tip")())};window.L.openCom("upload")("lectureImgAttUpload",c,"jpg;gif;png",'<font color="#1A5F9B" size="13" >'+window.L.getText("\u4e0a\u4f20\u56fe\u7247")+"</font>",60,15,{auto:!0,queueID:"lectureUploadProgress",
multi:!0,folder:window.coursewareAttFolder});$("#lectureText_Editer").focus(function(){window.temp=this.innerHTML}).blur(function(){this.innerHTML!==window.temp&&($("#lectureText").attr("coursewareType","text"),$("input[name=lectureDiv]:checked").parent().parent().siblings().css("fontWeight","normal").end().css("fontWeight","bold"),updateImgPageTable(document.getElementById("lectureImgAttPageTable")))});"img"===$("#lectureText").attr("coursewareType")?$("input[name=lectureDiv][value=lectureTwoDiv]").click():
$("input[name=lectureDiv][value=lectureOneDiv]").click();$("input[name=lectureDiv]:checked").parent().parent().siblings().css("fontWeight","normal").end().css("fontWeight","bold");$("#save").click(function(){var b={w_id:$("#w_id").val(),w_name:$("#w_name").val(),w_point:$("#w_point").val(),w_credit:$("#w_credit").val(),w_length:$("#coursewareHours").val(),w_type:$("#remoteUrl").attr("coursewareType"),w_video:$("#remoteUrl").val(),w_source:$("#w_source").attr("w_source_id"),w_category:$("#w_category").attr("w_category_id"),
lectureType:$("#lectureText").attr("coursewareType"),tabList:qsnAddTag.tagList};if(""===$.trim(b.w_name))return window.L.openCom("tip")(window.L.getText("\u8bfe\u4ef6\u540d\u79f0\u4e0d\u4e3a\u7a7a")),$("#w_name").focus(),!1;if(!/^\d+$/.test(b.w_credit))return window.L.openCom("tip")(window.L.getText("\u6240\u9700\u79ef\u5206\u5fc5\u987b\u662f\u6570\u5b57")),$("#w_credit").focus(),!1;if(!/^\d+$/.test(b.w_point))return window.L.openCom("tip")(window.L.getText("\u8bfe\u4ef6\u5b66\u5206\u5fc5\u987b\u662f\u6570\u5b57")),
$("#w_point").focus(),!1;if(!/^\d+(?:\.\d+)?$/.test(b.w_length)||"none"!==$("#remoteUrl").attr("coursewareType")&&0>=b.w_length)return window.L.openCom("tip")(window.L.getText("\u8bfe\u4ef6\u5b66\u65f6\u5fc5\u987b\u662f\u5927\u4e8e0\u6570\u5b57,\u5426\u5219\u65e0\u6cd5\u6b63\u786e\u7edf\u8ba1\u5b66\u4e60\u8fdb\u5ea6")),$("#coursewareHours").focus(),!1;if(""===$.trim(b.w_source))return window.L.openCom("tip")(window.L.getText("\u8bfe\u4ef6\u6765\u6e90\u4e0d\u4e3a\u7a7a")),$("#w_source").focus(),!1;
if(""===$.trim(b.w_category))return window.L.openCom("tip")(window.L.getText("\u8bfe\u4ef6\u5206\u7c7b\u4e0d\u4e3a\u7a7a")),$("#w_category").focus(),!1;"img"===b.lectureType?(b.w_des="",b.w_des_h=b.w_des=$("#lectureText").val()):(b.w_des=$("#lectureText").val(),b.w_des_h=$("#lectureText_Editer").html());window.L.openCom("tip")(window.L.getText("\u6b63\u5728\u4fdd\u5b58,\u8bf7\u7a0d\u540e..."),!1,!1,!0);$.post("?a=saveCourseware",b,function(a){if(a==="1"){window.L.openCom("tip")(window.L.getText(b.w_id!==
"0"?"\u64cd\u4f5c\u6210\u529f,\u5373\u5c06\u8df3\u8f6c\u5230\u5217\u8868\u9875":"\u64cd\u4f5c\u6210\u529f,\u5373\u5c06\u5237\u65b0\u9875\u9762"),null,false,true);coursewareObj.beforeUnloadTip.tipState=false;window.setTimeout(function(){window.location.href=b.w_id!=="0"?"?a=modfiyCourseware":window.location.href},1500)}else if(a==="0"){window.L.openCom("tip")(window.L.getText("\u670d\u52a1\u7aef\u5224\u5b9a,\u60a8\u672a\u505a\u4efb\u4f55\u4fee\u6539"));coursewareObj.beforeUnloadTip.tipState=false}else{window.L.openCom("tip")();
window.L.openCom("oDialogDiv")(window.L.getText("\u64cd\u4f5c\u5931\u8d25:"),"text:"+a,"auto","auto",[1])}});return!1});$("#addTag").click(function(){tagDisplayTag({tagType:"6",callbackFn:"qsnAddTag",targetId:"qsn_add_tag_a"});return!1});$("#w_source").click(function(){getTree({targetId:"w_source",callbackFn:function(b,a){$("#w_source").val(a).attr("w_source_id",b)},dataType:"courseware_source",isCheckBox:!1,isExpand:!1,expandLevel:2,showRoot:!1})});$("#w_category").click(function(){getTree({targetId:"w_category",
callbackFn:function(b,a){$("#w_category").val(a).attr("w_category_id",b)},dataType:"courseware_category",isCheckBox:!1,isExpand:!1,expandLevel:2,showRoot:!1})});$(document).keyup(function(){coursewareObj.beforeUnloadTip.tipState=!0});$(window).bind("beforeunload",coursewareObj.beforeUnloadTip)});
