function mouseDrag(d,e){this.mouseDragStatus=!1;this.rFn=[];this.objList=[];this.objListIndex=0;this.objListO={};this.$=function(a,b){"object"!=typeof a&&(a=(b||window).document.getElementById(a));return a};this.addEvent=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c)};this.removeEvent=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c)};this.mouseDown=function(a){this.setObjList(arguments[arguments.length-1]);this.disableSelection(a);
this.getScroll();this.objListO.nX=this.objListO.oX=a.clientX+this.objListO.scroll.left;this.objListO.nY=this.objListO.oY=a.clientY+this.objListO.scroll.top;this.mouseDragStatus=!0;this.rFn[0]&&(this.objListO.mouseDownFn=this.rFn[0]);this.rFn=[];this.removeEvent(this.objListO.thisWindow.document,"mousemove",this.objListO.mouseMoveFn);this.removeEvent(this.objListO.thisWindow.document,"mouseup",this.objListO.mouseUpFn);this.addEvent(this.objListO.thisWindow.document,"mousemove",this.mouseMove.mouseDragClosure(this));
this.addEvent(this.objListO.thisWindow.document,"mouseup",this.mouseUp.mouseDragClosure(this));this.objListO.mouseMoveFn=this.rFn[0];this.objListO.mouseUpFn=this.rFn[1];this.rFn=[];this.objListO.fn.mouseDownFn(this.objListO)};this.mouseMove=function(a){!0==this.mouseDragStatus&&(this.getScroll(),this.disableSelection(a),this.objListO.uX=this.objListO.nX,this.objListO.uY=this.objListO.nY,this.objListO.nX=a.clientX+this.objListO.scroll.left,this.objListO.nY=a.clientY+this.objListO.scroll.top,0<this.objListO.uX&&
0<this.objListO.uY&&(this.objListO.aW=this.objListO.nX-this.objListO.oX,this.objListO.aH=this.objListO.nY-this.objListO.oY,this.objListO.nW=this.objListO.nX-this.objListO.uX,this.objListO.nH=this.objListO.nY-this.objListO.uY,this.objListO.fn.mouseMoveFn(this.objListO)))};this.mouseUp=function(){this.getScroll();this.mouseDragStatus=!1;this.removeEvent(this.objListO.thisWindow.document,"mousemove",this.objListO.mouseMoveFn);this.removeEvent(this.objListO.thisWindow.document,"mouseup",this.objListO.mouseUpFn);
this.objListO.fn.mouseUpFn(this.objListO);this.objDefault(this.objListO)};this.getScroll=function(){this.objListO.scroll={top:this.objListO.thisWindow.document.documentElement.scrollTop||this.objListO.thisWindow.document.body.scrollTop,left:this.objListO.thisWindow.document.documentElement.scrollLeft||this.objListO.thisWindow.document.body.scrollLeft}};this.disableSelection=function(a){a.preventDefault?a.preventDefault():a.returnValue=!1};this.setObjList=function(a){for(var b in this.objList)if(this.objList[b].target==
a){this.objListO=this.objList[b];this.objListIndex=b;return}this.objListO=this.objList[this.objList.length]={target:a,thisWindow:window,oX:-1,oY:-1,uX:-1,uY:-1,nX:-1,nY:-1,aW:-1,aH:-1,nW:-1,nH:-1,mouseDownFn:null,mouseMoveFn:null,mouseUpFn:null};this.objListIndex=this.objList.length-1};this.ObjAllExtend=function(a,b){for(var c in b)"object"==typeof a[c]&&null!=a[c]?this.ObjAllExtend(a[c],b[c]):a[c]=b[c]};this.objDefault=function(a){for(var b in a)switch(typeof a[b]){case "number":a[b]=-1}};this.toArray=
function(a){for(var b=a.length,c=Array(b);b--;)c[b]=a[b];return c};this.onlyFalse=function(){return!1};this.removeDrag=function(){if(d=this.$(d,thisWindow))this.setObjList(d),this.removeEvent(d,"mousedown",this.objListO.mouseDownFn||this.rFn[0]),this.removeEvent(this.objListO.thisWindow.document,"mousemove",this.objListO.mouseMoveFn),this.removeEvent(this.objListO.thisWindow.document,"mouseup",this.objListO.mouseUpFn),this.objList.splice(this.objListIndex,1),this.rFn=[]};this.getObjListO=function(a,
b){if(a=this.$(a,b))return this.setObjList(a),[this.objListO,this.objListIndex]};this.init=function(a,b,c){if(a=this.$(a,c))this.setObjList(a),this.objListO.fn=b,this.objListO.thisWindow=c||window,b.mouseDownFn||(b.mouseDownFn=this.onlyFalse),b.mouseMoveFn||(b.mouseMoveFn=this.onlyFalse),b.mouseUpFn||(b.mouseUpFn=this.onlyFalse),this.objListIndex==this.objList.length-1&&this.addEvent(a,"mousedown",this.mouseDown.mouseDragClosure(this,a))};null==Function.prototype.mouseDragClosure&&(Function.prototype.mouseDragClosure=
function(){var a=this,b=arguments[0],c=b.toArray(arguments);return b.rFn[b.rFn.length]=function(){return a.apply(b,b.toArray(arguments).concat(c))}});this.init(d,e)};
