function oDialogDiv(a,b,c,q,g,p,n){var f,e={},s=function(){},t=function(){},h,i=""+(new Date).getTime(),m=new String,l=null,j=[],k=arguments.callee.getAncestorWindow(),m={skinStyle:"oDialogDiv"};null==a&&(a="");null==b&&(b="");n=null==n?!0:!1;null==g&&(g=[]);"object"===$.type(p)&&($.extend(m,p),p=m.topNum,n=m.effect);if($.isArray(g[0]))for(var d=0,r=g[0].length;d<r;++d)"object"===typeof g[0][d]||""==g[0][d]?(g[0][d].callBack&&(g[0][d].callBack="'"+g[0][d].callBack+"'"),j.push(g[0][d])):j.push({value:g[0][d]});
else null==g[0]||1==g[0]?j.push(""):(1<=g[0]&&j.push({value:"\u786e\u5b9a",callBack:"true"}),2==g[0]&&j.push({value:"\u53d6\u6d88",callBack:"false"}));"object"===typeof g[1]?(null!=g[1].mouseDownFun&&(s=g[1].mouseDownFun),null!=g[1].mouseClickFun&&(t=g[1].mouseClickFun),null!=g[1].layoutFun&&(h=g[1].layoutFun)):null!=g[1]&&(t=g[1]);if(window.event)l=window.event.srcElement;else try{var u=arguments.callee.caller;do if(f=u.arguments[0],"object"===typeof f&&"object"===typeof f.target&&null!=f.target.nodeType){l=
f.target;break}while(u=u.caller)}catch(y){}k.oDialogDiv.callBackList[i]=e={handle:i,oDialogDivObj:null,oDialogDivBgObj:null,customize:g[2],ancestorWindow:k};-1<(f=$.inArray("",j))?(j.splice(f,1),f=""):f=' notExist style="display:none;"';m='<div id="oDialogDivBg_'+i+'" class="'+m.skinStyle+'Bg" ></div><div id="oDialogDiv_'+i+'" effect="'+(n?"true":"false")+'" class="'+m.skinStyle+'"><div class="borderBgN" ie6Png ></div><div class="borderBgS" ie6Png ></div><div class="borderBgW" ie6Png ></div><div class="borderBgE" ie6Png ></div><div class="borderBgEN" ie6Png ></div><div class="borderBgES" ie6Png ></div><div class="borderBgWS" ie6Png ></div><div class="borderBgWN" ie6Png ></div><div class="title"><h4></h4><a callBack="true" onclick="return false;" href="/"'+
f+'></a><div style="clear:both;"></div><div class="maskLayer" ></div></div><div class="scroll"><span class="content"></span></div>';if(j.length){m+='<div class="operating">';d=0;for(r=j.length;d<r;++d)m+='<a callBack="'+(j[d].callBack||d)+'" onclick="return false;" href="/">'+j[d].value+"</a>";m+='</div><div style="height:1px; width:1px; overflow:hidden; margin-top:-1px;"></div>'}$(k.document.body).append(m+'<iframe frameborder="0" style="position:absolute; filter:alpha(opacity=0); display:none; z-index:-1; top:0px; left:0px;"></iframe></div>');
e.oDialogDivObj=$("#oDialogDiv_"+i,k.document);e.oDialogDivBgObj=$("#oDialogDivBg_"+i,k.document);e.oDialogDivObj.css({opacity:0,zIndex:k.oDialogDiv.zIndex.zIndex}).css($(l).offset()||{top:0,left:0});e.oDialogDivBgObj.css("zIndex",k.oDialogDiv.zIndex.zIndex);$("> .title a",e.oDialogDivObj).add("> .operating a",e.oDialogDivObj).each(function(){f=$(this);f.attr("notExist")===void 0?f.click(function(){var a=eval($(this).attr("callBack"));(typeof t==="function"?t(a,window,e):eval(t))!==false&&k.oDialogDiv.dialogClose(i)}).mousedown(function(){var a=
eval($(this).attr("callBack"));typeof s=="function"?s(a,window,e):eval(s)}).mouseover(function(){e.preVisit=eval($(this).attr("callBack"))}).mouseout(function(){e.preVisit=null}):f.click(function(){k.oDialogDiv.dialogClose(i)})});e.oDialogDivBgObj.click(function(){var a=e.oDialogDivObj.offset(),b=5,c=5,d=$(k.document).scrollTop(),f=$(k).height(),g=e.oDialogDivObj.prop("offsetTop"),h=e.oDialogDivObj.height();d+f<g+50?$(k.document).scrollTop(g+(f-h)/2):d>g+h-50&&$(k.document).scrollTop(g-(f-h)/2);d=
$(k.document).scrollLeft();f=$(k).width();g=e.oDialogDivObj.prop("offsetLeft");h=e.oDialogDivObj.width();d+f<g+50?$(k.document).scrollLeft(g+(f-h)/2):d>g+h-50&&$(k.document).scrollLeft(g-(f-h)/2);(function(){if(c<1)e.oDialogDivObj.css(a);else{b=-b;c=c-1;e.oDialogDivObj.animate({left:a.left+b,top:a.top-b},20,arguments.callee)}})()});r=b;$("> .title h4",e.oDialogDivObj)[a?"html":"hide"](a);contentType=b.substring(0,b.indexOf(":"));b=b.substring(b.indexOf(":")+1,b.length);if(""===b)$("> .scroll > .content",
e.oDialogDivObj).css({overflow:"hidden",height:1,width:194});else switch(contentType){case "url":d=b.split("?",3);if("post"===d[0].toLowerCase()&&(d[2]=b.substr(d[1].length+6),/^{.*}$/.test(d[2]))){try{var o=(new Function("return "+d[2]))()}catch(v){throw Error("\u65e0\u6548\u7684Json\u5bf9\u8c61:"+r);}"undefined"!==typeof o.get&&(d[1]+="?"+$.param(o.get));"undefined"!==typeof o.post?d[2]=$.param(o.post):delete d[2]}$.ajax({type:d[0],url:d[1],data:d[2],beforeSend:function(){$("> .title > a:eq(0)",
e.oDialogDivObj).show();$("> .operating",e.oDialogDivObj).css("visibility","hidden");$("> .scroll > .content",e.oDialogDivObj).html("loading...")},error:function(){$("> .scroll > .content",e.oDialogDivObj).html("error...");h&&h(false,window,e)},success:function(a){f=$("> .title > a:eq(0)",e.oDialogDivObj);f.attr("notExist")===""&&f.hide();$("> .operating",e.oDialogDivObj).css("visibility","visible");$("> .scroll > .content",e.oDialogDivObj).html(a);oDialogDiv.skinLayout(e.oDialogDivObj,c,q,p,n,h)}});
break;case "id":$("> .scroll > .content",e.oDialogDivObj).html($("#"+b+"").html());break;case "iframe":l="";if(-1<b.indexOf("?")&&(d=[b.substr(0,b.indexOf("?")),b.substr(b.indexOf("?")+1)],/^{.*}$/.test(d[1]))){try{o=(new Function("return "+d[1]))()}catch(w){throw Error("\u65e0\u6548\u7684Json\u5bf9\u8c61:"+r);}"undefined"!==typeof o.get&&(d[0]+="?"+$.param(o.get),b=d[0]);if("undefined"!==typeof o.post){o=$.param(o.post).split("&");b="about:blank";l='<FORM METHOD=POST STYLE="display:none;" ACTION="'+
d[0]+'" TARGET="oDialogDiv_iframe_'+i+'">';d=0;for(r=o.length;d<r;++d)j=o[d].split("="),l+='<INPUT TYPE="hidden" NAME="'+decodeURIComponent(j[0]).replace(/&/g,"&amp;").replace(/\"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;")+'" value="'+decodeURIComponent(j[1]).replace(/&/g,"&amp;").replace(/\"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;")+'">';l+="</FORM>"}}$("> .scroll > .content",e.oDialogDivObj).html("<div>loading...</div><iframe id='oDialogDiv_iframe_"+i+"' name='oDialogDiv_iframe_"+
i+"' src='"+b+"' scrolling='no' frameborder='0' marginheight='0' marginwidth='0' style='visibility:hidden;'></iframe>");$("> .title > a:eq(0)",e.oDialogDivObj).show();$("> .operating",e.oDialogDivObj).css("visibility","hidden");$("#oDialogDiv_iframe_"+i,e.oDialogDivObj).load(function(){$(this).unbind("load",arguments.callee);f=$("> .title > a:eq(0)",e.oDialogDivObj);f.attr("notExist")===""&&f.hide();$("> .operating",e.oDialogDivObj).css("visibility","visible");try{e.oDialogDivObj.find("> .scroll > .content").children("div").remove().end().children("iframe").css("visibility",
"visible");oDialogDiv.skinLayout(e.oDialogDivObj,c,q,p,n,h)}catch(a){}});""!==l?$(l).insertAfter("#oDialogDiv_iframe_"+i,e.oDialogDivObj).submit().remove():!$.browser.msie&&"about:blank"===b&&$("#oDialogDiv_iframe_"+i,e.oDialogDivObj).load();break;case "text":$("> .scroll > .content",e.oDialogDivObj).html(b);break;default:$("> .scroll > .content",e.oDialogDivObj).html(r)}oDialogDiv.skinLayout(e.oDialogDivObj,c,q,p,n,"url"!==contentType&&"iframe"!==contentType&&h);null!=oDialogDiv.mouseDragObj&&(d=
$("> .title",e.oDialogDivObj).get(0),f={mouseDownFn:oDialogDiv.mouseDownFn,mouseMoveFn:oDialogDiv.floatDivMove,mouseUpFn:oDialogDiv.mouseUpFn},oDialogDiv.mouseDragObj.init(d,f,k),oDialogDiv.mouseDragObj.getObjListO(d)[0].Customize={dateTime:i},$("div[ie6png]",e.oDialogDivObj).each(function(){this.style.cursor="move";oDialogDiv.mouseDragObj.init(this,f,k);oDialogDiv.mouseDragObj.getObjListO(this)[0].Customize={dateTime:i}}));return i}oDialogDiv.callBackList={};
oDialogDiv.getAncestorWindow=function(){if(!arguments.callee.ancestorWindow){for(var a=window;a.parent!==a&&null!=a.parent;)a=a.parent;arguments.callee.ancestorWindow=a}return arguments.callee.ancestorWindow};"function"!==typeof oDialogDiv.getAncestorWindow().oDialogDiv?oDialogDiv.getAncestorWindow().oDialogDiv=window.oDialogDiv:window.oDialogDiv=oDialogDiv.getAncestorWindow().oDialogDiv;
"function"!==typeof oDialogDiv.getTreeNode&&(oDialogDiv.getTreeNode=function(a){var b=oDialogDiv.getAncestorWindow().oDialogDiv.callBackList,c=[],q;for(q in b)c[c.length]=b[q];if(0!==c.length)return null==a?c:0>a&&(a=c.length+a,0>a)?void 0:c[a]},oDialogDiv.zIndex=function(a){if(/^\d+$/.test(a)&&arguments.callee.zIndex!=a){var b=oDialogDiv.getAncestorWindow().oDialogDiv.callBackList,c;for(c in b)b[c].oDialogDivObj.css("zIndex",a),b[c].oDialogDivBgObj.css("zIndex",a);arguments.callee.zIndex=a}},oDialogDiv.zIndex.zIndex=
2147483584,oDialogDiv.skinLayout=function(a,b,c,q,g,p){var n=oDialogDiv.getAncestorWindow(),f=$(n),e=n.oDialogDiv,s,t,h,i,m,l,j,k,d,r,u,y=!0;if("object"!==typeof a||null==a)if(a="string"===typeof a?e.callBackList[a]:e.getTreeNode("number"===typeof a?a:-1),null!=a)a=a.oDialogDivObj;else return!1;else a=$(a);l=a.children(".scroll");m=l.outerHeight(!0)-l.height()+(a.children(".operating").outerHeight(!0)||0)+a.children(".title").outerHeight(!0);null==c?c="auto":"object"===typeof c?(k=parseInt(c.minHeight||
0),d=parseInt(c.maxHeight||0),/\d+%/.test(c.minHeight)&&(k=f.height()*k/100),/\d+%/.test(c.maxHeight)&&(d=f.height()*d/100),c="auto"):"auto"!==c&&(c=/\d+%/.test(c)?f.height()*parseInt(c)/100:parseInt(c),c-=m);null==b?b="auto":"object"===typeof b?(r=parseInt(b.minWidth||0),u=parseInt(b.maxWidth||0),/\d+%/.test(b.minWidth)&&(r=f.width()*r/100),/\d+%/.test(b.maxWidth)&&(u=f.width()*u/100),b="auto"):"auto"!==b&&(b=/\d+%/.test(b)?f.width()*parseInt(b)/100:parseInt(b));var q=null==q?!1:parseInt(q),g=null==
g?!0:g,o=function(){var o=$.browser.msie&&$.browser.version==6?a.children("iframe").hide():false,v=l.children(".content"),x=v.height();if(b==="auto"){var w=a.find("> .operating > a").outerWidth(true)*a.find("> .operating > a").length,z=a.find(".title > h4").outerWidth(true)+(a.find(".title > a[callback=true]:visible").outerWidth(true)||0);h=v.outerWidth(true);c!=="auto"&&c<x&&(h=h+oDialogDiv.getScrollBarWidth());h=h>w?h:w;h=h>z?h:z;r&&r>h&&(h=r);if(u&&u<h){h=u;c==="auto"&&(x=x+oDialogDiv.getScrollBarWidth())}}if(c===
"auto"){i=x;if(k&&k>i+m){i=k-m;j.length&&j.height(i)}if(d&&d<i+m){i=d>m?d-m:0;b==="auto"&&(h=h+oDialogDiv.getScrollBarWidth())}}q=q||f.height()-(c==="auto"?i:c)-m>>1;q<0&&(q=0);s={opacity:1,width:h,top:q+$(n.document).scrollTop(),left:$(n.document).scrollLeft()+(f.width()-parseInt(h))/2};t={width:h,height:i};x=function(){l.css({overflow:"auto"});if(o){o.css({width:h,height:a.height(),display:""});a.children(".borderBgS[ie6png]").hide().show()}c==="auto"&&($.browser.msie&&$.browser.version<8&&b!==
"auto"&&v.outerWidth(true)>l.prop("clientWidth"))&&l.prop("style").setExpression("height",oDialogDiv.getScrollBarWidth()+" + $('#"+a.prop("id")+"').find('.content:eq(0)').outerHeight(true)");if(typeof p==="function"){var d,f;for(f in e.callBackList)a.get(0)===e.callBackList[f].oDialogDivObj.get(0)&&(d=e.callBackList[f]);p(y,window,d)}};a.children(".title").css("width","auto");if(g){a.stop(true,false).animate(s,"fast").css({overflow:"visible"});l.stop(true,false).animate(t,"fast",x)}else{a.css(s);
l.css(t);x()}};h=b;i=c;j=a.find("iframe[id^=oDialogDiv_iframe_]");if(j.length&&!1!==p)try{var v=$(j.get(0).contentWindow);l.width(l.width()).height(l.height());var w=function(){var a=$(this.document);if(a.width()>=v.width())if(arguments.callee.scrollWidth&&(c==="auto"||a.height()<=c)){j.width(arguments.callee.scrollWidth+oDialogDiv.getScrollBarWidth());delete arguments.callee.scrollWidth;$.browser.msie&&$.browser.version<7&&v.resize()}else n.setTimeout(function(){v.unbind("resize",w);a.width()>j.width()&&
j.width(a.width());c!=="auto"&&c>a.height()?j.height(c):j.height(a.height());o()},0)};w.scrollWidth=("auto"===b?299:b-11)-oDialogDiv.getScrollBarWidth();j.css({height:"auto",width:w.scrollWidth});v.resize(w);$.browser.msie&&v.resize()}catch(A){y=!1,o()}else o()},oDialogDiv.dialogClose=function(a){var b=oDialogDiv.getAncestorWindow(),c=b.oDialogDiv.callBackList[a];c&&($('<input style="position:absolute; top:0px; border:0px; width:1px; height:0px; overflow:hidden; z-index:-1;" />').appendTo(c.oDialogDivObj).focus().remove(),
c.oDialogDivBgObj.remove(),c.oDialogDivObj.animate({opacity:"0"},100,function(){$(this).remove();delete b.oDialogDiv.callBackList[a]}))},oDialogDiv.getScrollBarWidth=function(){if(!arguments.callee.scrollBarWidth){var a=$('<div style="height:50px; width:100px; overflow-y:scroll; z-index:-1; visibility:hidden; top:-100px; position:absolute;"></div>').appendTo(oDialogDiv.getAncestorWindow().document.body);arguments.callee.scrollBarWidth=100-a.prop("clientWidth");a.remove()}return arguments.callee.scrollBarWidth},
oDialogDiv.tip=function(a,b,c,q){var g=oDialogDiv.getAncestorWindow(),p=g.oDialogDiv,p=!1===c?null:p.getTreeNode(null==c?-1:c),n=arguments.callee,f=n.tipObj,e=n.bgObj;if("undefined"===typeof a)f.animate({opacity:0,height:0},"fast",function(){f.remove();e.remove();n.lock=!1});else if(!n.lock){a=!0===a?f.html():a;f.stop(!0,!0);var s=f.css({opacity:0,height:0,top:-50}).html(a).appendTo(g.document.body).outerWidth(),t;null==p||(t=p.oDialogDivObj.children(".scroll").width())<s+100||100>p.oDialogDivObj.children(".scroll").height()?
$.browser.msie&&"6.0"==$.browser.version?(f.get(0).style.setExpression("left","eval(document.documentElement.scrollLeft+document.documentElement.clientWidth-this.offsetWidth) / 2"),f.get(0).style.setExpression("top","eval(document.documentElement.scrollTop)")):f.css({position:"fixed",top:0,left:$(g).width()-s>>1}):p.oDialogDivObj.append(f.css({position:"absolute",top:p.oDialogDivObj.find("> .title").outerHeight(),left:t-s>>1}));q?e.appendTo(g.document.body):e.remove();f.height(0).animate({opacity:1,
height:14},"fast",function(){clearTimeout(n.timeoutObj);if(b!==false)n.timeoutObj=setTimeout(function(){n()},b==null?3E3:b)})}},oDialogDiv.tip.tipObj=$('<div class="tip"></div>'),oDialogDiv.tip.bgObj=$('<div class="oDialogDivBg" style="z-index:2147483584;" ></div>'));
null==oDialogDiv.mouseDragObj&&"function"===typeof window.mouseDrag&&(oDialogDiv.mouseDragObj=new mouseDrag,oDialogDiv.floatDivMove=function(a){var b=oDialogDiv.getAncestorWindow(),c=oDialogDiv.mouseDragObj.$("oDialogDiv_"+a.Customize.dateTime,b);c.style.top=c.offsetTop+a.nH+"px";c.style.left=c.offsetLeft+a.nW+"px";a=$(c).offset();a.scrollTop=$(b.document).scrollTop();a.scrollLeft=$(b.document).scrollLeft();a.scrollWidth=$(b).width();a.outerWidth=$(c).outerWidth();if(a.scrollTop>a.top)c.style.top=
a.scrollTop+"px";if(a.scrollLeft>a.left)c.style.left=a.scrollLeft+"px"},oDialogDiv.mouseDownFn=function(a){var b=oDialogDiv.getAncestorWindow().document,a=$("#oDialogDiv_"+a.Customize.dateTime,b);a.find("> .title > .maskLayer").height(a.find("> .scroll").outerHeight(true))},oDialogDiv.mouseUpFn=function(a){var b=oDialogDiv.getAncestorWindow().document;$("#oDialogDiv_"+a.Customize.dateTime,b).find("> .title > .maskLayer").height(0)});
