var windowObj=window,dirArr={"folderName..":"/"},selectFileCallBackFun=function(){window.close()},parentIframeWidth=null;
$(function(){var a;$(window).resize(function(){$("td.menu").parent().children().height($(window).height()-50);a=$("#fileList").hide();a.parent().height("39%").height(a.parent().height()-5);a.show();if("function"===typeof JS_OFplayer&&$("#objectID").length)try{setTimeout(function(){JS_OFplayer("objectID","event","normalScreen")},400)}catch(b){}});$(window).trigger("resize");if(-1!=navigator.userAgent.indexOf("Chrome")){var b=$("body table tbody").children("tr");b.eq(0).children("td").attr("colspan",
"999");b.eq(2).children("td").attr("colspan","999")}$("td.menuSwitch").click(function(){var b=$("#preview"),a=b.width();"none"==$("td.menu").css("display")&&b.width(a-160);$("td.menu").toggle("fast",function(){$(window).trigger("resize");$("td.menuSwitch").children("img").attr("src","none"==$("td.menu").css("display")?"images/menuSwitchOn.gif":"images/menuSwitchOff.gif")})});null!=window.dialogArguments?selectFileCallBackFun=window.dialogArguments:window.parent!=window&&(windowObj=window.parent);
for(var c=[window,windowObj];windowObj.parent!=windowObj;)windowObj=windowObj.parent,c[c.length]=windowObj;for(b=c.length-1;-1<b;b--)$(c[b]).ready(function(){for(var b=c.length-1;b>-1;b--)if(c[b]!=null&&typeof c[b].oDialogDiv=="function"){windowObj.oDialogDiv=c[b].oDialogDiv;c[b]=null;break}else if(c[b]==null)break});permissionsInit();requestDir({obj:$(".menu div span ul ol:eq(0)")})});
function permissionsInit(){loading("\u6b63\u5728\u521d\u59cb\u5316,\u8bf7\u7a0d\u540e...");var a=$("#operation th");a.eq(4).html("\u9009\u62e9\u6587\u4ef6").click(function(){var b=$("#operation td").eq(0).children("input").attr("dirUrl");null!=b?selectExt.test(b)?selectFileCallBackFun(returnUrlPrefix+b,window):windowObj.oDialogDiv("\u6e29\u99a8\u63d0\u793a",'\u60a8\u53ea\u80fd\u9009\u62e9\u6269\u5c55\u540d\u4e3a<font color="red">'+(""+selectExt).replace(/\\|\.|\+|\/i|\/|\$/g,"")+"</font>\u7684\u683c\u5f0f"):
loading("\u8bf7\u9009\u4e2d\u8981\u9009\u62e9\u7684\u6587\u4ef6",3E3)}).css("cursor","pointer");1<permissions?(a.eq(8).html('<input type="file" name="uploadify" id="uploadify" />'),$("#uploadify").uploadify({uploader:"include/uploadify/scripts/uploadify.swf",script:"include/uploadify/uploadify.php",cancelImg:"include/uploadify/cancel.png",folder:"upload",queueID:"fileQueue",auto:!0,multi:!0,fileExt:fileExt,fileDesc:"\u652f\u6301\u683c\u5f0f:"+fileExt,width:50,height:21,wmode:"transparent",buttonImg:"include/uploadify/Browse.jpg",
simUploadLimit:2,sizeLimit:sizeLimit,onSelectOnce:function(){var b=$(".title span:eq(0)").attr("dirUrl"),a=escape(phpUrlCode.rawurldecode(returnUrlPrefix+b));$("#uploadify").uploadifySettings("folder",a);$("#uploadify").uploadifySettings("nowFolder",b);"none"==$("#fileQueue").css("display")&&($("#fileQueue").css("display","block"),$("#operation").width($("#operation").width()+200))},onCancel:function(b,a,e,d){0==d.fileCount&&($("#fileQueue").css("display","none"),$("#operation").width($("#operation").width()-
200))},onAllComplete:function(b,a){loading('<font color="#009900">'+(a.filesUploaded-a.errors)+"/"+a.filesUploaded+"\u7684\u6587\u4ef6\u5df2\u4e0a\u4f20\u6210\u529f</font>",2E3);loading.lock=!0;$("#fileQueue").css("display","none");$("#operation").width($("#operation").width()-200);refreshFolder($("#uploadify").uploadifySettings("nowFolder"),!1,!0)}}),jQuery.browser.mozilla&&window.frameElement&&function(){var b;"visible"===window.frameElement.style.visibility&&(b=document.getElementById("uploadifyUploader"))&&
document.getElementById("uploadifyUploader").updateSettings?(b.style.display="inline-block",window.setTimeout(function(){b.style.display="inline"},500)):window.setTimeout(arguments.callee,100)}(),a.eq(9).html("\u65b0\u5efa").click(function(){nodeNameOperation("\u8bf7\u8f93\u5165\u6587\u4ef6\u5939\u540d",function(b,a,e){b&&requestDir({obj:refreshFolder($(".title span:eq(0)").attr("dirUrl"),!0,!0),type:"mkdir",parameters:e.oDialogDivObj.find("input").val()})})}).css("cursor","pointer")):a.eq(8).html('<font color="#CCCCCC" >\u65e0\u64cd\u4f5c\u9009\u9879</font>');
2<permissions&&(a.eq(5).html('<strong style="margin-left:3.1em">\u6587\u4ef6\u79fb\u52a8</strong><br />').click(function(b){var a=$("#operation td").eq(0).children("input").attr("dirUrl");if(a!=null){var e=$(this).children("br"),d=null,i=null,d=function(a,b){var c=indexDirArr(a.attr("dirUrl")),e=floatMenu.getMenuItemsHtml(c);if(!b&&e==""&&c["folderNum.."]>0){c=refreshFolder(a.attr("dirUrl"),true,true);c.get(0).callbackFun=function(){d(a,true)};c.trigger("click")}else floatMenu(a,e,d,i)},i=function(b,
d){windowObj.oDialogDiv('<font color="red">\u8bf7\u6ce8\u610f</fon>','<font color="red">\u60a8\u786e\u5b9a\u8981\u79fb\u52a8\u5f53\u524d\u6587\u4ef6\u5230\u8be5\u6587\u4ef6\u5939?!</font>',230,null,[2,function(d){var e=a.substr(0,a.lastIndexOf("/"));d&&requestDir({obj:refreshFolder(e,true,true),type:"mobile",parameters:a.substr(a.lastIndexOf("/")+1)+">|<"+b.attr("dirUrl")})}]);e.next("ul").remove();d.stopPropagation()};floatMenu(e,'<ol dirurl="/"><a href="javascript:void(0)">\u6839\u76ee\u5f55</a></ol>',
d,i);$(document).click(floatMenu.documentClose);b.stopPropagation()}else loading("\u8bf7\u9009\u62e9\u8981\u79fb\u52a8\u7684\u6587\u4ef6",3E3)}).css("cursor","pointer"),a.eq(6).html("\u91cd\u547d\u540d").click(function(){var a=$("#operation td").eq(0).children("input").attr("dirUrl");if(a!=null){var c=a.substr(0,a.lastIndexOf("/")),e=a.substr(a.lastIndexOf("/")+1);nodeNameOperation("\u8bf7\u8f93\u5165\u6587\u4ef6\u540d",function(a,b,g){a&&requestDir({obj:refreshFolder(c,true,true),type:"rename",parameters:e+
">|<"+g.oDialogDivObj.find("input").val()})},phpUrlCode.rawurldecode(phpUrlCode.rawurldecode(e)),true)}else loading("\u8bf7\u9009\u62e9\u8981\u91cd\u547d\u540d\u7684\u6587\u4ef6",3E3)}).css("cursor","pointer"),a.eq(7).html("\u5220\u9664").click(function(){var a=$("#operation td").eq(0).children("input").attr("dirUrl");if(a!=null){var c=a.substr(0,a.lastIndexOf("/")),e=a.substr(a.lastIndexOf("/")+1);windowObj.oDialogDiv('<font color="red">\u8bf7\u6ce8\u610f</fon>','<font color="red">\u60a8\u786e\u5b9a\u8981\u5220\u9664\u8be5\u6587\u4ef6?!</font>',
null,null,[2,function(a){a&&requestDir({obj:refreshFolder(c,true,true),type:"delete",parameters:e})}])}else loading("\u8bf7\u9009\u62e9\u8981\u5220\u9664\u7684\u6587\u4ef6",3E3)}).css("cursor","pointer"),a.eq(10).html("\u91cd\u547d\u540d").click(function(){var a=$(".title span:eq(0)").html();if(a!=""&&a!="/"){a=a.substr(a.lastIndexOf("/")+1);nodeNameOperation("\u8bf7\u8f93\u5165\u6587\u4ef6\u5939\u540d",function(a,b,d){a&&requestDir({obj:refreshFolder($(".title span:eq(0)").attr("dirUrl"),true,true),
type:"rename",parameters:d.oDialogDivObj.find("input").val()});loading()},a);loading('<font color="red">\u6587\u4ef6\u5939\u64cd\u4f5c\u8bf7\u614e\u91cd~</font>',3E3)}else loading('<font color="red">\u8bf7\u6307\u5b9a\u4fee\u6539\u7684\u6587\u4ef6\u5939<br/>\u6839\u76ee\u5f55\u4e0d\u80fd\u4fee\u6539</font>',3E3)}).css("cursor","pointer"),a.eq(11).html('<strong style="margin-left:1.5em">\u79fb\u52a8</strong><br />').click(function(a){var c=$(".title span:eq(0)").attr("dirUrl");if(c!=""&&c!="/"){var e=
refreshFolder(c,true,true),d=$(this).children("br"),i=null,g=null,i=function(a,b){var c=indexDirArr(a.attr("dirUrl")),d=floatMenu.getMenuItemsHtml(c,e.attr("dirUrl"));if(!b&&d==""&&c["folderNum.."]>0){var k=refreshFolder(a.attr("dirUrl"),true,true);k.get(0).callbackFun=function(){i(a,k.attr("dirUrl"))};refreshFolder(k,false,true)}else floatMenu(a,d,i,g)},g=function(a,b){windowObj.oDialogDiv('<font color="red">\u8bf7\u6ce8\u610f</fon>','<font color="red">\u60a8\u786e\u5b9a\u8981\u79fb\u52a8\u5f53\u524d\u6587\u4ef6\u5939?!</font>',
null,null,[2,function(b){b&&requestDir({obj:e,type:"mobileDir",parameters:a.attr("dirUrl")})}]);d.next("ul").remove();b.stopPropagation()};floatMenu(d,'<ol dirurl="/"><a href="javascript:void(0)">\u6839\u76ee\u5f55</a></ol>',i,g);$(document).click(floatMenu.documentClose);a.stopPropagation();loading('<font color="red">\u6587\u4ef6\u5939\u64cd\u4f5c\u8bf7\u614e\u91cd~</font>',3E3)}else loading('<font color="red">\u8bf7\u6307\u5b9a\u79fb\u52a8\u7684\u6587\u4ef6\u5939<br/>\u6839\u76ee\u5f55\u4e0d\u80fd\u79fb\u52a8</font>',
3E3)}).css("cursor","pointer"),a.eq(12).html("\u5220\u9664").click(function(){var a=$(".title span:eq(0)").html();if(a!=""&&a!="/"){windowObj.oDialogDiv('<font color="red">\u8bf7\u6ce8\u610f</fon>','<font color="red">\u60a8\u786e\u5b9a\u8981\u5220\u9664\u8be5\u6587\u4ef6\u5939?!</font>',null,null,[2,function(a){a&&requestDir({obj:refreshFolder($(".title span:eq(0)").attr("dirUrl"),true,true),type:"delete"});loading()}]);loading('<font color="red">\u6587\u4ef6\u5939\u64cd\u4f5c\u8bf7\u614e\u91cd~</font>',
3E3)}else loading('<font color="red">\u8bf7\u6307\u5b9a\u5220\u9664\u7684\u6587\u4ef6\u5939<br/>\u6839\u76ee\u5f55\u4e0d\u80fd\u5220\u9664</font>',3E3)}).css("cursor","pointer"));loading()}
function folderSlideToggle(){$(".menu div span ol").unbind("click").click(function(a){var b=$(this).attr("dirUrl"),c=indexDirArr(b);"function"==typeof $(this).get(0).callbackFun&&a.stopPropagation();$(this).next("ul").slideToggle("fast");"object"!==typeof c[".."]&&0==$(this).next("ul").length&&("0"!=$(this).attr("folderNum")||"0"!=$(this).attr("fileNum"))?requestDir({obj:$(this)}):fileListSwitch(b);$(".menu div span ol a").css("color","#000000");$(this).find("a").css("color","#06F")})}
function fileListSwitch(a){a=null!=a?a:$(this).prev("ol").attr("dirUrl");"/"===a&&(a="");var b="",c=indexDirArr(a),e;for(e in c[".."])b+='<span dirUrl="'+a+"/"+e+'" >'+phpUrlCode.rawurldecode(phpUrlCode.rawurldecode(e))+"</span>";""==b&&(b='<font color="#CCCCCC">\u6b64\u6587\u4ef6\u5939\u4e3a\u7a7a</font>');$(".title span:eq(0)").html(""==a?"/":phpUrlCode.rawurldecode(phpUrlCode.rawurldecode(a))).attr("dirUrl",a||"/").css("margin-left","0px");$(document.body).width()<$(".title").width()+50&&$(".title span:eq(0)").css("margin-left",
$(document.body).width()-$(".title").width()-50+"px");$("#fileList").html(b);$("#operation td").eq(0).children("input").removeAttr("dirUrl").val("").end().end().eq(1).html("").end().eq(2).html("").end().eq(3).html("");filePreview()}
function filePreview(){var a="",b="";$("#fileList span").mouseenter(function(){a=$(this).attr("dirUrl");b=phpUrlCode.rawurldecode(a);$(".footer div span").css("opacity",0).html(phpUrlCode.rawurldecode(b)).animate({opacity:"1"},"fast");$('<div id="fileDownload" ><img src="images/fileDown.gif" /><strong><a href="'+phpUrlCode.rawurlencode(rootDirUrl+b)+'" title="\u4e00\u4e9b\u5982swf,txt,jpg\u7b49\u683c\u5f0f\u8bf7\u53f3\u952e\u53e6\u5b58\u4e3a" target="_blank" >\u4e0b\u8f7d</a></strong></div>').css("opacity",
0.4).appendTo($(this)).mouseenter(function(){$(this).animate({opacity:0.8})}).mouseleave(function(){$(this).animate({opacity:0.4})}).click(function(a){$("#fileDownload").remove();a.stopPropagation()})}).mouseleave(function(){$(".footer div span").html("");$("#fileDownload").remove()}).click(function(){var c=indexDirArr(a.substr(0,a.lastIndexOf("/"))),e=a.substr(a.lastIndexOf("/")+1),d=e.substr(e.lastIndexOf(".")+1).toLocaleUpperCase();"JPG"==d||"GIF"==d||"BMP"==d||"PNG"==d?$("#preview").html('<img height="100%" src="fileExtension.php?fileUrl='+
returnUrlPrefix+a+'&thumbnail=1&redirect=1" />'):"SWF"==d?$("#preview").html(getPlayerHtml(rootDirUrl+a)):"FLV"==d||"MP3"==d?$("#preview").html(getPlayerHtml("include/player/ofplayer.swf","SkinURL=skin/defaultSE.zip&JSenable=true&file="+rootDirUrl+a)):"WMV"==d?$("#preview").html('<EMBED src="'+rootDirUrl+a+'" width="100%" height="100%" '+($.browser.msie?'windowlessVideo="1"':"")+' type=audio/mpeg controls="smallconsole" autostart="true">'):"TXT"==d?$("#preview").html('<iframe width="100%" height="100%" frameborder="0" src="'+
rootDirUrl+a+'"></iframe>'):$("#preview").html("\u65e0\u9884\u89c8");d=c[".."][e].filesize;d=1<d/1024?1<(d=Math.round(d/1024))/1024?1<(d=Math.round(d/1024))/1024?Math.round(d/1024)+"GB":d+"MB":d+"KB":d+"Byte";$("#operation td").eq(0).children("input").attr("dirUrl",a).val(b).end().end().eq(1).html(d).end().eq(2).html(c[".."][e].filectime).end().eq(3).html(c[".."][e].filemtime);$("#fileList span").css("background-color","transparent");$(this).css("background-color","#FFFFFF")}).dblclick(function(){$("#operation th:eq(4)").click()})}
function requestDir(a){var b=$(a.obj),c=b.attr("dirUrl");"/"===c&&(c="");var e="requestDir="+c;a.type&&(e+="&requestType="+a.type);a.parameters&&(e+="&requestParameters="+phpUrlCode.rawurlencode(a.parameters));loading("\u6b63\u5728\u52a0\u8f7d\u6587\u4ef6\u5939,\u8bf7\u7a0d\u540e...");$.ajax({url:"jsonDir.php",dataType:"json",type:"post",data:e,success:function(d){var e={},g=null,j=c.substr(0,c.lastIndexOf("/")),m=indexDirArr(j),f=indexDirArr(c),l="";f["folderNum.."]=d[2]["folderNum.."];f["fileNum.."]=
d[2]["fileNum.."];d[2]["folderName.."]=""!=d[2]["folderName.."]&&"."!=d[2]["folderName.."]?d[2]["folderName.."]:"/";d[2]["error.."]&&("\u6210\u529f:"==d[2]["error.."].substr(0,3)?(loading('<font color="#009900">'+d[2]["error.."].substr(3)+"</font>",500),loading.lock=!0):windowObj.oDialogDiv("\u6e29\u99a8\u63d0\u793a",d[2]["error.."]));if(d[2]["response.."]){var k=refreshFolder(d[2]["response.."],!0,!0);k.get(0).callbackFun=function(){};refreshFolder(k,!1,!0)}if(d[2]["security.."]&&("delete"===a.type&&
null==a.parameters||"mobileDir"===a.type))delete m[f["folderName.."]],b.next("ul").remove(),b.remove(),refreshFolder(j,!0,!0).trigger("click").trigger("click");else{m!=f&&f["folderName.."]!==d[2]["folderName.."]&&(delete m[f["folderName.."]],f["folderName.."]=d[2]["folderName.."],m[f["folderName.."]]=f,c=c.substr(0,c.lastIndexOf("/")+1)+f["folderName.."],b.attr("dirUrl",c),f["dirUrl.."]=c);b.attr("folderNum",f["folderNum.."]);b.attr("fileNum",f["fileNum.."]);b.children("a").attr("title",phpUrlCode.rawurldecode(phpUrlCode.rawurldecode(f["folderName.."]))+
"\n(\u6709"+f["folderNum.."]+"\u4e2a\u6587\u4ef6\u5939\u548c"+f["fileNum.."]+"\u4e2a\u6587\u4ef6)").html(phpUrlCode.rawurldecode(phpUrlCode.rawurldecode(f["folderName.."]))+"&nbsp;("+f["folderNum.."]+"-"+f["fileNum.."]+")").attr("class",0<f["folderNum.."]?"notEmptyDir":"");f[".."]=d[1];for(var h in d[0])f[h]=d[0][h],f[h]["dirUrl.."]=c+"/"+h,l+='<ol dirUrl="'+c+"/"+h+'" folderNum="'+d[0][h]["folderNum.."]+'" fileNum="'+d[0][h]["fileNum.."]+'" ><a '+(d[0][h]["folderNum.."]?'class="notEmptyDir"':"")+
' href="javascript:void(0)" title="'+phpUrlCode.rawurldecode(phpUrlCode.rawurldecode(h))+"\n(\u6709"+d[0][h]["folderNum.."]+"\u4e2a\u6587\u4ef6\u5939\u548c"+d[0][h]["fileNum.."]+'\u4e2a\u6587\u4ef6)" >'+phpUrlCode.rawurldecode(phpUrlCode.rawurldecode(h))+"&nbsp;("+d[0][h]["folderNum.."]+"-"+d[0][h]["fileNum.."]+")</a></ol>";""!==l&&(d="none",e=b.next("ul"),e.length&&("none"!=e.css("display")&&(d="block"),e.remove(),e.removeType=!0),g=$('<ul style="display:'+d+';" >'+l+"</ul>").insertAfter(b));folderSlideToggle();
"function"==typeof b.get(0).callbackFun?(b.get(0).callbackFun(),b.removeAttr("callbackFun")):(""!==l&&!e.removeType&&g.slideToggle("fast"),fileListSwitch(c))}loading()}})}function refreshFolder(a,b,c){"string"==typeof a&&(""==a&&(a="/"),c||(a=phpUrlCode.rawurlencode(phpUrlCode.rawurlencode(a))),a=$('.menu div span ol[dirUrl="'+a+'"]'));if(b)return a;requestDir({obj:a})}
function indexDirArr(a){var b=dirArr;null==a&&(a="");a=a.replace(/(^\/*)|(\/*$)/g,"");if(""!==a){var a=a.split("/"),c;for(c in a)b=b[a[c]];try{b["folderName.."]=a[c]}catch(e){}}return b}
function getPlayerHtml(a,b){return'<object id="objectID" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="100%" height="100%" >'+('<param name="movie" value="'+a+'" />')+'<param name="allowFullScreen" value="true" /><param name="allowScriptAccess" value="always" /><param name="quality" value="high" /><param name="wmode" value="opaque" />'+('<param name="flashvars" value="'+b+'" />')+'<embed type="application/x-shockwave-flash" name="objectID" width="100%" height="100%" '+('src="'+a+'" ')+
'allowfullscreen="true" allowscriptaccess="always" quality="high" wmode="opaque" '+('flashvars="'+b+'"')+"></embed></object>"}
var phpUrlCode={rawurlencode:function(a,b){a=escape(this._utf8_encode(a));b&&(a=this._encode_url(a));return a},rawurldecode:function(a){for(var a=a.split("/"),b=0,c=a.length;b<c;++b)/^[\w%-\.]+$/.test(a[b])&&(a[b]=this._utf8_decode(unescape(a[b])));return a.join("/")},_utf8_encode:function(a){for(var a=a.replace(/\r\n/g,"\n"),b="",c=0;c<a.length;c++){var e=a.charCodeAt(c);128>e?b+=String.fromCharCode(e):(127<e&&2048>e?b+=String.fromCharCode(e>>6|192):(b+=String.fromCharCode(e>>12|224),b+=String.fromCharCode(e>>
6&63|128)),b+=String.fromCharCode(e&63|128))}return b},_utf8_decode:function(a){for(var b="",c=0,e=c1=c2=0;c<a.length;)e=a.charCodeAt(c),128>e?(b+=String.fromCharCode(e),c++):191<e&&224>e?(c2=a.charCodeAt(c+1),b+=String.fromCharCode((e&31)<<6|c2&63),c+=2):(c2=a.charCodeAt(c+1),c3=a.charCodeAt(c+2),b+=String.fromCharCode((e&15)<<12|(c2&63)<<6|c3&63),c+=3);return b},_encode_url:function(a){return a=a.replace(/%5C/g,"\\").replace(/%2F/g,"/").replace(/%3A/g,":").replace(/%3F/g,"?")}};
function nodeNameOperation(a,b,c,e){var d="",a=windowObj.oDialogDiv(a,'<input value="'+(c?c:"")+'" style=" width:100px; margin-right:2px;" /><font color="red">\u4e0d\u80fd\u5305\u542b\\/:*?"<>|</font>',240,"auto",[2,{mouseDownFun:function(a,b,c){a&&(/^[^\\\/:*?"<>|]+$/.test(d=c.oDialogDivObj.find("input").val().replace(/^\.+|\.+$/g,""))?e&&(RegExp("("+fileExt.replace(/;/g,"|").replace(/\./g,"\\.").replace(/\*/g,".+")+")$").test(d)||windowObj.oDialogDiv("\u6587\u4ef6\u6269\u5c55\u540d\u975e\u6cd5",
"\u4ec5\u53ef\u4ee5\u662f:<br/>"+fileExt.replace(/\*/g,""),710,null,[1,function(){c.oDialogDivObj.find("input").focus()}])):windowObj.oDialogDiv("","\u5185\u5bb9\u4e3a\u7a7a\u6216\u5305\u542b\u975e\u6cd5\u5b57\u7b26",null,null,[1,function(){c.oDialogDivObj.find("input").focus()}]),c.oDialogDivObj.find("input").val(d))},mouseClickFun:b}]);windowObj.document.getElementById("oDialogDiv_"+a).getElementsByTagName("input")[0].focus()}
function floatMenu(a,b,c,e){if("object"==typeof a&&"string"==typeof b&&""!=b){var a=$(a),d=a.parentsUntil("th"),i=Math.floor((d.last().attr("offsetLeft")+d.width())/d.width()),g=d.length,j="";g>i&&(--g,--i);1<g&&("0px"==d.css("right")&&0==g%i?j=' style="margin-right:0px; right:-'+d.outerWidth()+'px;" ':"0px"!=d.css("right")&&0!=g%i&&(j=' style="margin-right:0px; right:-'+d.outerWidth()+'px;" '));$("<ul"+j+">"+b+"</ul>").insertAfter(a.siblings("ul").remove().end());a.next("ul").children("ol").mouseenter(function(){$(this).siblings("ul").remove();
typeof c=="function"&&c($(this))}).click(function(a){typeof e=="function"&&e($(this),a)})}}floatMenu.getMenuItemsHtml=function(a,b){var c="",e;for(e in a)if(".."!=e.substr(e.length-2)&&(!b||!(a[e]["dirUrl.."]===b||a[e]["dirUrl.."].substr(0,b.length+1)===b+"/")))c+='<ol dirUrl="'+a[e]["dirUrl.."]+'" ><a href="javascript:void(0)" >'+phpUrlCode.rawurldecode(phpUrlCode.rawurldecode(e))+"</a></ol>";return c};floatMenu.documentClose=function(){$("#operation ul").remove()};
function loading(a,b){loading.lock||(a=!0===a?$("#loading").html():a,$("#loading").stop(!0,!0),a?$("#loading").show("fast").html(a):$("#loading").hide("fast"),clearTimeout(loading.timeoutObj),b&&a&&(loading.timeoutObj=setTimeout(function(){loading.lock=!1;loading()},b)))};
