var setUserPermissionsObj={groupListJson:null,stratifiedListJson:null,stratifiedListTableTbodyObj:$("#groupListTable tbody"),stratifiedJsonName:"groupListJson",stratifiedTypeLanguage:[window.L.getText("\u6392\u9664"),window.L.getText("\u5305\u542b")],setStratifiedTableTr:function(){var a="",b;for(b in setUserPermissionsObj[setUserPermissionsObj.stratifiedJsonName])a+="<tr><td>"+window.L.strTranscoding.textToHtml(setUserPermissionsObj[setUserPermissionsObj.stratifiedJsonName][b].name)+'</td><td><a href="#" onclick="setUserPermissionsObj.tabStratifiedType(this, \''+
b+"'); return false;\">"+setUserPermissionsObj.stratifiedTypeLanguage[setUserPermissionsObj[setUserPermissionsObj.stratifiedJsonName][b].type]+'</a></td><td><input type="checkbox" class="checkbox" onclick="setUserPermissionsObj.tabStratifiedChild(this, \''+b+"')\" "+("1"==setUserPermissionsObj[setUserPermissionsObj.stratifiedJsonName][b].isChild?"checked":"")+' ></td><td><a href="#" onclick="setUserPermissionsObj.delStratified(this, \''+b+"'); return false;\">"+window.L.getText("\u5220\u9664")+"</a></td></tr>";
setUserPermissionsObj.stratifiedListTableTbodyObj.html(a)},tabStratifiedType:function(a,b){a.innerHTML=setUserPermissionsObj.stratifiedTypeLanguage[setUserPermissionsObj[setUserPermissionsObj.stratifiedJsonName][b].type=parseInt(setUserPermissionsObj[setUserPermissionsObj.stratifiedJsonName][b].type)?0:1]},tabStratifiedChild:function(a,b){setUserPermissionsObj[setUserPermissionsObj.stratifiedJsonName][b].isChild=parseInt(setUserPermissionsObj[setUserPermissionsObj.stratifiedJsonName][b].isChild)?
0:1},delStratified:function(a,b){delete setUserPermissionsObj[setUserPermissionsObj.stratifiedJsonName][b];setUserPermissionsObj.setStratifiedTableTr()},addStratifiedClickFun:function(a){var b=[],c;for(c in setUserPermissionsObj[setUserPermissionsObj.stratifiedJsonName])b[b.length]=c;getTree({targetId:a.id,treeMark:a.id,callbackFn:function(a){var b={},d,c;for(c in a)d=a[c].id,b[d]=setUserPermissionsObj[setUserPermissionsObj.stratifiedJsonName][d]?setUserPermissionsObj[setUserPermissionsObj.stratifiedJsonName][d]:
{id:d,name:a[c].name,type:1,isChild:0};setUserPermissionsObj[setUserPermissionsObj.stratifiedJsonName]=b;setUserPermissionsObj.setStratifiedTableTr()},dataType:"stratifiedListJson"===setUserPermissionsObj.stratifiedJsonName?"dataStratifiedPermissions":"group",isCheckBox:!0,isExpand:!1,showRoot:!1,expandLevel:2,checkedId:b,chkboxType:{Y:"",N:""}})},getUrlPermissionsStr:function(){var a=[];$("input[id^=urlPermissionsId_]").each(function(){this.checked&&(a[a.length]=this.id.substr(17))});return a.join()},
urlPermissionsSelectAll:function(a){$("input[id^=urlPermissionsId_]").each(function(){this.checked=a.checked})},urlPermissionsInvertSelect:function(){$("input[id^=urlPermissionsId_]").each(function(){this.checked=!this.checked})},userId:null,init:function(a,b,c){setUserPermissionsObj.userId=a;setUserPermissionsObj.stratifiedListJson=b;setUserPermissionsObj.groupListJson=c;setUserPermissionsObj.setStratifiedTableTr();setUserPermissionsObj.stratifiedJsonName="stratifiedListJson";setUserPermissionsObj.stratifiedListTableTbodyObj=
$("#stratifiedListTable tbody");setUserPermissionsObj.setStratifiedTableTr()},save:function(){window.L.openCom("tip")(window.L.getText("\u6b63\u5728\u63d0\u4ea4...",!1));var a="0";$.ajax({url:"?a=saveUserPermissions",type:"post",data:{userId:setUserPermissionsObj.userId,stratified:setUserPermissionsObj.stratifiedListJson,group:setUserPermissionsObj.groupListJson,urlPermissions:setUserPermissionsObj.getUrlPermissionsStr()},success:function(b){"1"===b?window.L.openCom("tip")(window.L.getText("\u6743\u9650\u8bbe\u7f6e\u6210\u529f"),
null,0):window.L.openCom("tip")(window.L.getText("\u64cd\u4f5c\u5931\u8d25,\u8bf7\u8054\u7cfb\u7ba1\u7406\u5458"));a=b},async:!1});return a},tabPermissions:function(a){$("div.tab_content").hide();$("#"+a.value).show();$("div.tab_title > a").removeClass("current");a.parentNode.parentNode.className="current";window.L.openCom("oDialogDiv").skinLayout(-1,"auto",{maxHeight:"80%"});"lectureOneDiv"===a.value?(setUserPermissionsObj.stratifiedJsonName="stratifiedListJson",setUserPermissionsObj.stratifiedListTableTbodyObj=
$("#stratifiedListTable tbody")):"lectureThrDiv"===a.value&&(setUserPermissionsObj.stratifiedJsonName="groupListJson",setUserPermissionsObj.stratifiedListTableTbodyObj=$("#groupListTable tbody"))}};
