function statisticsExamInit(){initResetArea({selection:"#statistics_exam_search_param_div",id:"statistics_exam_search_param_div"});window.L.openCom("wDate",{obj:$("#exam_begin_tm").get(0),params:{readOnly:!0}});window.L.openCom("wDate",{obj:$("#exam_end_tm").get(0),params:{readOnly:!0}})}function statisticsExamRankInit(){initResetArea({selection:"#statistics_rank_search_param_div",id:"statistics_rank_search_param_div"})}
function statisticsExamCategoryTreeShow(a,b,c){getTree({targetNameId:a,targetValueId:b,dataType:"exam_category",showRoot:c?c:!1})}
function statisticsExport(a){var b=1;switch(a){case "question":b=statisticsExamQuestionGetSearchCondition();break;case "rank":b=statisticsExamRankGetSearchCondition();break;case "group":b=statisticsExamGroupGetSearchCondition();break;case "user":b=statisticsExamUserGetSearchCondition()}b=encodeURIComponent(L.JSON.stringify(b));$("#export_params").val(b);$("#export_type").val(a);$("#statistics_export_form").submit()}
function statisticGroupTreeShow(a,b,c){getTree({targetNameId:a,targetValueId:b,dataType:"group",showRoot:c?c:!1})}function statisticsQsnCategoryTreeShow(a,b,c){getTree({targetNameId:a,targetValueId:b,dataType:"qsn_category",showRoot:c?c:!1})}function statisticsQsnSourceTreeShow(a,b,c){getTree({targetNameId:a,targetValueId:b,dataType:"qsn_source",showRoot:c?c:!1})}
function statisticsSearchExamStatistics(){var a=statisticsExamGetSearchCondition(),b=$('table[_pagetabledataset="admin_statistics_statisticsCtl::displayStatisticsExamList"]');window.L.extension.pageTable.classObj.params(b.get(0),a,!0)}function statisticsExamGetSearchCondition(){return{exam_name:$.trim($("#exam_name").val()),exam_category:"3"==$("#exam_category").val()?"":$("#exam_category").val(),exam_end_tm:$("#exam_end_tm").val(),exam_begin_tm:$("#exam_begin_tm").val()}}
function statisticsSearchExamUser(){var a=statisticsExamUserGetSearchCondition(),b=$('table[_pagetabledataset="admin_statistics_statisticsCtl::displayExamUserList"]');window.L.extension.pageTable.classObj.params(b.get(0),a,!0)}
function statisticsExamUserGetSearchCondition(){return{group_id:$.trim($("#group_id").val()),exam_id:$.trim($("#exam_id").val()),exam_times:$.trim($("#exam_times").val()),qsn_category:$("#qsn_category").val(),qsn_source:$.trim($("#qsn_source").val()),qsn_level:$.trim($("#qsn_level").val()),qsn_type:$.trim($("#qsn_type").val())}}
function statisticsSearchExamGroup(){var a=statisticsExamGroupGetSearchCondition(),b=$('table[_pagetabledataset="admin_statistics_statisticsCtl::displayExamGroupList"]');window.L.extension.pageTable.classObj.params(b.get(0),a,!0)}function statisticsExamGroupGetSearchCondition(){return{group_id:$.trim($("#group_id").val()),exam_id:$.trim($("#exam_id").val()),exam_times:$.trim($("#exam_times").val())}}
function statisticsSearchExamQuestion(){var a=statisticsExamQuestionGetSearchCondition(),b=$('table[_pagetabledataset="admin_statistics_statisticsCtl::displayExamQuestionList"]');window.L.extension.pageTable.classObj.params(b.get(0),a,!0)}
function statisticsExamQuestionGetSearchCondition(){return{qsn_category:$("#qsn_category").val(),qsn_source:$.trim($("#qsn_source").val()),qsn_level:$.trim($("#qsn_level").val()),qsn_type:$.trim($("#qsn_type").val()),exam_id:$.trim($("#exam_id").val()),exam_times:$.trim($("#exam_times").val())}}
function statisticsSearchExamRank(){var a=statisticsExamRankGetSearchCondition(),b=$('table[_pagetabledataset="admin_statistics_statisticsCtl::displayExamRankList"]');window.L.extension.pageTable.classObj.params(b.get(0),a,!0)}function statisticsExamRankGetSearchCondition(){return{group_id:$("#group_id").val(),username:$.trim($("#username").val()),real_name:$.trim($("#real_name").val()),exam_id:$.trim($("#exam_id").val()),exam_times:$.trim($("#exam_times").val())}}
function statisticsResetExamSearchParams(){resetArea("statistics_exam_search_param_div");statisticsExamInit()}function statisticsResetExamRankParams(){resetArea("statistics_rank_search_param_div");statisticsExamRankInit()}
function statisticsAlertSingleExamStatistics(a,b,c){a={exam_id:a,exam_times:b,statistics_type:c};a=L.JSON.stringify(a);window.L.openCom("oDialogDiv")&&(b=window.L._adminUrl+"/statistics/statisticsCtl.php?",ALERT_DIV_MARK=oDialogDiv(window.L.getText("\u8003\u8bd5\u7edf\u8ba1"),"iframe:"+b+"{'get':{'a':'alertSingleStatisticsExam'}, 'post' : {'_pageTableParams':'"+a+"'}}","1100px","600px",[1],10,!0))}
function statisticsChangeStatisticsExamDiv(a){$("[name='exam_info_item_div']").hide();$("#statistics_menu_ul > li").removeAttr("id");switch(a){case "rank":$("#exam_rand_div").show();$($("#statistics_menu_ul > li").get(0)).attr("id","statistics_menu_btn2");break;case "analysis":$("#exam_analysis_div").show();$($("#statistics_menu_ul > li").get(1)).attr("id","statistics_menu_btn2");break;case "other":$("#exam_other_div").show(),$($("#statistics_menu_ul > li").get(2)).attr("id","statistics_menu_btn2")}window.parent.oDialogDiv.skinLayout(window.parent.ALERT_DIV_MARK,
"1100px","600px")}
function statisticsGetQsnTypePosition(){var a=window.L._adminUrl+"/statistics/statisticsCtl.php?a=getPaprQsnTypePositions",b="paprid="+$("#papr_id").val();$.ajax({type:"POST",async:!1,url:a,data:b,dataType:"json",success:function(a){var b='<option value="">'+window.L.getText("\u8bf7\u9009\u62e9\u5927\u9898\u6807\u9898")+"</option>";$.each(a,function(a,c){b+='<option value="'+c.qsn_type_position+'">'+c.qsn_type_title+"</option>"});$("#qsn_type_position").empty();$("#qsn_type_position").append(b)},error:function(){}})}
function statisticsSearchExamQsnAnalysis(){var a=statisticsExamQsnAnalysisGetSearchCondition();if(""!=a.papr_id){var b=$('table[_pagetabledataset="admin_statistics_statisticsCtl::displayExamQsnAnalysisList"]');window.L.extension.pageTable.classObj.params(b.get(0),a,!0)}else oDialogDivInfo(window.L.getText("\u8bf7\u9009\u62e9\u4e00\u5f20\u8bd5\u5377"))}
window.L.strVar("L.extension.pageTable.callback.initLoadList[]",window.L.strVar("L.extension.pageTable.callback.afterLoadList[]",function(a){("admin_statistics_statisticsCtl::displayExamQsnAnalysisList"===$(a).attr("_pagetabledataset")||"admin_statistics_statisticsCtl::displayExamRankList"===$(a).attr("_pagetabledataset"))&&window.parent.oDialogDiv.skinLayout(window.parent.ALERT_DIV_MARK,"1100px","600px")}));
function statisticsExamQsnAnalysisGetSearchCondition(){return{exam_id:$("#exam_id").val(),exam_times:$("#exam_times").val(),papr_id:$("#papr_id").val(),qsn_type_position:$("#qsn_type_position").val(),qsn_level:$("#qsn_level").val()}}
function statisticsShowExamQsnAnalysisFlot(a){switch(a){case "selected":var b=[],c=[],d=[],e=[];e.push([0,""]);var g=!0;$(":checkbox[name='qsn_analysis_cb']:checked").each(function(a){e.push([a+1,$(this).val()]);b.push([a+0.75,$("#qsn_correct_count_hid_"+$(this).val()).val()]);c.push([a+0.95,$("#qsn_wrong_count_hid_"+$(this).val()).val()]);d.push([a+1.15,$("#qsn_half_correct_count_hid_"+$(this).val()).val()]);g=!0});g?($("#exam_qsn_analysis_flot_div").height(300),$.plot($("#exam_qsn_analysis_flot_div"),
[{label:window.L.getText("\u6b63\u786e\u6570"),data:b},{label:window.L.getText("\u9519\u8bef\u6570"),data:c},{label:window.L.getText("\u534a\u5bf9\u6570"),data:d}],{series:{bars:{show:!0,barWidth:0.1,fillColor:{colors:[{opacity:0.8},{opacity:0.1}]}}},colors:["#0F0","#F00","#FF0"],xaxis:{ticks:e}})):oDialogDivInfo(window.L.getText("\u8bf7\u81f3\u5c11\u9009\u4e2d\u4e00\u6761\u6570\u636e"))}window.parent.oDialogDiv.skinLayout(window.parent.ALERT_DIV_MARK,"1100px","600px")}
function statisticsShowScoreAreaFlot(){var a=parseFloat($("#exam_score_area").val()),b="success",c="";if(!validPositive(STATISTICS_EXAM_PASSING_GRADE)||!validPositive(STATISTICS_EXAM_POINT))b="failed",c=window.L.getText("\u6570\u636e\u6709\u8bef");if(!validPositive(a)||0==a)b="failed",c=window.L.getText("\u533a\u95f4\u6bb5\u8bf7\u8f93\u5165\u4e00\u4e2a\u6b63\u6570");if("success"==b){$("#exam_score_area_flot_div").height(300);var d={};for(f=a;f-a<STATISTICS_EXAM_POINT;f+=a)b=a,c=f,f>STATISTICS_EXAM_POINT&&
(b=STATISTICS_EXAM_POINT-(f-a),c=STATISTICS_EXAM_POINT),d[f]={bars:{show:!0,barWidth:b,fillColor:{colors:[{opacity:0.8},{opacity:0.1}]}},label:f-a+"-"+c,data:[[f-a+0.05,0]]};b=[{color:"#F00",lineWidth:1,xaxis:{from:STATISTICS_EXAM_PASSING_GRADE,to:STATISTICS_EXAM_PASSING_GRADE}}];$.each(STATISTICS_EXAM_POINT_LIST,function(b,c){for(f=a;f-a<STATISTICS_EXAM_POINT;f+=a)if(c.exam_point<=f){d[f].data[0][1]++;break}});dat_info=[];$.each(d,function(a,b){dat_info.push(b)});var e=$.plot($("#exam_score_area_flot_div"),
dat_info,{grid:{markings:b}});$.each(dat_info,function(a,b){var c=e.pointOffset({x:b.data[0][0],y:b.data[0][1]});$("#exam_score_area_flot_div").append('<div style="position:absolute;left:'+(c.left+4)+"px;top:"+(c.top-25)+'px;color:#666;font-size:smaller">'+b.data[0][1]+window.L.getText("\u4eba")+"</div>")})}else oDialogDivInfo(c);window.parent.oDialogDiv.skinLayout(window.parent.ALERT_DIV_MARK,"1100px","600px")};
