<?php

/**
 *    (C)2009-2013 Orivon Inc.
 *	  author@tiger
 */

$lang = array(
	'SC_GBK' => '简体中文版',
	'TC_BIG5' => '繁体中文版', 
	'SC_UTF8' => '简体中文 UTF8  编码 ',
	'TC_UTF8' => '繁体中文 UTF8  编码 ',
	'EN_ISO' => 'ENGLISH ISO8859',
	'EN_UTF8' => 'ENGLIST UTF-8',

    'title_welcome' => '欢迎使用',
	'title_install' => SOFT_NAME.' 安装向导',
	'title_update' => SOFT_NAME.' 升级向导',	
	'agreement_yes' => '我同意',
	'agreement_no' => '我不同意',
	'notset' => '不限制',
	'message_title' => '提示信息',
	'error_message' => '错误信息',
	'message_return' => '返回',
	'return' => '返回',
	'install_wizard' => '安装向导',
	'nodir' => '目录不存在',
	'short_open_tag_invalid' => '对不起，请将 php.ini 中的 short_open_tag 设置为 On，否则无法继续安装。',
	'redirect' => '浏览器会自动跳转页面，无需人工干预。<br>除非当您的浏览器没有自动跳转时，请点击这里',
	'auto_redirect' => '浏览器会自动跳转页面，无需人工干预',
	'dbpriv_createtable' => '没有CREATE TABLE权限，无法继续安装',
	'dbpriv_insert' => '没有INSERT权限，无法继续安装',
	'dbpriv_select' => '没有SELECT权限，无法继续安装',
	'dbpriv_update' => '没有UPDATE权限，无法继续安装',
	'dbpriv_delete' => '没有DELETE权限，无法继续安装',
	'dbpriv_droptable' => '没有DROP TABLE权限，无法安装',
	'db_not_null' => '数据库中已经安装过'.SOFT_NAME.', 继续安装会清空原有数据。',
	'db_drop_table_confirm' => '继续安装会清空全部原有数据，您确定要继续吗?',
	'writeable' => '可写',
	'unwriteable' => '不可写',
	'readWrite' => '读写',
	
	'database_errno_2003' => '无法连接数据库，请检查数据库是否启动，数据库服务器地址是否正确',
	'database_errno_1044' => '无法创建新的数据库，请检查数据库名称填写是否正确',
	'database_errno_1045' => '无法连接数据库，请检查数据库用户名或者密码是否正确',
	'database_errno_2013 ' => '无法连接数据库，请确认数据库服务器端口号是否正确',
	'database_connect_error' => '数据库连接错误',
	'install_run_error' => SOFT_NAME.'安装失败',

	'step_show_license_title' => '授权协议',
	'step_show_license_desc' => '中文版授权协议 适用于中文用户',
	'step_env_check_title' => '开始安装',
	'step_env_check_desc' => '环境以及文件目录权限检查',
	'step_db_init_title' => '安装数据库',
	'step_db_init_desc' => '正在执行数据库安装',

	'step1_file' => '目录文件',
	'step1_need_status' => '所需状态',
	'step1_status' => '当前状态',
	'not_continue' => '请将以上红叉部分修正再试',

	'tips_dbinfo' => '填写数据库信息',
	'tips_dbinfo_comment' => '',
	'tips_admininfo' => '填写管理员信息',
	'step_ext_info_title' => '安装成功。',
	'step_ext_info_comment' => '点击进入登入',

	'ext_info_succ' => '安装成功。',
	'install_submit' => '提交',
	'install_locked' => '安装锁定，已经安装过了，如果您确定要重新安装，请到服务器上删除<br /> ' . $config['_browseHome'] . '/install.lock',
	'demo_locked' => '安装锁定，已经安装过demo数据，如果您确定要重新安装，请到服务器上删除<br /> ' . $config['_browseHome'] . '/demolock.lock',
	'error_quit_msg' => '您必须解决以上问题，才可以继续',

	'step_app_reg_title' => '设置运行环境',
	'step_app_reg_desc' => '检测服务器环境以及设置'.SOFT_NAME,

	'advice_mysql_connect' => '请检查 mysql 模块是否正确加载',
	'advice_fsockopen' => '该函数需要 php.ini 中 allow_url_fopen 选项开启。请联系服务器管理员，确定开启了此项功能',
	'advice_gethostbyname' => '是否php配置中禁止了gethostbyname函数。请联系服务器管理员，确定开启了此项功能',
	'advice_file_get_contents' => '该函数需要 php.ini 中 allow_url_fopen 选项开启。请联系服务器管理员，确定开启了此项功能',
	'advice_xml_parser_create' => '该函数需要 PHP 支持 XML。请联系服务器管理员，确定开启了此项功能',
	'class_zip' => '不影响使用我们的产品(建议启用)',
	'class_PDO' => '请检查 php_pdo扩展是否正确加载',
	'class_pdo_mysql' => '请检查 php_pdo_mysql扩展是否正确加载',
	'class_gd' => '请检查 php_gd2扩展是否正确加载',
	'class_mbstring' => '请检查 php_mbstring扩展是否正确加载',

	'forceinstall' => '强制安装',
	'dbinfo_forceinstall_invalid' => '请注意：数据库已有数据，强制安装会删除原数据，无法恢复',

	'click_to_back' => '点击返回上一步',
	'adminemail_comment' => '用于发送程序错误报告',
	'dbhost_comment' => '数据库服务器地址, 一般为 127.0.0.1',
	'dbport_comment' => '数据库服务器端口号一般为 3306，注意端口号只能为1～65535之间的整数值',
	'forceinstall_check_label' => '我要删除数据，强制安装 !!!',

	'dbinfo_dbhost_invalid' => '数据库服务器为空，或者格式错误，请检查',
	'dbinfo_dbname_invalid' => '数据库名为空，或者格式错误，请检查',
	'dbinfo_dbnamenotexist_invalid' => '数据库中没有您填写的选择要升级的数据库，请检查数据库名称是否填写正确',
	'dbinfo_dbport_invalid' => '注意端口号只能是1～65535之间的整数',
	'dbinfo_dbuser_invalid' => '数据库用户名为空，或者格式错误，请检查',
	'dbinfo_dbpw_invalid' => '数据库密码为空，或者格式错误，请检查',
	'dbinfo_tablepre_invalid' => '数据表前缀为空，或者格式错误，请检查',
	'admininfo_username_invalid' => '管理员用户名为空，或者格式错误，请检查',
	'admininfo_password_invalid' => '管理员密码为空，请填写',
	'admininfo_password2_invalid' => '两次密码不一致，请检查',
	'username' => '管理员账号',
	'password' => '管理员密码',
	'password_comment' => '管理员密码不能为空',
	'password2' => '重复密码',
	'resetAdmin' => '修改或找回超级管理员帐号,密码时使用 <font color="red">安装,升级时可以不填写</font>',
	'dbname_invalid' => '数据库名为空，请填写数据库名称',	
	'tablepre_invalid' => '数据表前缀为空，或者格式错误，请检查',
	'admin_username_invalid' => '非法用户名，用户名长度不应当超过 15 个英文字符，且不能包含特殊字符，一般是中文，字母或者数字',
	'admin_password_invalid' => '密码和上面不一致，请重新输入',
	'admin_invalid' => '您的信息管理员信息没有填写完整，请仔细填写每个项目',
	'config_unwriteable' => '安装向导无法写入配置文件, 请设置 config.inc.php 程序属性为可写状态(777)',
	'install_in_processed' => '正在安装...',
	'install_finished' => '安装结束，点击进入首页',	
	'init_default_template_copyright' => '奥瑞文（大连）网络有限公司',
	'init_dataformat' => 'Y-n-j',
	'supportted' => '支持',
	'unsupportted' => '不支持',
	'max_size' => '支持/最大尺寸',
	'project' => '项目',
	'required' => '所需配置',
	'best' => '推荐配置',
	'curr_server' => '当前服务器',
	'env_check' => '环境检查',
    'fill_config' => '填写配置',
	'os' => '操作系统',
	'php' => 'PHP 版本',
	'attachmentupload' => '附件上传',
	'unlimit' => '不限制',
	'version' => '版本',
	'allow' => '允许',
	'unix' => '类Unix',
	'diskspace' => '磁盘空间',
	'priv_check' => '目录、文件权限检查',
	'func_depend' => '依赖性检查',
	'func_name' => '函数名称',
	'extension_depend' => 'PHP扩展检查',
	'extension_name' => 'PHP扩展',
	'check_result' => '检查结果',
	'suggestion' => '建议',
	'advice_mysql' => '请检查 mysql 模块是否正确加载',
	'advice_fopen' => '该函数需要 php.ini 中 allow_url_fopen 选项开启。确定开启了此项功能',
	'advice_file_get_contents' => '该函数需要 php.ini 中 allow_url_fopen 选项开启。确定开启了此项功能',
	'advice_xml' => '该函数需要 PHP 支持 XML。确定开启了此项功能',
	'none' => '无',
	'dbhost' => '数据库服务器',
	'dbport' => '数据库端口号',
	'dbuser' => '数据库用户名',
	'dbpw' => '数据库密码',
	'dbname' => '数据库名',
	'tablepre' => '数据表前缀',
	'init_log' => '初始化记录',
	'clear_dir' => '清空目录',
	'select_db' => '选择数据库',
	'create_table' => '建立数据表',
	'create_procedure' => '创建存储过程',
	'load_data' => '导入表数据',
	'load_demo_data' => '导入demo数据',
	'succeed' => '成功 ',
	'failed' => '失败 ',
	'install_attention' => "注意：为了安全，请更改install文件的名称或者将其删除！",
	'install_failed' => "安装失败！请解决以上问题后，尝试重新安装。",
    'products_installed' => '产品已安装',
	'products_installed_label' => '选中复选框"重新安装",否则"产品升级"',
	'demodata' => '演示数据',
	'demodata_check_label' => '安装演示数据',
	'install_test_data' => '正在安装演示数据',
	'addadmin'=>'添加管理员信息',
	'dropproc' => '删除存储过程',
	'method_undefined' => '未定义方法',
	'database_nonexistence' => '数据库操作对象不存在',
	'ioncube_check' => 'Ioncube 安装检查',
	'ioncube_require' => '最新版本',
	'ioncube_version' => '当前版本',
	'ioncube_path' => '文件位置',
	'ioncube_status' => '检查结果',
	'config_nonexistence' => '您的 config.inc.php 不存在, 无法继续安装, 请用 FTP 将该文件上传后再试。',
	'copy_attachment' => '复制demo数据附件到文件目录',
	'delete_attachment' => '删除demo数据附件',
	'delete_demo_data' => '删除demo数据',	
	
	'php_unsupport_ioncube' => '<p>您所安装的php版本不支持ioncube。 建议使用php5.x的版本是php5.1或者更高的版本。',
	'ioncube_' => '<p>您目前使用的php版本不支持ioncube_loader。 建议php4的版本在php4.2或者更高版本，php5的版本是php5.1或者更高的版本。',
	'ioncube_path_error2' => '请确定php.ini配置文件中，ioncube路径是否加载正确！请认真参照本地路径填写！',
	'ioncube_path_error3' => '请确定php.ini配置文件中，ioncube路径是否加载正确！请认真参照本地路径填写！',
	'loader_not_installed_error_title1' => "<p>请注意本次安装中依然存在下面这些问题",
	'loader_not_installed_error_title2' => "<p>请注意本次安装中存在下面这些问题",
	'error_ini_not_found1' => "没有找到php的配置文件",
	'error_ini_not_found2' => "这个 ",
	'error_ini_not_found2-1' => " 文件没有找到。",
	'error_ini_not_readable1' => "这个 ",
	'error_ini_not_readable1-1' => " 文件没有读取权限。",
	'get_loader_location_from_ini_error_ini_multiple_ic_loader_lines1' => "在配置文件 ",
	'get_loader_location_from_ini_error_ini_multiple_ic_loader_lines1-1' => " 中，发现有多个ionCube Loader扩展 ",
	'get_loader_location_from_ini_error_ini_multiple_ic_loader_lines1-2' => " ",
	'get_loader_location_from_ini_error_error_ini_not_first_ze1' => "在 ",
	'get_loader_location_from_ini_error_error_ini_not_first_ze1-1' => " 配置文件中，ionCube Loader 必须位于所有Zend extension 扩展的最前面",
	'get_loader_location_from_ini_error_error_ini_wrong_ze_start1' => "在 ",
	'get_loader_location_from_ini_error_error_ini_wrong_ze_start1-1' => " 文件中关于ionCube Loader的配置，应该使用 ",
	'get_loader_location_from_ini_error_error_ini_wrong_ze_start1-2' => " 开始，而<strong>不是</strong> ",
	'get_loader_location_from_ini_error_error_ini_wrong_ze_start1-3' => "  ",
	'get_loader_location_from_ini_error_error_ini_ze_line_not_found1' => " 在配置文件",
	'get_loader_location_from_ini_error_error_ini_ze_line_not_found1-1' => " 中，没有找到必须存在的 zend_extension行 ",
	'get_loader_location_from_ini_error_error_ini_loader_file_not_found1' => " 无法按照PHP配置文件 ",
	'get_loader_location_from_ini_error_error_ini_loader_file_not_found1-1' => " 中配置路径的找到Loader文件： ",
	'get_loader_location_from_ini_error_error_ini_loader_file_not_found1-2' => " 不存在或者不能执行",
	'get_loader_location_from_ini_error_error_ini_not_full_path1' => "在配置文件 ",
	'get_loader_location_from_ini_error_error_ini_not_full_path1-1' => " 中，必须为ionCube Loader文件指定一个完整的路径 ",
	'os_arch_string_check1' => "您当前的Loader版本相对于您的操作系统来说是不正确的，",
	'os_arch_string_check1-1' => " ",
	'os_arch_string_check2' => "您目前的Loader版本相对您的服务器硬件架构来说是不正确的，",
	'os_arch_string_check2-1' => "您目前的系统是 ",
	'os_arch_string_check2-2' => " 但是您使用的Loader是 ",
	'php_ini_install_shared1' => "在当前这个虚拟主机上，Loader配置应该写在 ",
	'php_ini_install_shared1-1' => " 配置文件中 ",
	'php_ini_install_shared2' => "使用您的虚拟主机帐号，或许您可以使用您自己的PHP配置文件 ",
	'php_ini_install_shared3' => "目前您不能将ionCube Loader配置写在 ",
	'php_ini_install_shared3-1' => "文件中。您需要联系您的服务器提供商或者系统管理员，请他们协助您做好配置。 ",
	'php_ini_install_shared_des1' => "对于",
	'php_ini_install_shared_des2' => "对于当前服务器",
	'php_ini_install_shared_des1-1' => "您目前使用",
	'php_ini_install_shared_des1-2' => "这个文件作为PHP的配置文件",
	'php_ini_install_shared_des3' => "当前安装ionCube Loader所使用的是",
	'php_ini_install_shared_des3-1' => "文件",
	'php_ini_install1' => "对于 ",
	'php_ini_install1-1' => " 服务器",
	'php_ini_install2' => "对于当前服务器",
	'php_ini_install3' => "您可以使用 ",
	'php_ini_install3-1' => " 这个配置文件来安装ionCube Loader",
	'php_ini_install4' => " 推荐使用",
	'php_ini_install4-1' => " 这个配置文件来安装ionCube Loader",
	'php_ini_install5' => " 如果您确定 ",
	'php_ini_install5-1' => " 不是 ",
	'php_ini_install5-2' => "服务器",
	'php_ini_install5-2' => "服务器",
	'os_arch_string_check1' => "相对您的服务器架构来说，您目前使用的Loader是错误的",
	'os_arch_string_check1-1' => " 您的服务器操作系统是 ",
	'os_arch_string_check1-2' => " 但是您使用的Loader是 ",
	'shared_server1' => " ionCube Loader  ",
	'shared_server1-1' => " 已经被成功的安装了 ",
	'info_disabled_text' => " ionCube Loader被成功安装后,这个函数已经被禁用了 ",
	'run1' => "这个函数只能运行在Web Server上",
	'php_ini_instruction_list_title' => "安装ionCube Loader的步骤：",
	'loader_download_instructions_download_windows1' => "请点击下面的链接下载系统安装所必需的",
	'loader_download_instructions_download_windows1-1' => "",
	'loader_download_instructions_download_windows2' => "点击",
	'loader_download_instructions_download_windows2-1' => "下载Windows版的Loader。如果PHP是非线程安全的（thread safety disabled,），请使用 Windows non-TS Loaders",
	'loader_download_instructions_download_unix1' => "下载 ",
	'loader_download_instructions_download_unix1-1' => " 从  ",
	'loader_download_instructions_download_unix1-2' => " 这里 ",
	'loader_download_instructions_download_unix2' => "您的系统看起来好像是 ",
	'loader_download_instructions_download_unix2-1' => " 如果Loader相对于 ",
	'loader_download_instructions_download_unix2-2' => " 系统无法使用，您可以尝试着使用一个低版本的Loader。",
	'loader_download_instructions_download_unix2-3' => " 注意,相对于操作系统来说,您可能需要用向后兼容的二进制模式安装",
	'loader_download_instructions_download_unix3' => " 从下面的Loader列表中下载一个  ",
	'loader_download_instructions_download_unix4' => " 注意:对于",
	'loader_download_instructions_download_unix4-1' => " 操作系统来说,您需要以向后兼容的二进制模式安装",
	'loader_install_instructions1' => "将Loader文件放到 ",
	'loader_install_instructions1-1' => " 文件夹内(如果该文件夹不存在，请创建一个)",
	'loader_install_instructions2' => "将Loader文件上传到您的web服务器的 ",
	'loader_install_instructions2-1' => " 文件夹内",
	'loader_install_instructions2' => "下载Windows版的Loader。如果PHP是非线程安全的（thread safety disabled,），请使用 Windows non-TS Loaders",
	
	'scan_inis_for_loader1' => "在这台虚拟主机上，ionCube Loader配置向导找不到PHP的ini文件，或者这个文件无法读取。",
	'scan_inis_for_loader2' => "ionCube Loader配置向导无法找到下面的ini文件 ",
	'scan_inis_for_loader3' => "或许是因为服务器的权限设置 ",
	'scan_inis_for_loader4' => " 配置文件中无法找到包含zend_extension的行 ",
	'find_loader' => "在标准位置无法找到Loader文件 ",
	'loader_compatibility_test_error_loader_unexpected_name1' => "您当前的操作系统需要的Loader名称是 ",
	'loader_compatibility_test_error_loader_unexpected_name1-1' => " 而您目前已经安装的Loader是 ",
	'loader_compatibility_test_error_loader_unexpected_name1-2' => " 。请您使用正确的Loader。 ",
	'loader_compatibility_test_error_error_loader_not_readable1' => "这个位置 ",
	'loader_compatibility_test_error_error_loader_not_readable1-1' => " 的Loader好像不能被读取。",
	'loader_compatibility_test_error_error_loader_not_readable1-2' => " <br/>请检查这个文件是否存在，是否可以有读取的权限。 ",
	'loader_compatibility_test_error_error_loader_not_readable1-3' => " <br/>请检查是否包含这些许可 ",
	'loader_compatibility_test_error_error_loader_not_readable1-3-1' => "<br/>请检查是否web服务器被重启 ",
	'loader_compatibility_test_error_error_loader_php_mismatch1' => "您当前服务器已经安装的PHP版本是 ",
	'loader_compatibility_test_error_error_loader_php_mismatch1-2' => "而您安装的Loader运行需要的PHP版本是 ",
	'loader_compatibility_test_error_error_loader_php_mismatch1-3' => "",
	'loader_compatibility_test_error_error_loader_nonts_php_ts' => "您当前的服务器运行的PHP版本是线程安全的版本(thread-safe)，而当前安装的Loader不是线程安全的版本",
	'loader_compatibility_test_error_error_loader_ts_php_nonts' => "您当前的服务器运行的PHP版本是非线程安全的版本(non-thread-safe)，而当前安装的Loader是线程安全的版本",
	'loader_compatibility_test_error_error_loader_win_server_nonwin' => "您当前的服务器是Windows系统，而您当前运行的Loader不能运行在Windows上",
	'loader_compatibility_test_error_error_loader_win_nonts_php_ts' => "当前服务器上运行的是一个在Windows下运行的非线程安全版本的Loader，但是当前Windows系统实际需要一个线程安全版本的Loader",
	'loader_compatibility_test_error_error_loader_win_ts_php_nonts' => "当前服务器上运行的是一个在Windows下运行的线程安全版本的Loader，但是当前Windows系统实际需要一个非线程安全版本的Loader",
	'loader_compatibility_test_error_error_loader_win_php_mismatch1' => "您当前服务器运行的PHP版本是 ",
	'loader_compatibility_test_error_error_loader_win_php_mismatch1-1' => " 而目前已经安装的Loader需要的PHP版本是 ",
	'loader_compatibility_test_error_error_loader_win_php_mismatch1-2' => "",
	'loader_compatibility_test_error_error_loader_win_compiler_mismatch1' => "您当前的Loader使用",
	'loader_compatibility_test_error_error_loader_win_compiler_mismatch1-1' => " 建立的，但是您需要使用 ",
	'loader_compatibility_test_error_error_loader_win_compiler_mismatch1-2' => " 来建立",
	'loader_compatibility_test_error_error_loader_php_version_unknown' => "当前的PHP版本和Loader的版本不兼容，请选择一个正确的Loader",
	'runtime_loading_instructions_h4' => "当前的PHP版本和Loader的版本不兼容，请选择一个正确的Loader",
	'runtime_loading_instructions1' => "在虚拟主机上ionCube Loader可以使用运行时加载的方法进行加载",
	'runtime_loading_instructions2' => "请点击这里，如果您的主机",
	'runtime_loading_instructions3' => "不是",
	'runtime_loading_instructions4' => "虚拟主机",
	'runtime_loading_instructions5' => " 请注意，当第一个加密文件被读取的时候，Loder",
	'runtime_loading_instructions6' => "必须",
	'runtime_loading_instructions7' => "存在于",
	'runtime_loading_instructions8' => "中",
	'runtime_loading_errors1' => "没有找到扩展目录",
	'runtime_loading_errors2' => "在 ",
	'runtime_loading_errors3' => " 里没有找到Loader文件",
	
	'zend_extension_instructions1' => "请在 ",
	'zend_extension_instructions1-1' => " 文件夹内编辑",
	'zend_extension_instructions1-2' => "文件",
	'zend_extension_instructions2' => "在 ",
	'zend_extension_instructions2-1' => " 文件夹下的php.ini文件已经被添加了ionCube Loader",
	'zend_extension_instructions3' => "在 ",
	'zend_extension_instructions3-1' => " 文件夹下创建了",
	'zend_extension_instructions3-2' => "文件",
	'zend_extension_instructions4' => "编辑 ",
	'zend_extension_instructions4-1' => " 这个文件",
	'zend_extension_instructions5' => "下载 ",
	'zend_extension_instructions5-1' => " 文件，将其上传到服务器，然后将文件移动到您的ini文件所在的",
	'zend_extension_instructions5-2' => " 文件夹下",
	'zend_extension_instructions6' => "编辑",
	'zend_extension_instructions6-1' => "文件",
	'zend_extension_instructions7' => "编辑 ",
	'zend_extension_instructions7-1' => " 这个系统文件",
	'zend_extension_instructions4-2' => "并且要保证下面添加的这一行在其他 ",
	'zend_extension_instructions4-3' => " 行的<strong>前面</strong>：",
	'zend_extension_instructions4-4' => "",
	'zend_extension_instructions4-5' => "或者，",
	'zend_extension_instructions4-6' => "下载 ",
	'zend_extension_instructions4-7' => " 文件替换您当前的 ",
	'zend_extension_instructions4-8' => " 文件",
	
	'may_need_to_copy_ini1' => "请注意,如果经过加密的文件在不同的",
	'may_need_to_copy_ini2' => " 内，您可以尝试着将 ",
	'may_need_to_copy_ini3' => " 复制到加密文件所在的 ",
	'may_need_to_copy_ini4' => " 内 ",
	'successful_install_end_instructions1' => "安装运行时加载Loader的方法被应用于 ",
	'successful_install_end_instructions1-1' => " 路径中",
	
	'loader_major_version_instructions1' => " 当前的已经安装的Loader版本不是最新的，建议您下载最新版本的Loader。",
	'loader_major_version_instructions2' => " 最新版的Loader版本号是 ",
	
	'loader_already_installed1' => " Loader已经安装 ",
	'loader_already_installed2' => "ionCube Loader 版本 ",
	'loader_already_installed2-1' => "已经安装",
	'loader_already_installed2-2' => " ，但这个版本是个旧版本的Loader",
	'loader_already_installed2-3' => "如果可能的话，我们推荐您将Loader的版本升级到最新版。",
	'loader_already_installed3' => "已经安装并且没有任何问题",
	
	'loader_upgrade_instructions1' => "Loader 升级说明",
	'loader_upgrade_instructions2' => "可以",
	'loader_upgrade_instructions2-1' => "需要",
	'loader_upgrade_instructions3' => "请注意：您",
	'loader_upgrade_instructions3-1' => " 联系系统管理员做下面的升级工作。当Loader被升级后，Web 服务器需要重新启动。",
	'loader_upgrade_instructions4' => " 版本",
	'loader_upgrade_instructions4-1' => " 一个新版本 ",
	'loader_upgrade_instructions5' => " 一旦替换了Loader文件后，您需要重启Web Server ",
	
	'loader_not_installed1' => " 请注意下面这些当前已经存在的问题 ",
	'loader_not_installed1-1' => " 请注意下面这些当前已经存在的问题 ",
	'loader_not_installed2' => " 在ionCube Loader安装过程中  ",	
	'loader_not_installed3' => " 请注意下面这些问题： ",
	'loader_not_installed4' => " 当前您使用的这些PHP文件被加密，请安装 ionCube Loader 组件 ",
	'loader_not_installed5' => " 当前您使用的PHP版本是  ",
	'loader_not_installed5-1' => " ，ionCube Loader 不支持该版本的PHP，推荐您将PHP的版本升级到 PHP4，PHP4.2，PHP5.1，或者更高的PHP5版本",
	'loader_not_installed6' => "您当前运行的是debug模式的PHP。Loader不能被安装到debug模式下的PHP中。请重新配置PHP将其debug模式设为禁用。",
	'loader_not_installed7' => "Loader不能运行在Windows操作系统下的64位PHP环境中。",
	'loader_not_installed7-1' => " 如果您在Windows上 ",
	'loader_not_installed7-2' => " 安装32位版本的PHP ",
	'loader_not_installed7-3' => "和32位的loader后，软件就可以正常的工作了",
	'loader_not_installed8' => "从下面的列表中下载32位Windows x86 版本的Loader",
	'loader_not_installed8-1' => "从下面的列表中下载32位Windows x86 non-ts(非线程安全)版本的Loader",
	'loader_not_installed8-2' => "当前您安装的Loader相对您的操作系统来说可能无法正常运行。",
	'loader_not_installed9' => "当前ionCube Loader需要用",
	'loader_not_installed9-1' => " 编译的PHP版本",
	'loader_not_installed9-2' => "您的PHP是使用 ",
	'loader_not_installed9-3' => " 编译的",
	
	'server_selection_form1' => "这个向导将给您一些信息,帮助您安装ionCube Loader",
	'server_selection_form1-1' => "请选择您当前的Web服务器类型，然后点击下一步",
	'server_selection_form1-2' => "请选择一个Web服务器的类型",
	'server_selection_form1-3' => "请输入一个完整的主机提供商名称和他们的URL",
	'server_selection_form1-4' => "主机提供商的名称只能是4个字符",
	'server_selection_form1-5' => "主机提供商的URL无效",
	'server_selection_form1-6' => "主机提供商的URL只能在5个字符内",
	'server_selection_form2' => "(例如,服务器只能通过ftp方式访问并且不能访问php.ini)",
	'server_selection_form3' => "专用或者VPS主机",
	'server_selection_form3-1' => "服务器有root和ssh权限",
	'server_selection_form4' => "如果您是专用主机或者是虚拟主机，请联系您的主机提供商并且给他们下面的URL",
	'server_selection_form5' => "服务器有root和ssh权限",
	'server_selection_form5-1' => "主机提供商的名字",
	'server_selection_form5-2' => "主机提供商的URL",
	'server_selection_form5-3' => "本地安装",
	
	'phpinfo_page' => "当前服务器关闭了phpinfo",
	'loader_check_page' => "Loader 安装成功 ",
	'loader_check_page1' => "ionCube Loader ",
	'loader_check_page1-1' => " 已经安装 ",
	'loader_check_page2' => " 请注意您当前的ionCube Loader是一个旧版本 ",
	'loader_check_page3' => " Loader没有安装成功 ",
	'loader_check_page4' => " 运行中加载Loader的尝试失败 ",
	
	'ini_loader_warnings1' => "PHP无法识别这个配置文件 ",
	'ini_loader_warnings1-1' => " 请检查文件的文件名和位置是否正确 ",
	'ini_loader_warnings1-2' => " 请尝试复制 ",
	'ini_loader_warnings1-3' => " 到 ",
	'ini_loader_warnings1-4' => " 或许您需要复制 ",
	'ini_loader_warnings1-5' => " 到全部有加密文件的 ",
	'ini_loader_warnings1-6' => "您可能无法在虚拟主机中创建自己的ini文件 ",
	'ini_loader_warnings1-7' => "您或许需要请您的系统管理员来帮助您配置php.ini文件后，才能使用ionCube Loader",
	'ini_loader_warnings2' => "在您的系统中，正确的Loader被放在 ",
	'ini_loader_warnings2-1' => " 您可以将复制Loader从",
	'ini_loader_warnings2-2' => " 到 ",
	
	'list_loader_errors1' => "再试一次",
	'list_loader_errors1-1' => "在安装ionCube Loader时出现了下列问题",
	'list_loader_errors1-2' => "请检查这些问题并再试一次",
	'list_loader_errors2' => "也请注意下面这些",
	'list_loader_errors3' => "请注意下面这些潜在的问题",
	'list_loader_errors4' => "请联系您的系统管理员安装ionCube Loader",
	'list_loader_errors5' => "看起来在您的服务器上 SELinux 被启用了。以root权限运行这个命令看起来能解决这个问题 ",
	'list_loader_errors5-1' => " 如果问题没有解决，请查看这个说明 ",
	'list_loader_errors5-2' => " 来解决在 SELinux被启用时，如何安装ionCube Loader ",
	'list_loader_errors6' => "看起来在您的服务器上 grsecurity 被启用了。请运行这个命令 ",
	'list_loader_errors6-1' => " 然后重启web服务器 ",
	'list_loader_errors7' => "请检查 ",
	'list_loader_errors7-1' => " web服务器是否已经被重启 ",
	
	'extra_page1' => "附加信息",
	'extra_page2' => "下载Loader文件",
	'extra_page2' => "Loader没有找到",
	'GoDaddy_windows_instructions1' => "看起来您在使用一个godaddy的Windows主机",
	'GoDaddy_windows_instructions2' => " 您可以在Godaddy那里更换成一个Linux主机",
	'GoDaddy_windows_instructions3' => "如果您",
	'GoDaddy_windows_instructions4' => "联系Godaddy团队",
	'GoDaddy_windows_instructions5' => "他们将帮助您切换到Linux主机",
	'GoDaddy_linux_instructions1' => "在您的html文件夹 ",
	'GoDaddy_linux_instructions2' => "内，创建一个名称为 ",
	'GoDaddy_linux_instructions3' => "的子文件夹 ",
	'GoDaddy_linux_instructions4' => "编辑 ",
	'GoDaddy_linux_instructions4-1' => " 文件，在你的 ",
	'GoDaddy_linux_instructions4-2' => " 并且在文件的<strong>头部</strong>添加下面的行 ",
	'GoDaddy_linux_instructions5' => "保存这个 ",
	'GoDaddy_linux_instructions5-1' => "文件",
	'GoDaddy_linux_instructions5-2' => " 并且将这个文件上传到 ",
	'GoDaddy_linux_instructions5-3' => " 文件夹内 ",
	'GoDaddy_linux_instructions6' => " 下载 ",
	'GoDaddy_linux_instructions6-1' => " Linux 版的ionCube Loader",
	'GoDaddy_linux_instructions6-2' => " 解压这个loader文件,然后将其上传到你刚才创建的文件夹内",
	'GoDaddy_linux_instructions6-3' => " 加密文件现在可以正常的工作了",
	'GoDaddy_page1' => "GoDaddy安装说明",
	'GoDaddy_page2' => "看起来您是一台Godaddy主机",
	'GoDaddy_page3' => "如果<strong>不是</strong>这种情况，请",
	'GoDaddy_page4' => "点击这里返回安装向导",
	'GoDaddy_page5' => "如果您已经安装了Loader，请",
	'GoDaddy_page6' => "点击这里测试Loader",
	'error1' => "请报告这个错误，来帮助我们改进这个安装包",
	'error2' => "反馈问题",



	'zend_extension_instructions_download_ini_file1' => "下载",
	'zend_extension_instructions_download_ini_file1-1' => "文件 ",
	'zend_extension_instructions_download_ini_file1-2' => " ，将其上传到服务器，然后将文件移动到 ",
	'zend_extension_instructions_download_ini_file1-3' => " 文件夹下(服务器上的完整路径) ",
	'server_restart_instructions_des1' => "重启 ",
	'server_restart_instructions_des1-1' => " 服务器",
	'server_restart_instructions_des2' => "重启Web服务器",
	'server_restart_instructions_des3' => "重启Web服务器后，请点击<strong> 上一步 </strong>重新开始安装",
	'server_restart_instructions_des4' => "如果安装Loader失败，请检查 Apache的错误日志",
	'loader_not_installed_error_explain' => "我们的产品需要加载一个名为ioncube_loader的扩展，该扩展必须安装！",
	'loader_already_installed' => "ionCube Loader 已经安装成功！",
	'successful_install_end_instructions' => "ionCube Loader 升级操作",
	'loader_already_installed_new_version1' => "当前安装的ionCube Loader ",
	'loader_already_installed_new_version1-1' => " 是一个低版本，我们推荐您升级到最新版",
	'loader_major_version_instructions1' => "目前安装的Loader版本过低，如果您希望提高PHP页面的运行速度，您需要将Loader升级到 ionCube Loader ",
	'loader_major_version_instructions1-1' => "版本 ",
	'loader_upgrade_instructions' => "Loader升级操作 ",
	'loader_upgrade_instructions1' => "请注意：您或许需要您的系统管理员按照以下的步骤来进行升级操作。当重新安装了Loader文件后，web服务器需要重新启动后，Loader才能生效 ",
	'loader_upgrade_instructions2' => "将当前版本 ",
	'loader_upgrade_instructions2-1' => " 升级到  ",
	'loader_upgrade_instructions2-2' => " ，请替换当前已经存在的Loader文件：",
	'loader_upgrade_instructions2-3' => " 您需要下载下面的压缩包之一，并用里面的同名文件替换： ",
	'loader_upgrade_instructions3' => "一旦您替换了Loader文件，请重新启动您的Web服务器 ",
	'loader_already_installed1' => "您目前已经<strong>成功</strong>的安装了ionCube Loader ",
	'loader_already_installed1-1' => "，您可以点击下一步按钮继续安装了。",
	'ini_loader_errors_error_ini_user_cannot_create' => "目前看起来您不能在服务器上创建自己的php.ini配置文件，您需要请您的服务器管理员帮助您安装ionCube Loader",
	'ini_loader_errors_error_ini_no_path' => "在您的服务器配置的路径中，没有找到您的php.ini文件",
	'ini_loader_errors_error_ini_not_found' => "没有找到PHP配置文件 ",
	'correct_loader_wrong_location' => "没有找到ionCube Loader文件",
	'uninstall_wizard_instructions' => "您的ionCube Loader已经安装成功！",
	'win_ioncube_error' => '	请修改php.ini文件.在文件最后增加一行如下例，其中"d:/www/oes/ioncube/～"为ioncube的存放路径。
						注意：请根据服务器安装的php版本选择正确的ioncube版本，下例以php版本5.2为例。如果您的php.ini中已经配置其他zend_extension，请确保ioncube在其他zend_extension之前。
						填写方式如下：
						Windows服务器(二选一)
						zend_extension_ts="d:/www/oes/ioncube/ioncube_loader_win_5.2.dll"
						zend_extension="d:/www/oes/ioncube/ioncube_loader_win_5.2.dll"
						以上根据本地php是否为线程安全，选择其中的一个添加即可。zend_extension_ts表示线程安全',
	'lin_ioncube_error' => '	请修改php.ini文件.在文件最后增加一行如下例，其中"/var/www/oes/ioncube/～"为ioncube的存放路径。
						注意：请根据服务器安装的php版本选择正确的ioncube版本，下例以php版本5.2为例。如果您的php.ini中已经配置其他zend_extension，请确保ioncube在其他zend_extension之前。
						填写方式如下：
						Linux服务器(二选一)
						zend_extension="/var/www/oes/ioncube/ioncube_loader_lin_5.2.so"
						zend_extension_ts="/var/www/oes/ioncube/ioncube_loader_lin_5.2_ts.so"
						以上根据本地php是否为线程安全，选择其中的一个添加即可。zend_extension_ts表示线程安全',
						
						
	
	'license' => '<div class="license"><h1>中文版授权协议 适用于中文用户</h1>

<p>版权所有 (c) 2009-2013，大连奥瑞文网络技术有限公司保留所有权利。</p>

<p>感谢您选择 '.SOFT_NAME.' 产品。希望我们的努力能为您提供一个高效快速和强大的在线考试，在线培训解决方案。</p>

<p>大连奥瑞文网络技术有限公司为 '.SOFT_NAME.' 产品的开发商，依法独立拥有 '.SOFT_NAME.' 产品著作权</p>
<p>'.SOFT_NAME.' 官方网址为 http://www.orivon.com</p>

<p>'.SOFT_NAME.' 著作权已在中华人民共和国国家版权局注册，著作权受到法律和国际公约保护。
使用者：无论个人或组织、盈利与否、用途如何（包括以学习和研究为目的），均需仔细阅读本协议，在理解、同意、并遵守本协议的全部条款后，方可开始使用 '.SOFT_NAME.' 软件。</p>

<p>本授权协议适用且仅适用于 '.SOFT_NAME.' 2.x 版本，大连奥瑞文网络技术有限公司拥有对本授权协议的最终解释权。</p>

<h3>I. 协议许可的权利</h3>
<ol>
<li>您拥有使用本软件构建的网站中全部会员资料、文章及相关信息的所有权，并独立承担与文章内容的相关法律义务。</li>
<li>获得商业授权之后，您可以将本软件应用于商业用途，同时依据所购买的授权类型中确定的技术支持期限、技术支持方式和技术支持内容，
自购买时刻起，在技术支持期限内拥有通过指定的方式获得指定范围内的技术支持服务。商业授权用户享有反映和提出意见的权力，相关意见将被作为首要考虑，
但没有一定被采纳的承诺或保证。</li>
</ol>

<h3>II. 协议规定的约束和限制</h3>
<ol>
<li>未获商业授权之前，不得将本软件用于商业用途（包括但不限于企业网站、经营性网站、以营利为目或实现盈利的网站）。购买商业授权请登入 http://www.orivon.com 参考相关说明。</li>
<li>不得对本软件或与之关联的商业授权进行出租、出售、抵押或发放子许可证。</li>
<li>无论如何，即无论用途如何、是否经过修改或美化、修改程度如何，只要使用 '.SOFT_NAME.' 的整体或任何部分，
	未经书面许可，页面页脚处的 '.SOFT_NAME.' 名称和大连奥瑞文网络技术有限公司下属网站（http://www.orivon.com） 的链接都必须保留，而不能清除或修改。</li>
<li>禁止在 '.SOFT_NAME.' 的整体或任何部分基础上以发展任何派生版本、修改版本或第三方版本用于重新分发。</li>
<li>如果您未能遵守本协议的条款，您的授权将被终止，所被许可的权利将被收回，并承担相应法律责任。</li>
</ol>

<h3>III. 有限担保和免责声明</h3>
<ol>
<li>本软件及所附带的文件是作为不提供任何明确的或隐含的赔偿或担保的形式提供的。</li>
<li>用户出于自愿而使用本软件，您必须了解使用本软件的风险，在尚未购买产品技术服务之前，我们不承诺提供任何形式的技术支持、使用担保，也不承担任何因使用本软件而产生问题的相关责任。</li>
<li>大连奥瑞文网络技术有限公司不对使用本软件构建的网站中的文章或信息承担责任。</li>
</ol>

<p>有关 '.SOFT_NAME.' 最终用户授权协议、商业授权与技术服务的详细内容，均由 '.SOFT_NAME.'  官方网站独家提供。
大连奥瑞文网络技术有限公司拥有在不事先通知的情况下，修改授权协议和服务价目表的权力，修改后的协议或价目表对自改变之日起的新授权用户生效。</p>

<p>电子文本形式的授权协议如同双方书面签署的协议一样，具有完全的和等同的法律效力。您一旦开始安装 '.SOFT_NAME.' ，
即被视为完全理解并接受本协议的各项条款，在享有上述条款授予的权力的同时，受到相关的约束和限制。
协议许可范围以外的行为，将直接违反本授权协议并构成侵权，我们有权随时终止授权，责令停止损害，并保留追究相关责任的权力。</p></div>',

	'update_locked' => '更新锁定，如果您确定要更新，请到服务器上删除<br /> ' . $config['_browseHome'] . '/update.lock',
	'update_begin'=>'升级中，请稍候......',
	'update_end'=>'恭喜您！升级完成。'
);
