"function"!==typeof window.L.strVar("L.extension.pageTable.init")&&window.L.strVar("L.extension.pageTable.callback.afterLoadList[]",window.L.strVar("L.extension.pageTable.callback.initLoadList[]",function(g){if(""!==g.getElementsByTagName("thead")[0].innerHTML){for(var c=g.getElementsByTagName("thead")[0].getElementsByTagName("font"),a=0,b=c.length;a<b;++a)null!==c[a].getAttribute("_pageTableSort")&&-1===c[a].className.indexOf("sortDefault")&&(c[a].className="sortDefault");g=g.getElementsByTagName("tbody")[0].childNodes;
c=a=0;for(b=g.length;a<b;++a)"TR"===g[a].tagName&&(g[a].className=++c%2?"odd_bg":"even_bg")}}));
(function(){var g={init:function(c){for(var a=document.getElementsByTagName("table"),b,d,e=0,k=a.length;e<k;++e)if("string"===typeof a[e].getAttribute("_pageTableDataset")&&null==a[e]._pageTableSortStatusList){b=a[e];b._pageTableConfig={};if(null===(d=b.getAttribute("_pageTableSort")))b._pageTableSortStatusList={};else{b._pageTableSortStatusList=(new Function("return "+d))();for(var i=b.getElementsByTagName("thead")[0].getElementsByTagName("font"),f=0,h=i.length;f<h;++f)if("thTitle"===i[f].getAttribute("name")&&
null!==(d=i[f].getAttribute("_pageTableSort"))){d=i[f]._pageTableSortList=(new Function("return "+d))();if(""===i[f].parentNode.getAttribute("_bottomTh")){var j=b._pageTableSortStatusList[d[0]].objList;j[j.length]=i[f]}window.L.onEvent.addEvent(i[f],"click",g.thTitleClickSortFn(b,i[f]))}}d=g.getChildNodesTag(b,"tfoot").getElementsByTagName("div");f=0;for(h=d.length;f<h;++f)if("page_nav"===d[f].id){f=d[f].getElementsByTagName("*");h=0;for(i=f.length;h<i;++h)if(1===f[h].nodeType)switch(f[h].id){case "page_first":window.L.onEvent.addEvent(f[h],
"click",g.pageClickFn(b,!0));break;case "page_last":0>b.getAttribute("_pageTableTotalItems")?f[h].style.display="none":(f[h].style.display="",window.L.onEvent.addEvent(f[h],"click",g.pageClickFn(b,!1)));break;case "page_prev":window.L.onEvent.addEvent(f[h],"click",g.pageClickFn(b,-1));break;case "page_next":window.L.onEvent.addEvent(f[h],"click",g.pageClickFn(b,1));break;case "page_submit":window.L.onEvent.addEvent(f[h],"click",g.pageClickFn(b,null,f[h]));break;case "toPage":d=parseInt(b.getAttribute("_pageTableCurPage"))+
1;f[h].value=d<=b.getAttribute("_pageTableTotalPages")||0>b.getAttribute("_pageTableTotalItems")?d:1;window.L.onEvent.addEvent(f[h],"keypress",g.toPageKeypressFn(b,f[h]));window.L.onEvent.addEvent(f[h],"mouseover",function(){this.focus();this.select()});b._pageTableConfig.toPageObj=f[h];break;case "pageSize":f[h].value=b.getAttribute("_pageTablePageSize");window.L.onEvent.addEvent(f[h],"keypress",g.toPageKeypressFn(b,f[h]));window.L.onEvent.addEvent(f[h],"mouseover",function(){this.focus();this.select()});
break;case "page_num":f[h].innerHTML=b.getAttribute("_pageTableCurPage")+" / "+b.getAttribute("_pageTableTotalPages");b._pageTableConfig.pageNumObj=f[h];break;case "totaLitems":f[h].innerHTML=b.getAttribute("_pagetabletotalitems")}break}g.initCustomNav(a[e]);!0!==c&&g.callbackLoadList(b,"init")}},load:function(c,a){if(!1===g.callbackLoadList(c,"before"))return!1;var b=c.getAttribute("_pageTableParams"),d=c.getAttribute("_pageTableStarterPrint");if(""===d||null===d)d=1;null!==b&&(b="&_pageTableParams="+
encodeURIComponent(unescape(b)).replace(/%20/g,"+"));if("object"!==typeof a||null==a)a={};g.loadLock(c,!0);window.L.AJAX({url:window.L._rootUrl+"/include/Of/Com/CommonPackage.php?a=pageTable",data:"_pageTableDataset="+c.getAttribute("_pageTableDataset")+"&_pageTableTotalItems="+c.getAttribute("_pageTableTotalItems")+"&_pageTablePageSize="+c.getAttribute("_pageTablePageSize")+"&_pageTableCurPage="+c.getAttribute("_pageTableCurPage")+"&_pageTableColspan="+c.getAttribute("_pageTableColspan")+"&_pageTableStarterPrint="+
d+(null===b?"":b)+(null!=c._pageTableConfig.sortStr&&""!==c._pageTableConfig.sortStr?"&_pageTableSort="+c._pageTableConfig.sortStr:""),context:this,pageTableObj:c,starterPrint:d,success:function(c,b){if(!b.pageTableObj.parentNode)return!1;if(1==b.starterPrint)b.pageTableObj._pageTableConfig.pageNumObj&&(b.pageTableObj._pageTableConfig.pageNumObj.innerHTML=b.pageTableObj.getAttribute("_pageTableCurPage")+" / "+b.pageTableObj.getAttribute("_pageTableTotalPages")),this.html(b.pageTableObj.getElementsByTagName("tbody")[0],
c),g.loadLock(b.pageTableObj,!1);else{var d=b.pageTableObj._pageTableSortStatusList,f=this.html(b.pageTableObj,c);this.init(!a.callbackInit);var h=[],j;for(j in f._pageTableSortStatusList)null!=d[j]&&null!=d[j].status&&(f._pageTableSortStatusList[j].status=d[j].status,h[h.length]="`"+j+"` "+d[j].status,this.sortStyle(f._pageTableSortStatusList[j]));f._pageTableConfig.sortStr=h.join(",");b.pageTableObj=f;try{f._pageTableConfig.toPageObj.focus()}catch(l){}}"string"===typeof a._pageTableStarterPrint&&
b.pageTableObj.setAttribute("_pageTableStarterPrint",a._pageTableStarterPrint);a.callbackInit||g.callbackLoadList(b.pageTableObj,"after")}})},html:function(c,a){var b=document.createElement("div");if("string"===typeof a){if("TBODY"===c.tagName)b.innerHTML="<table><tbody>"+a+"</tbody></table>",a=b.getElementsByTagName("tbody")[0].childNodes;else{b.innerHTML=a;var d=b.getElementsByTagName("table")[0];c.parentNode.replaceChild(d,c);c=d;b.innerHTML=a;a=b.getElementsByTagName("table")[0].childNodes}for(;c.firstChild;)c.removeChild(c.firstChild);
for(var d=0,e=a.length;d<e;++d)1===a[0].nodeType?this.html(c,a[0]):c.appendChild(a[0]);return c}if("SCRIPT"===a.tagName)(window.execScript||function(a){window.eval.call(window,a)})(a.text||a.textContent||a.innerHTML||"");else{for(var g=a.childNodes,e=g.length,d=0;d<e;++d)b.appendChild(g[0]);c.appendChild(a);g=b.childNodes;e=g.length;for(d=0;d<e;++d)1===g[0].nodeType?this.html(a,g[0]):a.appendChild(g[0])}},initCustomNav:function(c){var a=0,b;if(null==c)arguments.callee.resize();else{b=g.getChildNodesTag(c,
"tfoot").getElementsByTagName("td")[0].childNodes;for(var d=0,e=b.length;d<e;++d)if("page_nav"===b[d].className&&(a=b[d].offsetWidth),"custom_nav"===b[d].className){for(var k=b[d].parentNode.clientWidth-a-10,i=b[d].getElementsByTagName("div")[0].scrollWidth,e=b[d].childNodes,f=0,h=e.length;f<h;++f)if("LABEL"===e[f].tagName){e=e[f];break}0>=k&&(k=1);i<=k?(e.style.display="none",b[d].style.width=i+"px",b[d].onmouseover=null,b[d].onmouseout=null):(e.style.display="inline",b[d].style.width=k+"px",b[d].onmouseover=
function(){this.style.width=i+"px";this.style.backgroundColor="#FFFFFF"},b[d].onmouseout=function(){this.style.width=k+"px";this.style.backgroundColor="transparent"});a||(a=b[d].currentStyle?[b[d].parentNode.currentStyle,b[d].currentStyle]:[document.defaultView.getComputedStyle(b[d].parentNode,null),document.defaultView.getComputedStyle(b[d],null)],a[0]=parseInt("auto"!=a[0].marginTop&&a[0].marginTop||0)+parseInt("auto"!=a[0].borderTop&&a[0].borderTop||0)+parseInt("auto"!=a[0].paddingTop&&a[0].paddingTop||
0)+parseInt("auto"!=a[0].marginButtom&&a[0].marginButtom||0)+parseInt("auto"!=a[0].borderButtom&&a[0].borderButtom||0)+parseInt("auto"!=a[0].paddingButtom&&a[0].paddingButtom||0),a[1]=parseInt("auto"!=a[1].marginTop&&a[1].marginTop||0)+parseInt("auto"!=a[1].borderTop&&a[1].borderTop||0)+parseInt("auto"!=a[1].paddingTop&&a[1].paddingTop||0)+parseInt("auto"!=a[1].marginButtom&&a[1].marginButtom||0)+parseInt("auto"!=a[1].borderButtom&&a[1].borderButtom||0)+parseInt("auto"!=a[1].paddingButtom&&a[1].paddingButtom||
0),b[d].parentNode.parentNode.style.height=b[d].offsetHeight+a[0]+a[1]+"px");break}}},callbackLoadList:function(c,a){var b;if(b=window.L.strVar("L.extension.pageTable.callback."+a+"LoadList[]")){for(var d={},e=0,g=b.length;e<g;++e)if("function"===typeof b[e])if("undefined"===typeof d[b[e].toString()]){window.L.extension.pageTable.nowCallback={pageTableObj:c,pageTableClass:this,index:e,type:a};if(!1===b[e](c,this,e,a)){delete window.L.extension.pageTable.nowCallback;return}b[e]&&(d[b[e].toString()]=
"")}else delete b[e];delete window.L.extension.pageTable.nowCallback}},eachTbody:function(c,a,b,d,e){var g=[],i=c.getElementsByTagName("tbody")[0].childNodes;"function"!==typeof d&&(d=function(){});null==a&&(a="*");null==b&&(b="*");if("object"!==typeof e||null==e)e=window.L.onEvent.getEventTarget(c);for(var f=0,h=0,j=i.length;f<j;++f)if("TR"===i[f].tagName){if("*"===a||a==h)for(var c=i[f].childNodes,l=0,m=0,n=c.length;l<n;++l)if("TD"===c[l].tagName){if("*"===b||b==m)d.call(e,g[g.length]={y:h,x:m,
tdObj:c[l]});++m}++h}return g},params:function(c,a,b){if("undefined"===typeof a)return c=unescape(c.getAttribute("_pageTableParams")),"[]"===c?{}:window.L.JSON.parse(c);null!==a&&c.setAttribute("_pageTableParams",escape(window.L.JSON.stringify(a)));!0===b&&(a=c.getAttribute("_pageTableStarterPrint"),c.setAttribute("_pageTableStarterPrint",0),c.setAttribute("_pageTableCurPage",1),this.load(c,{_pageTableStarterPrint:a,callbackInit:!0}))},getChildNodesTag:function(c,a,b){for(var c=c.childNodes,d=[],
e=0,g=c.length;e<g;++e)c[e].tagName===a.toUpperCase()&&(d[d.length]=c[e]);return"boolean"===typeof b?d:d[b||0]},sortStyle:function(c){for(var a=0,b=c.objList.length;a<b;++a)c.objList[a].className="DESC"===c.status?"sortDefault sortDesc":"ASC"===c.status?"sortDefault sortAsc":"sortDefault"},loadLock:function(c,a){c._pageTableConfig.loadLockObj&&!0!==a&&(c._pageTableConfig.loadLockObj.parentNode.removeChild(c._pageTableConfig.loadLockObj),delete c._pageTableConfig.loadLockObj);if(!c._pageTableConfig.loadLockObj&&
!0===a||!1!==a&&!0!==a){var b=c.getElementsByTagName("thead")[0],d=document.createElement("tr"),e=document.createElement("td");d.className="pageTableLoadLock";d.appendChild(e);e.colSpan=c.getAttribute("_pageTableColspan");e.innerHTML='<div class="pageTableLoadLock"></div><font style="position:absolute;"><img src="'+window.L._rootUrl+'/images/components/pageTable/loadLock.gif" align="middle" style="margin-right:5px; vertical-align:middle;" />'+("string"===typeof a?a:"")+"</font>";e=e.childNodes;e[0].style.height=
c.clientHeight+"px";e[0].style.width=c.clientWidth+"px";e[1].style.top=(c.clientHeight-e[1].offsetHeight>>1)+"px";e[1].style.left=(c.clientWidth-e[1].offsetWidth>>1)+"px";b.insertBefore(d,b.firstChild);c._pageTableConfig.loadLockObj=d}},thTitleClickSortFn:function(c,a){var b=this;return function(){var d,e=[],g;for(g in c._pageTableSortStatusList){var i=!0;d=c._pageTableSortStatusList[g];for(var f=0,h=a._pageTableSortList.length;f<h;++f)g===a._pageTableSortList[f]&&(i=!1,"DESC"===d.status?(d.status=
"ASC",e[e.length]="`"+a._pageTableSortList[f]+"`"):(d.status="DESC",e[e.length]="`"+a._pageTableSortList[f]+"` DESC"));i&&delete d.status;b.sortStyle(d)}c._pageTableConfig.sortStr=e.join(",");b.load(c)}},pageClickFn:function(c,a,b){return function(){if(!0===a)c.setAttribute("_pageTableCurPage",1);else if(!1===a)c.setAttribute("_pageTableCurPage",c.getAttribute("_pageTableTotalPages"));else if(null===a)for(var d=b.parentNode.getElementsByTagName("input"),e=0,k=d.length;e<k;++e)g.toPageKeypressFn(c,
d[e])();else d=parseInt(c.getAttribute("_pageTableCurPage"))+a,1>d?d=1:d>c.getAttribute("_pageTableTotalPages")&&(d=c.getAttribute("_pageTableTotalPages")),c.setAttribute("_pageTableCurPage",d);g.load(c)}},toPageKeypressFn:function(c,a){return function(b){if(void 0===b||"13"==b.keyCode){if("toPage"===a.id){var d=parseInt(a.value);if(isNaN(d)){a.value="";return}1>d?d=1:d>c.getAttribute("_pageTableTotalPages")&&(d=c.getAttribute("_pageTableTotalPages"));a.value=d+1<=c.getAttribute("_pageTableTotalPages")||
0>c.getAttribute("_pageTableTotalItems")?d+1:1;c.setAttribute("_pageTableCurPage",d)}else if("pageSize"===a.id)if(d=parseInt(a.value),0<d){if(0<=c.getAttribute("_pageTableTotalItems")){var e=Math.ceil(c.getAttribute("_pageTableTotalItems")/d);c.setAttribute("_pageTableTotalPages",e);c.getAttribute("_pageTableCurPage")>e&&c.setAttribute("_pageTableCurPage",e)}c.setAttribute("_pageTablePageSize",d)}else a.value="";void 0!==b&&g.load(c)}}}};null==window.L.extension.pageTable&&(window.L.extension.pageTable=
{});"function"!==typeof window.L.extension.pageTable.init&&(window.L.extension.pageTable.classObj=g,window.L.extension.pageTable.init=g.init,g.init(),g.initCustomNav.resize=function(){window.clearTimeout(arguments.callee.timeout);arguments.callee.timeout=window.setTimeout(function(){for(var c=document.getElementsByTagName("table"),a=0,b=c.length;a<b;++a)typeof c[a].getAttribute("_pageTableDataset")==="string"&&g.initCustomNav(c[a])},150)},window.L.onEvent.addEvent(window,"resize",g.initCustomNav.resize))})();
