window._ROOT_URL||(window._ROOT_URL="");var ObjAllExtend=function(a,b){for(var c in b)"object"==typeof a[c]&&null!=a[c]?ObjAllExtend(a[c],b[c]):"object"==typeof b[c]&&null!=b[c]?(a[c]={},ObjAllExtend(a,b)):a[c]=b[c]},bkExtend=function(){var a=arguments;1==a.length&&(a=[this,a[0]]);for(var b in a[1])a[0][b]=a[1][b];return a[0]};function bkClass(){}bkClass.prototype.construct=function(){};
bkClass.extend=function(a){var b=function(){if(arguments[0]!==bkClass)return this.construct.apply(this,arguments)},c=new this(bkClass);bkExtend(c,a);b.prototype=c;b.extend=this.extend;return b};
var bkElement=bkClass.extend({construct:function(a,b){"string"==typeof a&&(a=(b||document).createElement(a));return a=$BK(a)},appendTo:function(a){a.appendChild(this);return this},appendBefore:function(a){a.parentNode.insertBefore(this,a);return this},addEvent:function(a,b){bkLib.addEvent(this,a,b);return this},setContent:function(a){this.innerHTML=a;return this},pos:function(){var a=curtop=0;obj=this;if(obj.offsetParent){do a+=obj.offsetLeft,curtop+=obj.offsetTop;while(obj=obj.offsetParent)}var b=
!window.opera?parseInt(this.getStyle("border-width")||this.style.border)||0:0;return[a+b,curtop+b+this.offsetHeight]},noSelect:function(){bkLib.noSelect(this);return this},parentTag:function(a){var b=this;do{if(b&&b.nodeName&&b.nodeName.toUpperCase()==a)return b;b=b.parentNode}while(b);return!1},hasClass:function(a){return this.className.match(RegExp("(\\s|^)nicEdit-"+a+"(\\s|$)"))},addClass:function(a){this.hasClass(a)||(this.className+=" nicEdit-"+a);return this},removeClass:function(a){this.hasClass(a)&&
(this.className=this.className.replace(RegExp("(\\s|^)nicEdit-"+a+"(\\s|$)")," "));return this},setStyle:function(a){var b=this.style,c;for(c in a)try{switch(c){case "float":b.cssFloat=b.styleFloat=a[c];break;case "opacity":b.opacity=a[c];b.filter="alpha(opacity="+Math.round(100*a[c])+")";break;case "className":this.className=a[c];break;default:b[c]=a[c]}}catch(d){}return this},getStyle:function(a,b){var c=!b?document.defaultView:b;if(1==this.nodeType)return c&&c.getComputedStyle?c.getComputedStyle(this,
null).getPropertyValue(a):this.currentStyle[bkLib.camelize(a)]},remove:function(){this.parentNode.removeChild(this);return this},setAttributes:function(a){for(var b in a)this[b]=a[b];return this}}),bkLib={isMSIE:-1!=navigator.appVersion.indexOf("MSIE"),isFirefox:-1!=navigator.userAgent.indexOf("Firefox"),isChrome:-1!=navigator.userAgent.indexOf("Chrome"),version:(navigator.userAgent.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/i)||[])[1],addEvent:function(a,b,c){a.addEventListener?a.addEventListener(b,
c,!1):a.attachEvent("on"+b,c)},toArray:function(a){for(var b=a.length,c=Array(b);b--;)c[b]=a[b];return c},noSelect:function(a){a.setAttribute&&("input"!=a.nodeName.toLowerCase()&&"textarea"!=a.nodeName.toLowerCase())&&a.setAttribute("unselectable","on");for(var b=0;b<a.childNodes.length;b++)bkLib.noSelect(a.childNodes[b])},camelize:function(a){return a.replace(/\-(.)/g,function(a,c){return c.toUpperCase()})},inArray:function(a,b){return null!=bkLib.search(a,b)},search:function(a,b){for(var c=0;c<
a.length;c++)if(a[c]==b)return c;return null},cancelEvent:function(a){a=a||window.event;a.preventDefault&&a.stopPropagation&&(a.preventDefault(),a.stopPropagation());return!1},domLoad:[],domLoaded:function(){if(!arguments.callee.done){arguments.callee.done=!0;for(i=0;i<bkLib.domLoad.length;i++)bkLib.domLoad[i]()}},onDomLoaded:function(a){this.domLoad.push(a);document.addEventListener?document.addEventListener("DOMContentLoaded",bkLib.domLoaded,null):bkLib.isMSIE&&(document.write("<style>.nicEdit-main p { margin: 0; }</style><script id=__ie_onload defer "+
("https:"==location.protocol?"src='javascript:void(0)'":"src=//0")+"><\/script>"),$BK("__ie_onload").onreadystatechange=function(){"complete"==this.readyState&&bkLib.domLoaded()});window.onload=bkLib.domLoaded}};function $BK(a){"string"==typeof a&&(a=document.getElementById(a));return a&&!a.appendTo?bkExtend(a,bkElement.prototype):a}
var bkEvent={addEvent:function(a,b){b&&(this.eventList=this.eventList||{},this.eventList[a]=this.eventList[a]||[],this.eventList[a].push(b));return this},fireEvent:function(){var a=bkLib.toArray(arguments),b=a.shift();if(this.eventList&&this.eventList[b])for(var c=0;c<this.eventList[b].length;c++)this.eventList[b][c].apply(this,a)}};function __(a){return a}
Function.prototype.closure=function(){var a=this,b=bkLib.toArray(arguments),c=b.shift();return function(){if("undefined"!=typeof bkLib)return a.apply(c,b.concat(bkLib.toArray(arguments)))}};Function.prototype.closureListener=function(){var a=this,b=bkLib.toArray(arguments),c=b.shift();return function(d){d=d||window.event;return a.apply(c,[d,d.target?d.target:d.srcElement].concat(b))}};
bkLib.isMSIE||(window.HTMLElement.prototype.__defineGetter__("outerHTML",function(){var a=document.createElement("p");a.appendChild(this.cloneNode(!0));return a.innerHTML}),window.HTMLElement.prototype.__defineSetter__("outerHTML",function(a){this.parentNode.replaceChild(this.ownerDocument.createRange().createContextualFragment(a),this);return a}));
var outerHTML=function(a){var b=document.createElement("p");b.appendChild(a);return b.innerHTML},nicEditorConfig=bkClass.extend({buttons:{bold:{name:__("\u52a0\u7c97"),command:"Bold",tags:["B","STRONG"],css:{"font-weight":"bold"},key:"b"},italic:{name:__("\u503e\u659c"),command:"Italic",tags:["EM","I"],css:{"font-style":"italic"},key:"i"},underline:{name:__("\u4e0b\u5212\u7ebf"),command:"Underline",tags:["U"],css:{"text-decoration":"underline"},key:"u"},left:{name:__("\u5de6\u5bf9\u9f50"),command:"justifyleft",
noActive:!0},center:{name:__("\u5c45\u4e2d"),command:"justifycenter",noActive:!0},right:{name:__("\u53f3\u5bf9\u9f50"),command:"justifyright",noActive:!0},justify:{name:__("\u4e24\u7aef\u5bf9\u9f50"),command:"justifyfull",noActive:!0},ol:{name:__("\u7f16\u53f7\u5217\u8868"),command:"insertorderedlist",tags:["OL"]},ul:{name:__("\u9879\u76ee\u5217\u8868"),command:"insertunorderedlist",tags:["UL"]},subscript:{name:__("\u4e0b\u6807"),command:"subscript",tags:["SUB"]},superscript:{name:__("\u4e0a\u6807"),
command:"superscript",tags:["SUP"]},strikethrough:{name:__("\u5220\u9664\u7ebf"),command:"strikeThrough",css:{"text-decoration":"line-through"}},removeformat:{name:__("\u79fb\u9664\u683c\u5f0f"),command:"removeformat",noActive:!0},hr:{name:__("\u63d2\u5165\u6c34\u5e73\u7ebf"),command:"insertHorizontalRule",noActive:!0}},iconsPath:_ROOT_URL+oFileManagerMainDir+"/include/oEditor/resources/oEditorIcons.gif",buttonList:"save bold italic underline left center right justify ol ul fontSize fontFamily fontFormat indent outdent image upload link unlink forecolor bgcolor table subscript superscript strikethrough removeformat hr ImageArea AnswerSelect media xhtml".split(" "),
iconList:{xhtml:1,bgcolor:2,forecolor:3,bold:4,center:5,hr:6,indent:7,italic:8,justify:9,left:10,ol:11,outdent:12,removeformat:13,right:14,save:25,strikethrough:16,subscript:17,superscript:18,ul:19,underline:20,image:21,link:22,unlink:23,close:24,arrow:26,upload:27,table:28,AnswerSelect:29,ImageArea:31,media:32}}),nicEditors={nicPlugins:[],editors:[],registerPlugin:function(a,b){this.nicPlugins.push({p:a,o:b})},allTextAreas:function(a){for(var b=document.getElementsByTagName("textarea"),c=0;c<b.length;c++)nicEditors.editors.push((new nicEditor(a)).panelInstance(b[c]));
return nicEditors.editors},findEditor:function(a){for(var b=nicEditors.editors,c=0;c<b.length;c++)if(b[c].instanceById(a))return b[c].instanceById(a)}},nicEditor=bkClass.extend({construct:function(a){this.options=new nicEditorConfig;bkExtend(this.options,a);this.nicInstances=[];this.loadedPlugins=[];this.CustomConfig={oFileManager:{quickUploadDir:{},browseDir:{}}};if(window._ROOT_URL==null)window._ROOT_URL="";for(var b=nicEditors.nicPlugins,c=0;c<b.length;c++)this.loadedPlugins.push(new b[c].p(this,
b[c].o));ObjAllExtend(this.CustomConfig,a.CustomConfig);window.CustomConfig=this.CustomConfig;nicEditors.editors.push(this)},panelInstance:function(a,b){b=b||{};b.hasPanel=true;var c=$BK(a);if(c){a=this.checkReplace(c);this.panelElm=(new bkElement("DIV")).setStyle({width:a.getStyle("width")||a.clientWidth}).appendBefore(a);this.setPanel(this.panelElm);return this.addInstance(a,b)}},checkReplace:function(a){var b=nicEditors.findEditor(a);if(b){b.removeInstance(a);b.removePanel()}return a},addInstance:function(a,
b){a=this.checkReplace($BK(a));this.nicInstances.push(a.contentEditable||window.opera?new nicEditorInstance(a,b,this):new nicEditorIFrameInstance(a,b,this));return this},removeInstance:function(a){for(var a=$BK(a),b=this.nicInstances,c=0;c<b.length;c++)if(b[c].e==a){b[c].remove();this.nicInstances.splice(c,1)}},removePanel:function(){if(this.nicPanel){this.nicPanel.remove();this.nicPanel=null}},instanceById:function(a){for(var a=$BK(a),b=this.nicInstances,c=0;c<b.length;c++)if(b[c].e==a)return b[c]},
setPanel:function(a){this.nicPanel=new nicEditorPanel($BK(a),this.options,this);this.fireEvent("panel",this.nicPanel);return this},nicCommand:function(a,b){this.selectedInstance&&this.selectedInstance.nicCommand(a,b)},getIcon:function(a,b){var c=this.options.iconList[a],d=b.iconFiles?b.iconFiles[a]:"";return{backgroundImage:"url('"+(c?this.options.iconsPath:d)+"')",backgroundPosition:(c?(c-1)*-18:0)+"px 0px"}},selectCheck:function(a,b){do if(b.className&&b.className.indexOf("nicEdit")!=-1)return false;
while(b=b.parentNode);this.fireEvent("blur",this.selectedInstance,b);this.lastSelectedInstance=this.selectedInstance;this.selectedInstance=null;return false},Text_HTML:function(a){var b=document.createElement("div");typeof b.innerText=="undefined"?b.textContent=a:b.innerText=a;return b.innerHTML.replace(/\"/ig,"&quot;").replace(/\'/ig,"&#039;").replace(/<BR>/ig,"")},HTML_Text:function(a){var b=document.createElement("div");b.innerHTML=a;return typeof b.innerText=="undefined"?b.textContent:b.innerText},
setSize:function(a,b){var c;if(b)for(var d=this.nicInstances,b=$BK(b),e=0;e<d.length;e++){if(d[e].e===b){b=d[e].elm;break}}else b=this.elm;d=b.parentNode.previousSibling;do if(d.tagName==="DIV"){c=b.parentNode;break}while(d=d.previousSibling);if(a.width!=null){c.style.width=d.style.width=a.width;b.style.width=(c.clientWidth-10>0?c.clientWidth-10:0)+"px"}if(a.height!=null){c.style.maxHeight=c.style.height=a.height;c.style.maxHeight=c.style.height=(c.clientHeight-d.offsetHeight>0?c.clientHeight-d.offsetHeight:
0)+"px";b.style.minHeight=b.style.height=(c.clientHeight-12>0?c.clientHeight-12:0)+"px"}b.style.overflow="visible";c.style.overflowY="scroll"}}),nicEditor=nicEditor.extend(bkEvent),nicEditorInstance=bkClass.extend({isSelected:!1,construct:function(a,b,c){this.ne=c;this.elm=this.e=a;this.options=b||{};newX=a.getStyle("width")||a.clientWidth;newY=parseInt(a.getStyle("height"))||a.clientHeight;this.initialHeight=newY-8;if((c=a.nodeName.toLowerCase()=="textarea")||this.options.hasPanel){var b=bkLib.isMSIE&&
!(typeof document.body.style.maxHeight!="undefined"&&document.compatMode=="CSS1Compat"),d={width:newX,border:"1px solid #ccc",borderTop:0,overflowY:"auto",overflowX:"hidden"};d.maxHeight=this.ne.options.maxHeight?this.ne.options.maxHeight+"px":null;this.editorContain=(new bkElement("DIV")).setStyle(d).appendBefore(a);b&&this.ne.options.maxHeight&&this.editorContain.style.setExpression("height","this.scrollHeight > "+this.ne.options.maxHeight+' ? "'+this.ne.options.maxHeight+'px" : "auto"');var d=
"#"+a.id+"_Editer { padding:5px; white-space:normal; word-break:break-all; }                    #"+a.id+"_Editer p{ margin:0px; padding:0px;}                    #"+a.id+"_Editer ul { list-style-type:disc; padding-left:40px; margin-left:2em;}                    #"+a.id+"_Editer ol { list-style-type:decimal; padding-left:0px; margin-left:2em;}                    #"+a.id+"_Editer ol li { list-style:decimal outside none;}                    #"+a.id+"_Editer ul li { list-style:disc outside none;}",e=new bkElement("style");
e.setAttribute("type","text/css");this.editorContain.appendChild(e);try{bkLib.isMSIE?e.styleSheet.cssText=d:e.appendChild(document.createTextNode(d))}catch(f){}a.style.display="block";d=(new bkElement("DIV")).setStyle({width:a.clientWidth-10,margin:"1px 0px",minHeight:newY-15+"px"}).addClass("main").appendTo(this.editorContain);d.id=a.id+"_Editer";d.offsetHeight>this.editorContain.clientHeight&&bkLib.isMSIE?d.setStyle({width:d.clientWidth-18}):bkLib.isMSIE&&d.setStyle({width:a.clientWidth});a.setStyle({display:"none"});
d.innerHTML=a.innerHTML;if(c){d.setContent(a.value);this.copyElm=a;(a=a.parentTag("FORM"))&&bkLib.addEvent(a,"submit",this.saveContent.closure(this))}d.setStyle(b?{height:newY+"px"}:{overflow:"hidden"});this.elm=d}this.ne.addEvent("blur",this.blur.closure(this));this.init();this.blur()},init:function(){this.ne.elm=this.elm;this.elm.setAttribute("contentEditable","true");this.ne.panelElm.addEvent("mouseover",this.focus.closure(this));this.ne.panelElm.addEvent("mouseover",this.selected.closure(this));
this.getContent().replace(/(^\s*)|(\s*$)/g,"")==""&&this.setContent("<p>&nbsp;</p>");for(var a=this.elm.getElementsByTagName("img"),b=0,c=a.length;b<c;b++)if(a[b].getAttribute("AnswerType")=="textbox"||a[b].getAttribute("AnswerType")=="select")parseInt(a[b].getAttribute("Num"))>this.ne.CustomConfig.AnswerSelect.AnswerNum&&(this.ne.CustomConfig.AnswerSelect.AnswerNum=parseInt(a[b].getAttribute("Num")));this.instanceDoc=document.defaultView;this.elm.addEvent("mouseover",this.focus.closure(this)).addEvent("mouseover",
this.selected.closure(this)).addEvent("click",this.MouseClick.closure(this)).addEvent("keypress",this.keyDown.closureListener(this)).addEvent("paste",this.keyDown.closureListener(this)).addEvent("blur",this.blur.closure(this)).addEvent("keyup",this.selected.closure(this));this.ne.elm.addEvent("mouseup",function(){if(window.CustomConfig.ImageArea.mousedownObj!=null){var a=window.CustomConfig.ImageArea.mousedownObj,b=a.getElementsByTagName("div")[0];if(b){b.style.width=a.offsetWidth;b.style.height=
a.offsetHeight}}});this.ne.fireEvent("add",this)},remove:function(){this.saveContent();if(this.copyElm||this.options.hasPanel){this.editorContain.remove();this.e.setStyle({display:"block"});this.ne.removePanel()}this.disable();this.ne.fireEvent("remove",this)},disable:function(){this.elm.setAttribute("contentEditable","false")},getSel:function(){return window.getSelection?window.getSelection():document.selection},getRng:function(){var a=this.getSel();return!a?null:a.rangeCount>0?a.getRangeAt(0):a.createRange()},
selRng:function(a,b){if(window.getSelection){b.removeAllRanges();b.addRange(a)}else a.select()},selElm:function(){var a=this.getRng();if(a.startContainer){var b=a.startContainer;if(a.cloneContents().childNodes.length==1)for(var c=0;c<b.childNodes.length;c++){var d=b.childNodes[c].ownerDocument.createRange();d.selectNode(b.childNodes[c]);if(a.compareBoundaryPoints(Range.START_TO_START,d)!=1&&a.compareBoundaryPoints(Range.END_TO_END,d)!=-1)return $BK(b.childNodes[c])}return $BK(b)}return $BK(this.getSel().type==
"Control"?a.item(0):a.parentElement())},saveRng:function(){this.savedRange=this.getRng();this.savedSel=this.getSel()},restoreRng:function(){this.savedRange&&this.selRng(this.savedRange,this.savedSel)},MouseClick:function(a,b){this.ne.fireEvent("click",this.ne.selectedInstance,b)},keyDown:function(a,b){a.ctrlKey&&this.ne.fireEvent("key",this,a);this.ne.fireEvent("click",this.ne.selectedInstance,b);try{var c=new bkElement("div");bkLib.isMSIE?c.innerHTML=this.ne.selectedInstance.getRng().htmlText:c.appendChild(this.ne.selectedInstance.getRng().cloneContents());
if(this.elm.innerHTML.search(/^(<br>)+$/i)>-1||this.elm.innerHTML==""){this.elm.innerHTML="<p>&nbsp;</p>";this.elm.blur();this.elm.focus()}if(this.elm.innerHTML.search(/^<p>&nbsp;<\/p>$/i)>-1||this.elm.innerHTML==c.innerHTML&&a.keyCode!=13&&a.keyCode!=8&&a.keyCode!=46&&!(a.ctrlKey&&a.which==120))if(bkLib.isMSIE){this.ne.selectedInstance.getRng().findText("&nbsp;");this.ne.selectedInstance.getRng().select()}else{if(bkLib.isFirefox){this.elm.innerHTML="<p>&nbsp;</p>";b=this.elm.getElementsByTagName("p")[0];
this.ne.selectedInstance.getRng().selectNodeContents(b)}}else if(!bkLib.isMSIE&&a.keyCode==13&&!a.shiftKey&&this.elm.innerHTML!=c.innerHTML){b=new bkElement("p");this.ne.selectedInstance.getRng().insertNode(b);b.parentNode!=this.elm?b.parentNode.removeChild(b):this.ne.selectedInstance.getRng().selectNodeContents(b)}}catch(d){bkLib.isMSIE?a.returnValue=false:a.preventDefault()}},selected:function(a,b){b||(b=this.selElm());if(!a.ctrlKey){var c=this.ne.selectedInstance;if(c!=this){c&&this.ne.fireEvent("blur",
c,b);this.ne.selectedInstance=this;this.ne.fireEvent("focus",c,b)}this.ne.fireEvent("selected",c,b);this.isFocused=true;this.elm.addClass("selected")}return false},blur:function(){this.isFocused=false;this.elm.removeClass("selected");this.e.innerHTML=this.ne.Text_HTML(this.contentProcessing(this.cleanWord(this.getContent())))},contentProcessing:function(a,b){var c=document.createElement("div");c.innerHTML=a;b==null&&(b=c);for(var d=c.childNodes,e=d.length-1;e>=0;e--)if(d[e].getAttribute)if(d[e].tagName===
"SCRIPT")c.removeChild(d[e]);else{if(d[e].childNodes.length>0)if(d[e].tagName!="TABLE")try{d[e].innerHTML=this.contentProcessing(d[e].innerHTML,b)}catch(f){}else for(var g=d[e].rows,k=0;k<g.length;k++)for(var m=d[e].rows[k].cells,l=0;l<m.length;l++)if(m[l].childNodes.length)m[l].innerHTML=this.contentProcessing(m[l].innerHTML,b);if(d[e].getAttribute("AnswerType"))if(d[e].getAttribute("eval")){g=d[e].getAttribute("eval").replace(/\bthis\b/g,"temp_obj_arr[i]").replace(/\bthisObj\b/g,"this").replace(/\bthisOpObj\b/g,
"oP").replace(/\bthisRootObj\b/g,"rootObj");if(typeof d[e]=="object"||d[e].tagName=="OBJECT"||d[e].tagName=="EMBED")try{d[e].removeAttribute("eval");d[e].removeAttribute("onmousedown");d[e].removeAttribute("AnswerType")}catch(h){alert(h)}eval(g)}else d[e].outerHTML="["+d[e].getAttribute("AnswerType")+"]"+d[e].getAttribute("Num")+"[/"+d[e].getAttribute("AnswerType")+"]"}return c.innerHTML},cleanWord:function(a){a=a.replace(/<o:p>\s*<\/o:p>/g,"").replace(/<o:p>[\s\S]*?<\/o:p>/g,"&nbsp;");a=a.replace(/\s*mso-[^:]+:[^;"]+;?/gi,
"");a=a.replace(/\s*MARGIN: 0cm 0cm 0pt\s*;/gi,"").replace(/\s*MARGIN: 0cm 0cm 0pt\s*"/gi,'"').replace(/\s*TEXT-INDENT: 0cm\s*;/gi,"").replace(/\s*TEXT-INDENT: 0cm\s*"/gi,'"').replace(/\s*PAGE-BREAK-BEFORE: [^\s;]+;?"/gi,'"').replace(/\s*FONT-VARIANT: [^\s;]+;?"/gi,'"').replace(/\s*tab-stops:[^;"]*;?/gi,"").replace(/\s*tab-stops:[^"]*/gi,"");a=a.replace(/<(\w[^>]*) class=([^ |>]*)([^>]*)/gi,"<$1$3");a=a.replace(/<STYLE[^>]*>[\s\S]*?<\/STYLE[^>]*>/gi,"").replace(/<(?:META|LINK)[^>]*>\s*/gi,"");a=a.replace(/\s*style="\s*"/gi,
"").replace(/<SPAN\s*[^>]*>\s*&nbsp;\s*<\/SPAN>/gi,"&nbsp;").replace(/<SPAN\s*[^>]*><\/SPAN>/gi,"");a=a.replace(/<(\w[^>]*) lang=([^ |>]*)([^>]*)/gi,"<$1$3").replace(/<SPAN\s*>([\s\S]*?)<\/SPAN>/gi,"$1").replace(/<FONT\s*>([\s\S]*?)<\/FONT>/gi,"$1");a=a.replace(/<\\?\?xml[^>]*>/gi,"");a=a.replace(/<w:[^>]*>[\s\S]*?<\/w:[^>]*>/gi,"");a=a.replace(/<\/?\w+:[^>]*>/gi,"");a=a.replace(/<\!--[\s\S]*?--\>/g,"").replace(/<(U|I|STRIKE)>&nbsp;<\/\1>/g,"&nbsp;").replace(/<H\d>\s*<\/H\d>/gi,"");a=a.replace(/<(\w+)[^>]*\sstyle="[^"]*DISPLAY\s?:\s?none[\s\S]*?<\/\1>/ig,
"");a=a.replace(/<(\w[^>]*) language=([^ |>]*)([^>]*)/gi,"<$1$3");a=a.replace(/<(\w[^>]*) onmouseover="([^\"]*)"([^>]*)/gi,"<$1$3").replace(/<(\w[^>]*) onmouseout="([^\"]*)"([^>]*)/gi,"<$1$3");a=a.replace(/<H(\d)([^>]*)>/gi,"<h$1>");return a=a.replace(/<(H\d)><FONT[^>]*>([\s\S]*?)<\/FONT><\/\1>/gi,"<$1>$2</$1>").replace(/<(H\d)><EM>([\s\S]*?)<\/EM><\/\1>/gi,"<$1>$2</$1>")},focus:function(){if(document.activeElement!=this.elm){var a=this.editorContain.scrollTop;this.elm.focus();this.editorContain.scrollTop=
a}},saveContent:function(){},getElm:function(){return this.elm},getContent:function(){this.content=this.getElm().innerHTML;this.ne.fireEvent("get",this);return this.content},setContent:function(a){this.content=a;this.ne.fireEvent("set",this);this.elm.innerHTML=this.content},nicCommand:function(a,b){document.execCommand(a,false,b)}}),nicEditorIFrameInstance=nicEditorInstance.extend({savedStyles:[],init:function(){var a=this.elm.innerHTML.replace(/^\s+|\s+$/g,"");this.elm.innerHTML="";!a&&(a="<br />");
this.initialContent=a;this.elmFrame=(new bkElement("iframe")).setAttributes({src:"javascript:;",frameBorder:0,allowTransparency:"true",scrolling:"no"}).setStyle({height:"100px",width:"100%"}).addClass("frame").appendTo(this.elm);this.copyElm&&this.elmFrame.setStyle({width:this.elm.offsetWidth-4+"px"});a=["font-size","font-family","font-weight","color"];for(itm in a)this.savedStyles[bkLib.camelize(itm)]=this.elm.getStyle(itm);setTimeout(this.initFrame.closure(this),50)},disable:function(){this.elm.innerHTML=
this.getContent()},initFrame:function(){var a=$BK(this.elmFrame.contentWindow.document);a.designMode="on";a.open();var b=this.ne.options.externalCSS;a.write("<html><head>"+(b?'<link href="'+b+'" rel="stylesheet" type="text/css" />':"")+'</head><body id="nicEditContent" style="margin: 0 !important; background-color: transparent !important;">'+this.initialContent+"</body></html>");a.close();this.frameDoc=a;this.frameWin=$BK(this.elmFrame.contentWindow);this.frameContent=$BK(this.frameWin.document.body).setStyle(this.savedStyles);
this.instanceDoc=this.frameWin.document.defaultView;this.heightUpdate();this.frameDoc.addEvent("mousedown",this.selected.closureListener(this)).addEvent("keyup",this.heightUpdate.closureListener(this)).addEvent("keydown",this.keyDown.closureListener(this)).addEvent("keyup",this.selected.closure(this));this.ne.fireEvent("add",this)},getElm:function(){return this.frameContent},setContent:function(a){this.content=a;this.ne.fireEvent("set",this);this.frameContent.innerHTML=this.content;this.heightUpdate()},
getSel:function(){return this.frameWin?this.frameWin.getSelection():this.frameDoc.selection},heightUpdate:function(){this.elmFrame.style.height=Math.max(this.frameContent.offsetHeight,this.initialHeight)+"px"},nicCommand:function(a,b){this.frameDoc.execCommand(a,false,b);setTimeout(this.heightUpdate.closure(this),100)}}),nicEditorPanel=bkClass.extend({construct:function(a,b,c){this.elm=a;this.options=b;this.ne=c;this.panelButtons=[];this.buttonList=bkExtend([],this.ne.options.buttonList);this.panelContain=
(new bkElement("DIV")).setStyle({overflow:"hidden",width:"100%",border:"1px solid #cccccc",backgroundColor:"#efefef"}).addClass("panelContain");this.panelElm=(new bkElement("DIV")).setStyle({margin:"2px",marginTop:"0px",zoom:1,overflow:"hidden"}).addClass("panel").appendTo(this.panelContain);this.panelContain.appendTo(a);b=this.ne.options;c=b.buttons;for(button in c)this.addButton(button,b,true);this.reorder();a.noSelect()},addButton:function(a,b){var c=b.buttons[a],c=c.type?eval("(typeof("+c.type+
') == "undefined") ? null : '+c.type+";"):nicEditorButton,d=bkLib.inArray(this.buttonList,a);if(c&&(d||this.ne.options.fullPanel)){this.panelButtons.push(new c(this.panelElm,a,b,this.ne));d||this.buttonList.push(a)}},findButton:function(a){for(var b=0;b<this.panelButtons.length;b++)if(this.panelButtons[b].name==a)return this.panelButtons[b]},reorder:function(){for(var a=this.buttonList,b=0;b<a.length;b++){var c=this.findButton(a[b]);c&&this.panelElm.appendChild(c.margin)}},remove:function(){this.elm.remove()}}),
nicEditorButton=bkClass.extend({construct:function(a,b,c,d){this.options=c.buttons[b];this.name=b;this.ne=d;this.elm=a;this.margin=(new bkElement("DIV")).setStyle({"float":"left",marginTop:"2px"}).appendTo(a);this.contain=(new bkElement("DIV")).setStyle({width:"20px",height:"20px"}).addClass("buttonContain").appendTo(this.margin);this.border=(new bkElement("DIV")).setStyle({backgroundColor:"#efefef",border:"1px solid #efefef"}).appendTo(this.contain);this.button=(new bkElement("DIV")).setStyle({width:"18px",
height:"18px",overflow:"hidden",zoom:1,cursor:"pointer"}).addClass("button").setStyle(this.ne.getIcon(b,c)).appendTo(this.border);this.button.addEvent("mouseover",this.hoverOn.closure(this)).addEvent("mouseout",this.hoverOff.closure(this)).addEvent("mousedown",this.mouseClick.closure(this)).noSelect();if(!window.opera)this.button.onmousedown=this.button.onclick=bkLib.cancelEvent;d.addEvent("selected",this.enable.closure(this)).addEvent("key",this.key.closure(this));this.disable();this.init()},init:function(){},
hide:function(){this.contain.setStyle({display:"none"})},updateState:function(){this.isDisabled?this.setBg():this.isHover?this.setBg("hover"):this.isActive?this.setBg("active"):this.setBg()},setBg:function(a){switch(a){case "hover":var b={border:"1px solid #666",backgroundColor:"#ddd"};break;case "active":b={border:"1px solid #666",backgroundColor:"#ccc"};break;default:b={border:"1px solid #efefef",backgroundColor:"#efefef"}}this.border.setStyle(b).addClass("button-"+a)},checkNodes:function(a){var b=
a;do if((!b.getAttribute||b.getAttribute&&b.getAttribute("AnswerType")==this.options.AnswerType)&&this.options.tags&&bkLib.inArray(this.options.tags,b.nodeName)){this.activate();return true}while(b=b.parentNode&&b.className!="nicEdit");for(b=$BK(a);b.nodeType==3;)b=$BK(b.parentNode);if(this.options.css)for(itm in this.options.css)if(b.getStyle(itm,this.ne.selectedInstance.instanceDoc)==this.options.css[itm]){this.activate();return true}this.deactivate();return false},activate:function(){if(!this.isDisabled){this.isActive=
true;this.updateState();this.ne.fireEvent("buttonActivate",this)}},deactivate:function(){this.isActive=false;this.updateState();this.isDisabled||this.ne.fireEvent("buttonDeactivate",this)},enable:function(a,b){this.isDisabled=false;this.contain.setStyle({opacity:1}).addClass("buttonEnabled");this.updateState();this.checkNodes(b)},disable:function(){this.isDisabled=false;this.contain.setStyle({opacity:1}).removeClass("buttonEnabled");this.updateState()},toggleActive:function(){this.isActive?this.deactivate():
this.activate()},hoverOn:function(){if(!this.isDisabled){this.isHover=true;this.updateState();this.ne.fireEvent("buttonOver",this)}},hoverOff:function(){this.isHover=false;this.updateState();this.ne.fireEvent("buttonOut",this)},mouseClick:function(){if(this.options.command){this.ne.nicCommand(this.options.command,this.options.commandArgs);this.options.noActive||this.toggleActive()}this.ne.fireEvent("buttonClick",this)},key:function(a,b){if(this.options.key&&b.ctrlKey&&String.fromCharCode(b.keyCode||
b.charCode).toLowerCase()==this.options.key){this.mouseClick();b.preventDefault&&b.preventDefault()}}}),nicPlugin=bkClass.extend({construct:function(a,b){this.options=b;this.ne=a;ObjAllExtend(this.ne.CustomConfig,b.CustomConfig);this.ne.addEvent("panel",this.loadPanel.closure(this));this.init()},loadPanel:function(a){var b=this.options.buttons,c;for(c in b)a.addButton(c,this.options);a.reorder()},init:function(){}}),nicPaneOptions={},nicEditorPane=bkClass.extend({construct:function(a,b,c,d){this.ne=
b;this.elm=a;this.pos=a.pos();this.contain=(new bkElement("div")).setStyle({zIndex:"99999",overflow:"hidden",position:"absolute",left:this.pos[0]+"px",top:this.pos[1]+"px"});this.pane=(new bkElement("div")).setStyle({fontSize:"12px",border:"1px solid #ccc",overflow:"hidden",padding:"4px",textAlign:"left",backgroundColor:"#ffffc9"}).addClass("pane").setStyle(c).appendTo(this.contain);if(d&&!d.options.noClose)this.close=(new bkElement("div")).setStyle({"float":"right",height:"16px",width:"16px",cursor:"pointer"}).setStyle(this.ne.getIcon("close",
nicPaneOptions)).addEvent("mousedown",d.removePane.closure(this)).appendTo(this.pane);this.contain.noSelect().appendTo(document.body);this.position();this.init()},init:function(){},position:function(){if(this.ne.nicPanel){var a=this.ne.nicPanel.elm,a=a.pos()[0]+parseInt(a.clientWidth)-(parseInt(this.pane.clientWidth)+8);a<this.pos[0]&&this.contain.setStyle({left:a+"px"})}},toggle:function(){this.isVisible=!this.isVisible;this.contain.setStyle({display:this.isVisible?"block":"none"})},remove:function(){if(this.contain){this.contain.remove();
this.contain=null}},append:function(a){a.appendTo(this.pane)},setContent:function(a){this.pane.setContent(a)}}),nicEditorAdvancedButton=nicEditorButton.extend({init:function(){this.ne.addEvent("click",this.removePane.closure(this)).addEvent("blur",this.removePane.closure(this))},mouseClick:function(){if(!this.isDisabled&&this.ne.selectedInstance)if(this.pane&&this.pane.pane)this.removePane();else{this.pane=new nicEditorPane(this.contain,this.ne,{width:this.width||"270px",backgroundColor:"#fff"},this);
this.addPane();this.ne.selectedInstance.saveRng()}},addForm:function(a,b){this.form=(new bkElement("form")).addEvent("submit",this.submit.closureListener(this));this.pane.append(this.form);this.inputs={};for(itm in a){var c=a[itm],d="",e={overflow:"hidden",clear:"both"};bkExtend(e,a[itm].p_css);b&&(d=b.getAttribute(itm));d||(d=c.value||"");var f=a[itm].type;if(f=="title")(new bkElement("div")).setContent(c.txt).setStyle({fontSize:"14px",fontWeight:"bold",padding:"0px",margin:"2px 0"}).setStyle(e).appendTo(this.form);
else{var g=(new bkElement("div")).setStyle(e).appendTo(this.form);if(c.txt){e={margin:"2px 2px",fontSize:"13px",width:"60px",lineHeight:"20px",textAlign:"left","float":"left",display:"inline"};bkExtend(e,a[itm].s_css);(new bkElement("label")).setAttributes({"for":itm}).setContent(c.txt).setStyle(e).appendTo(g)}switch(f){case "text":this.inputs[itm]=(new bkElement("input")).setAttributes({id:itm,value:d,type:"text"}).setStyle({margin:"2px 0",fontSize:"13px","float":"left",height:"20px",border:"1px solid #ccc",
overflow:"hidden"}).setStyle(c.style).appendTo(g);break;case "select":this.inputs[itm]=(new bkElement("select")).setAttributes({id:itm}).setStyle({border:"1px solid #ccc","float":"left",margin:"2px 0"}).appendTo(g);for(opt in c.options)(new bkElement("option")).setAttributes({value:opt,selected:opt==d?"selected":""}).setContent(c.options[opt]).appendTo(this.inputs[itm]);break;case "checkbox":this.inputs[itm]=(new bkElement("input")).setAttributes({id:itm,value:d,type:"checkbox",checked:a[itm].checked}).setStyle({border:"0px",
overflow:"hidden"}).setStyle(c.style).appendTo(g);break;case "content":this.inputs[itm]=(new bkElement("textarea")).setAttributes({id:itm}).setStyle({border:"1px solid #ccc","float":"left"}).setStyle(c.style).appendTo(g);this.inputs[itm].value=d}}}(new bkElement("input")).setAttributes({type:"submit"}).setStyle({backgroundColor:"#efefef",border:"1px solid #ccc",margin:"3px 0","float":"left",clear:"both"}).appendTo(this.form);this.form.onsubmit=bkLib.cancelEvent},submit:function(){},findElm:function(a,
b,c){for(var a=this.ne.selectedInstance.getElm().getElementsByTagName(a),d=0;d<a.length;d++)if(a[d].getAttribute(b)==c)return $BK(a[d])},removePane:function(){if(this.pane){this.pane.remove();this.pane=null;this.ne.selectedInstance.restoreRng()}}}),nicButtonTips=bkClass.extend({construct:function(a){this.ne=a;a.addEvent("buttonOver",this.show.closure(this)).addEvent("buttonOut",this.hide.closure(this))},show:function(a){this.timer=setTimeout(this.create.closure(this,a),400)},create:function(a){this.timer=
null;if(!this.pane){this.pane=new nicEditorPane(a.button,this.ne,{fontSize:"12px",marginTop:"5px"});this.pane.setContent(a.options.name)}},hide:function(){this.timer&&clearTimeout(this.timer);if(this.pane)this.pane=this.pane.remove()}});nicEditors.registerPlugin(nicButtonTips);
var nicSelectOptions={buttons:{fontSize:{name:__("\u5b57\u4f53\u5927\u5c0f"),type:"nicEditorFontSizeSelect",command:"fontsize"},fontFamily:{name:__("\u9009\u62e9\u5b57\u4f53"),type:"nicEditorFontFamilySelect",command:"fontname"},fontFormat:{name:__("\u5b57\u4f53\u683c\u5f0f"),type:"nicEditorFontFormatSelect",command:"formatBlock"}}},nicEditorSelect=bkClass.extend({construct:function(a,b,c,d){this.options=c.buttons[b];this.elm=a;this.ne=d;this.name=b;this.selOptions=[];this.margin=(new bkElement("div")).setStyle({"float":"left",
margin:"2px 1px 0 1px"}).appendTo(this.elm);this.contain=(new bkElement("div")).setStyle({width:"90px",height:"20px",cursor:"pointer",overflow:"hidden"}).addClass("selectContain").addEvent("click",this.toggle.closure(this)).appendTo(this.margin);this.items=(new bkElement("div")).setStyle({overflow:"hidden",zoom:1,border:"1px solid #ccc",paddingLeft:"3px",backgroundColor:"#fff"}).appendTo(this.contain);this.control=(new bkElement("div")).setStyle({overflow:"hidden","float":"right",height:"18px",width:"16px"}).addClass("selectControl").setStyle(this.ne.getIcon("arrow",
c)).appendTo(this.items);this.txt=(new bkElement("div")).setStyle({overflow:"hidden","float":"left",width:"66px",height:"14px",lineHeight:"14px",marginTop:"1px",fontFamily:"'\u5b8b\u4f53','Arial'",textAlign:"center",fontSize:"12px"}).addClass("selectTxt").appendTo(this.items);if(!window.opera)this.contain.onmousedown=this.control.onmousedown=this.txt.onmousedown=bkLib.cancelEvent;this.margin.noSelect();this.ne.addEvent("selected",this.enable.closure(this));this.disable();this.init()},disable:function(){this.isDisabled=
true;this.close();this.contain.setStyle({opacity:1})},enable:function(){this.isDisabled=false;this.ne.elm.addEvent("click",this.close.closure(this)).addEvent("keypress",this.close.closureListener(this));this.contain.setStyle({opacity:1})},setDisplay:function(a){this.txt.setContent(a)},toggle:function(){this.isDisabled||(this.pane?this.close():this.open())},open:function(){this.pane=new nicEditorPane(this.items,this.ne,{width:"88px",padding:"0px",borderTop:0,borderLeft:"1px solid #ccc",borderRight:"1px solid #ccc",
borderBottom:"0px",backgroundColor:"#fff"});for(var a=0;a<this.selOptions.length;a++){var b=this.selOptions[a],c=(new bkElement("div")).setStyle({overflow:"hidden",borderBottom:"1px solid #ccc",width:"88px",textAlign:"left",overflow:"hidden",cursor:"pointer"}),d=(new bkElement("div")).setStyle({padding:"0px 4px"}).setContent(b[1]).appendTo(c).noSelect();d.addEvent("click",this.update.closure(this,b[0])).addEvent("mouseover",this.over.closure(this,d)).addEvent("mouseout",this.out.closure(this,d)).setAttributes("id",
b[0]);this.pane.append(c);if(!window.opera)d.onmousedown=bkLib.cancelEvent}},close:function(){if(this.pane)this.pane=this.pane.remove()},over:function(a){a.setStyle({backgroundColor:"#ccc"})},out:function(a){a.setStyle({backgroundColor:"#fff"})},add:function(a,b){this.selOptions.push([a,b])},update:function(a){if(bkLib.isMSIE&&this.options.command=="formatBlock"){a=/^<(.*)>$/.exec(a)[1];a="<"+a+">"+this.ne.selectedInstance.getRng().htmlText+"</"+a+">";this.ne.selectedInstance.getRng().pasteHTML(a)}else this.ne.nicCommand(this.options.command,
a);this.close()}}),nicEditorFontSizeSelect=nicEditorSelect.extend({sel:{1:"1\u53f7\u5b57",2:"2\u53f7\u5b57",3:"3\u53f7\u5b57",4:"4\u53f7\u5b57",5:"5\u53f7\u5b57",6:"6\u53f7\u5b57"},init:function(){this.setDisplay("\u5b57\u4f53\u5927\u5c0f");for(itm in this.sel)this.add(itm,'<font size="'+itm+'">'+this.sel[itm]+"</font>")}}),nicEditorFontFamilySelect=nicEditorSelect.extend({sel:{"\u5b8b\u4f53":"\u5b8b\u4f53","\u6977\u4f53_gb2312":"\u6977\u4f53","\u96b6\u4e66":"\u96b6\u4e66","\u5e7c\u5706":"\u5e7c\u5706",
"\u9ed1\u4f53":"\u9ed1\u4f53",arial:"Arial","comic sans ms":"Comic Sans","courier new":"Courier New",georgia:"Georgia",helvetica:"Helvetica",impact:"Impact","times new roman":"Times","trebuchet ms":"Trebuchet",verdana:"Verdana"},init:function(){this.setDisplay("\u9009\u62e9\u5b57\u4f53");for(itm in this.sel)this.add(itm,'<font face="'+itm+'">'+this.sel[itm]+"</font>")}}),nicEditorFontFormatSelect=nicEditorSelect.extend({sel:{p:"\u6bb5\u843d",pre:"\u4ee3\u7801",h6:"\u6807\u9898\u516d",h5:"\u6807\u9898\u4e94",
h4:"\u6807\u9898\u56db",h3:"\u6807\u9898\u4e09",h2:"\u6807\u9898\u4e8c",h1:"\u6807\u9898\u4e00"},init:function(){this.setDisplay("\u5b57\u4f53\u683c\u5f0f");for(itm in this.sel){var a=itm.toUpperCase();this.add("<"+a+">","<"+itm+' style="padding: 0px; margin: 0px;">'+this.sel[itm]+"</"+a+">")}}});nicEditors.registerPlugin(nicPlugin,nicSelectOptions);
var nicLinkOptions={buttons:{link:{name:"\u589e\u52a0\u94fe\u63a5/\u9644\u4ef6",type:"nicLinkButton",tags:["A"]},unlink:{name:"\u5220\u9664\u94fe\u63a5",command:"unlink",noActive:!0}}},nicLinkButton=nicEditorAdvancedButton.extend({width:"220px",addPane:function(){var a=(new Date).getTime();this.att=this.ne.selectedInstance.selElm().parentTag("A");var b="http://";if(this.att.getAttribute){b=this.att.href;this.att.getAttribute("delurl")&&(b=b.substr(b.indexOf("/",7)+this.att.getAttribute("delurl").length))}this.addForm({"":{type:"title",
txt:"\u6dfb\u52a0\u94fe\u63a5/\u9644\u4ef6"},title:{type:"text",txt:"\u6807\u9898",value:"Link",style:{width:"150px"}},hrefInput:{type:"text",txt:"\u5730\u5740",value:b,style:{width:"150px"}},target:{type:"select",txt:"\u6253\u5f00\u65b9\u5f0f",options:{"":"\u9ed8\u8ba4",_blank:"\u65b0\u7a97\u53e3"},style:{width:"100px"},s_css:{width:"60px"},p_css:{"float":"left"}},alt1:{type:"title",txt:'<iframe id="oEditUploadify'+a+'" frameborder="0" style="width:25px; height:19px; border:0px; float:right; margin-top:-2px;" src="'+
_ROOT_URL+oFileManagerMainDir+'/include/uploadify/iframeIndex.php"></iframe><font style="font-weight:normal; font-size:12px; cursor:pointer; margin-left:5px; float:right;" onclick="selectFile(\'hrefInput\',null,\''+this.ne.CustomConfig.oFileManager.browseDir.attachment+"');\">\u9009\u62e9\u6587\u4ef6</font>",p_css:{"float":"right",textAlign:"right",height:"15px",clear:"none"}}},this.att);document.getElementById("oEditUploadify"+a).contentWindow.config={uploadifyId:"uploadify",onAllCompleteFun:function(a){document.getElementById("hrefInput").value=
a},swfConfig:{folder:this.ne.CustomConfig.oFileManager.quickUploadDir.attachment}}},submit:function(){var a=this.inputs.hrefInput.value,b="";if(a.replace(/(^\s*)|(\s*$)/g,"")==""){alert("\u8bf7\u8f93\u5165\u6587\u4ef6\u5730\u5740\uff01");return false}if(a.search(/^\w+:\/\//i)){b='delUrl="'+window._ROOT_URL+'"';a=window._ROOT_URL+a}/((?!\/).)*$/.exec(a);this.removePane();if(!this.att){this.ne.nicCommand("createlink","javascript:nicTemp();");this.att=this.findElm("A","href","javascript:nicTemp();")}if(this.att){this.att.setAttributes({href:a,
title:this.inputs.title.value,target:this.inputs.target.options[this.inputs.target.selectedIndex].value});b&&this.att.setAttribute("delUrl",window._ROOT_URL)}else{if(!this.inputs.title.value)return false;if(bkLib.isMSIE&&bkLib.version<9){a='<a href="'+a+'" title="'+this.inputs.title.value+'" target="'+this.inputs.target.options[this.inputs.target.selectedIndex].value+'" '+b+">"+this.inputs.title.value+"</a>";this.ne.selectedInstance.getRng().pasteHTML(a)}else{a=(new bkElement("a")).setAttributes({href:a,
title:this.inputs.title.value,target:this.inputs.target.options[this.inputs.target.selectedIndex].value});b&&a.setAttribute("delUrl",window._ROOT_URL);a.innerHTML=this.inputs.title.value;this.ne.selectedInstance.getRng().insertNode(a)}}}});nicEditors.registerPlugin(nicPlugin,nicLinkOptions);
var nicColorOptions={buttons:{forecolor:{name:__("\u6587\u672c\u989c\u8272"),type:"nicEditorColorButton",noClose:!0},bgcolor:{name:__("\u80cc\u666f\u989c\u8272"),type:"nicEditorBgColorButton",noClose:!0}}},nicEditorColorButton=nicEditorAdvancedButton.extend({addPane:function(){var a={"0":"00",1:"33",2:"66",3:"99",4:"CC",5:"FF"},b=(new bkElement("DIV")).setStyle({width:"270px"}),c;for(c in a)for(var d in a)for(var e in a){var f="#"+a[c]+a[e]+a[d],g=(new bkElement("DIV")).setStyle({cursor:"pointer",
height:"15px","float":"left"}).appendTo(b),k=(new bkElement("DIV")).setStyle({border:"2px solid "+f}).appendTo(g),f=(new bkElement("DIV")).setStyle({backgroundColor:f,overflow:"hidden",width:"11px",height:"11px"}).addEvent("click",this.colorSelect.closure(this,f)).addEvent("mouseover",this.on.closure(this,k)).addEvent("mouseout",this.off.closure(this,k,f)).appendTo(k);if(!window.opera)g.onmousedown=f.onmousedown=bkLib.cancelEvent}this.pane.append(b.noSelect())},colorSelect:function(a){this.ne.nicCommand("foreColor",
a);this.removePane()},on:function(a){a.setStyle({border:"2px solid #000"})},off:function(a,b){a.setStyle({border:"2px solid "+b})}}),nicEditorBgColorButton=nicEditorColorButton.extend({colorSelect:function(a){bkLib.isMSIE?this.ne.nicCommand("BackColor",a):this.ne.nicCommand("hiliteColor",a);this.removePane()}});nicEditors.registerPlugin(nicPlugin,nicColorOptions);var nicImageOptions={buttons:{image:{name:"\u6dfb\u52a0\u56fe\u7247",type:"nicImageButton",tags:["IMG"]}}};
function selectFile(a,b,c){if(oFileManager.oFileManagerMainDir==".")oFileManager.oFileManagerMainDir=_ROOT_URL+oFileManagerMainDir;oFileManager(function(b){$BK(a).value=b.url},null,true,{selectExt:b?b:"",browseDir:c?c:"/."})}
var nicImageButton=nicEditorAdvancedButton.extend({width:"220px",addPane:function(){var a=(new Date).getTime();if((this.im=this.ne.selectedInstance.selElm().parentTag("IMG"))&&this.im.AnswerType)this.im=false;this.addForm({"":{type:"title",txt:"\u6dfb\u52a0\u4fee\u6539\u56fe\u7247"},src:{type:"text",txt:"\u8def\u5f84",value:"http://",style:{width:"150px"}},alt1:{type:"title",txt:'<iframe id="oEditUploadify'+a+'" frameborder="0" style="width:25px; height:19px; border:0px; float:right; margin-top:-2px;" src="'+
_ROOT_URL+oFileManagerMainDir+"/include/uploadify/iframeIndex.php\"></iframe><font style=\"font-weight:normal; font-size:12px; cursor:pointer; margin-left:5px; float:right; margin-top:-5px;*margin-top:-10px;_margin-top:-5px;\" onclick=\"selectFile('src','jpg;png;gif;bmp','"+this.ne.CustomConfig.oFileManager.browseDir.img+"');\">\u9009\u62e9\u56fe\u7247</font>",p_css:{textAlign:"right",height:"15px"}},width:{type:"text",txt:"\u5bbd",style:{width:"40px"},p_css:{clear:"none","float":"left"},s_css:{width:"60px"}},
height:{type:"text",txt:"\u9ad8",style:{width:"40px"},p_css:{clear:"none","float":"left"}},alt:{type:"text",txt:"\u63cf\u8ff0",style:{width:"100px"}},align:{type:"select",txt:"\u6837\u5f0f",options:{baseline:"\u9ed8\u8ba4",left:"\u5de6\u5bf9\u9f50",right:"\u53f3\u5bf9\u9f50"}}},this.im);if(this.im&&!this.im.getAttribute("src").indexOf(window._ROOT_URL)){$BK("src").value=this.im.getAttribute("src").substr(window._ROOT_URL.length);$BK("width").value=parseInt(this.im.style.width);$BK("height").value=
parseInt(this.im.style.height)}document.getElementById("oEditUploadify"+a).contentWindow.config={uploadifyId:"uploadify",onAllCompleteFun:function(a){document.getElementById("src").value=a},fileExt:"jpg;png;gif;bmp",swfConfig:{folder:this.ne.CustomConfig.oFileManager.quickUploadDir.img}}},submit:function(){var a=this.inputs.src.value,b={};this.inputs.width.value&&(b.width=parseInt(this.inputs.width.value)+"px");this.inputs.height.value&&(b.height=parseInt(this.inputs.height.value)+"px");if(a==""||
a=="http://"){alert("\u60a8\u5fc5\u987b\u63d2\u5165\u56fe\u7247\u8def\u5f84");return false}this.removePane();if(!this.im){this.ne.nicCommand("insertImage","javascript:nicImTemp();");this.im=this.findElm("IMG","src","javascript:nicImTemp();")}if(this.im){this.errorfn(a);this.im.setAttributes({src:/^http:/.test(this.inputs.src.value)?this.inputs.src.value:window._ROOT_URL+this.inputs.src.value,alt:this.inputs.alt.value,align:this.inputs.align.value}).setStyle(b)}},errorfn:function(a){this.im.setAttribute("onerror",
'if(this.defaultSrc==null){this.defaultSrc="'+a+'"}else{this.defaultSrc="http:"+this.defaultSrc}if(!window._ROOT_URL){window._ROOT_URL=""}if(!/^http:/.test(this.defaultSrc)){this.onload=function(){this.removeAttribute("defaultSrc")};this.src=window._ROOT_URL+this.defaultSrc}else{if(this.src.indexOf(window._ROOT_URL+"'+oFileManagerMainDir+'/include/oEditor/resources/onerror.gif")<0){this.src=window._ROOT_URL+"'+oFileManagerMainDir+'/include/oEditor/resources/onerror.gif"}else{this.removeAttribute("defaultSrc")}}');
if(bkLib.isMSIE){this.im.errorfn=function(){this.defaultSrc=this.defaultSrc==null?a:"http:"+this.defaultSrc;if(!window._ROOT_URL)window._ROOT_URL="";if(/^http:/.test(this.defaultSrc))this.src.indexOf(window._ROOT_URL+oFileManagerMainDir+"/include/oEditor/resources/onerror.gif")<0?this.src=window._ROOT_URL+oFileManagerMainDir+"/include/oEditor/resources/onerror.gif":this.removeAttribute("defaultSrc");else{this.onload=function(){this.removeAttribute("defaultSrc")};this.src=window._ROOT_URL+this.defaultSrc}};
this.im.addEvent("error",this.im.errorfn.closure(this.im))}}});nicEditors.registerPlugin(nicPlugin,nicImageOptions);var nicSaveOptions={buttons:{save:{name:__("Save this content"),type:"nicEditorSaveButton"}}},nicEditorSaveButton=nicEditorButton.extend({init:function(){this.ne.options.onSave||this.margin.setStyle({display:"none"})},mouseClick:function(){var a=this.ne.options.onSave,b=this.ne.selectedInstance;a(b.getContent(),b.elm.id,b)}});nicEditors.registerPlugin(nicPlugin,nicSaveOptions);
var nicXHTML=bkClass.extend({stripAttributes:["_moz_dirty","_moz_resizing","_extended"],noShort:["style","title","script","textarea","a"],cssReplace:{"font-weight:bold;":"strong","font-style:italic;":"em"},sizes:{1:"xx-small",2:"x-small",3:"small",4:"medium",5:"large",6:"x-large"},construct:function(a){this.ne=a;this.ne.options.xhtml&&a.addEvent("get",this.cleanup.closure(this))},cleanup:function(a){var b=this.toXHTML(a.getElm());a.content=b},toXHTML:function(a,b){var c="",d="",e="",f=a.nodeType,
g=a.nodeName.toLowerCase(),k=a.hasChildNodes&&a.hasChildNodes(),m=[];switch(f){case 1:var l=a.attributes;switch(g){case "b":g="strong";break;case "i":g="em";break;case "font":g="span"}if(b){for(f=0;f<l.length;f++){var h=l[f],n=h.nodeName.toLowerCase(),j=h.nodeValue;if(h.specified&&j&&!(bkLib.inArray(this.stripAttributes,n)||typeof j=="function")){switch(n){case "style":h=j.replace(/ /g,"");for(itm in this.cssReplace)if(h.indexOf(itm)!=-1){m.push(this.cssReplace[itm]);h=h.replace(itm,"")}e=e+h;j="";
break;case "class":j=j.replace("Apple-style-span","");break;case "size":e=e+("font-size:"+this.sizes[j]+";");j=""}j&&(d=d+(" "+n+'="'+j+'"'))}}e&&(d=d+(' style="'+e+'"'));for(f=0;f<m.length;f++)c=c+("<"+m[f]+">");d==""&&g=="span"&&(b=false);if(b){c=c+("<"+g);g!="br"&&(c=c+d)}}if(!k&&!bkLib.inArray(this.noShort,n))b&&(c=c+" />");else{b&&(c=c+">");for(f=0;f<a.childNodes.length;f++)(d=this.toXHTML(a.childNodes[f],true,true))&&(c=c+d)}b&&k&&(c=c+("</"+g+">"));for(f=0;f<m.length;f++)c=c+("</"+m[f]+">");
break;case 3:c=c+a.nodeValue}return c}});nicEditors.registerPlugin(nicXHTML);
var nicBBCode=bkClass.extend({construct:function(a){this.ne=a;if(this.ne.options.bbCode){a.addEvent("get",this.bbGet.closure(this));a.addEvent("set",this.bbSet.closure(this));a=this.ne.loadedPlugins;for(itm in a)if(a[itm].toXHTML)this.xhtml=a[itm]}},bbGet:function(a){var b=this.xhtml.toXHTML(a.getElm());a.content=this.toBBCode(b)},bbSet:function(a){a.content=this.fromBBCode(a.content)},toBBCode:function(a){function b(b,d){a=a.replace(b,d)}b(/\n/gi,"");b(/<strong>(.*?)<\/strong>/gi,"[b]$1[/b]");b(/<em>(.*?)<\/em>/gi,
"[i]$1[/i]");b(/<span.*?style="text-decoration:underline;">(.*?)<\/span>/gi,"[u]$1[/u]");b(/<ul>(.*?)<\/ul>/gi,"[list]$1[/list]");b(/<li>(.*?)<\/li>/gi,"[*]$1[/*]");b(/<ol>(.*?)<\/ol>/gi,"[list=1]$1[/list]");b(/<img.*?src="(.*?)".*?>/gi,"[img]$1[/img]");b(/<a.*?href="(.*?)".*?>(.*?)<\/a>/gi,"[url=$1]$2[/url]");b(/<br.*?>/gi,"\n");b(/<.*?>.*?<\/.*?>/gi,"");return a},fromBBCode:function(a){function b(b,d){a=a.replace(b,d)}b(/\[b\](.*?)\[\/b\]/gi,"<strong>$1</strong>");b(/\[i\](.*?)\[\/i\]/gi,"<em>$1</em>");
b(/\[u\](.*?)\[\/u\]/gi,'<span style="text-decoration:underline;">$1</span>');b(/\[list\](.*?)\[\/list\]/gi,"<ul>$1</ul>");b(/\[list=1\](.*?)\[\/list\]/gi,"<ol>$1</ol>");b(/\[\*\](.*?)\[\/\*\]/gi,"<li>$1</li>");b(/\[img\](.*?)\[\/img\]/gi,'<img src="$1" />');b(/\[url=(.*?)\](.*?)\[\/url\]/gi,'<a href="$1">$2</a>');b(/\n/gi,"<br />");return a}});nicEditors.registerPlugin(nicBBCode);
oEditor=nicEditor=nicEditor.extend({floatingPanel:function(){this.floating=(new bkElement("DIV")).setStyle({position:"absolute",top:"-1000px"}).appendTo(document.body);this.addEvent("focus",this.reposition.closure(this)).addEvent("blur",this.hide.closure(this));this.setPanel(this.floating)},reposition:function(){var a=this.selectedInstance.e;this.floating.setStyle({width:(parseInt(a.getStyle("width"))||a.clientWidth)+"px"});var b=a.offsetTop-this.floating.offsetHeight;b<0&&(b=a.offsetTop+a.offsetHeight);
this.floating.setStyle({top:b+"px",left:a.offsetLeft+"px",display:"block"})},hide:function(){this.floating.setStyle({top:"-1000px"})}});
var nicCodeOptions={buttons:{xhtml:{name:"\u7f16\u8f91\u6e90\u7801",type:"nicCodeButton"}}},nicCodeButton=nicEditorAdvancedButton.extend({width:"350px",addPane:function(){this.addForm({"":{type:"title",txt:"\u7f16\u8f91\u6e90\u7801"},code:{type:"content",value:this.ne.selectedInstance.cleanWord(this.ne.selectedInstance.getContent()),style:{width:"340px",height:"200px"}}})},submit:function(){this.ne.selectedInstance.setContent(this.inputs.code.value);this.removePane()}});
nicEditors.registerPlugin(nicPlugin,nicCodeOptions);
var tableOptions={buttons:{table:{name:"\u6dfb\u52a0\u8868\u683c",type:"nicEditorTableButton",tags:["TABLE"]}}},nicEditorTableButton=nicEditorAdvancedButton.extend({width:"220px",addPane:function(){this.ln=this.ne.selectedInstance.selElm().parentTag("TABLE");this.addForm({"":{type:"title",txt:"\u6dfb\u52a0\u8868\u683c"},rowsLength:{type:"text",txt:"\u884c",value:"1",style:{width:"30px"},p_css:{display:"inline",clear:"none"}},colsLength:{type:"text",txt:"\u5217",value:"1",style:{width:"30px"},p_css:{display:"inline",
clear:"none"}},border:{type:"text",txt:"\u8fb9\u6846",value:"1",style:{width:"30px"},p_css:{display:"inline",clear:"none"}},cellpadding:{type:"text",txt:"\u586b\u5145",value:"1",style:{width:"30px"},p_css:{display:"inline",clear:"none"}},cellspacing:{type:"text",txt:"\u95f4\u8ddd",value:"1",style:{width:"30px"},p_css:{display:"inline",clear:"none"}}},this.ln)},submit:function(){var a=this.inputs.rowsLength.value,b=this.inputs.colsLength.value,c=this.inputs.border.value,d=this.inputs.cellpadding.value,
e=this.inputs.cellspacing.value;this.removePane();c="<table border="+c+" cellpadding="+d+" cellspacing="+e+" >";for(d=0;d<a;d++){c=c+"<tr>";for(e=0;e<b;e++)c=c+"<td>&nbsp;</td>";c=c+"</tr>"}c=c+"</table>";if(bkLib.isMSIE&&bkLib.version<9)this.ne.selectedInstance.getRng().pasteHTML(c);else{a=new bkElement("div");a.innerHTML=c;c=a.getElementsByTagName("table")[0];this.ne.selectedInstance.getRng().insertNode(c)}}});nicEditors.registerPlugin(nicPlugin,tableOptions);
var AnswerOptions={buttons:{AnswerSelect:{name:"\u63d2\u5165\u7b54\u6848\u6846",type:"nicEditorAnswerButton",tags:["IMG"],AnswerType:"select"}},CustomConfig:{AnswerSelect:{AnswerType:"select",ExtensionFun:null,AnswerNum:"0"}}},nicEditorAnswerButton=nicEditorAdvancedButton.extend({width:"220px",addPane:function(){if(bkLib.isMSIE&&bkLib.version<9){var a="<img AnswerType="+this.ne.CustomConfig.AnswerSelect.AnswerType+' alt="\u7b54\u6848'+ ++this.ne.CustomConfig.AnswerSelect.AnswerNum+'" Num="'+this.ne.CustomConfig.AnswerSelect.AnswerNum+
'" style="width:80px; height: 25px; border:0px; background-color:#FFFFCC; color:#FF0000;" />';try{var b=this.ne.selectedInstance.getRng();b.pasteHTML(a)}catch(c){}}else{a=new bkElement("img");a.style.cssText="width:80px; height: 25px; border:0px; background-color:#FFFFCC; color:#FF0000;";a.setAttribute("AnswerType",this.ne.CustomConfig.AnswerSelect.AnswerType);a.src="http://";a.alt="\u7b54\u6848"+ ++this.ne.CustomConfig.AnswerSelect.AnswerNum;a.setAttribute("Num",this.ne.CustomConfig.AnswerSelect.AnswerNum);
this.ne.selectedInstance.getRng().insertNode(a)}this.removePane();try{for(var d in this.ne.CustomConfig.AnswerSelect.ExtensionFun)eval(this.ne.CustomConfig.AnswerSelect.ExtensionFun[d]+"(this);");b.moveStart("character",0);b.select()}catch(e){}}});nicEditors.registerPlugin(nicPlugin,AnswerOptions);
var nicImageOptions={buttons:{ImageArea:{name:"\u63d2\u5165\u56fe\u7247\u57df",type:"nicImageAreaButton",tags:["DIV"],AnswerType:"ImageArea"}},CustomConfig:{ImageArea:{mousedownObj:null}}},nicImageAreaButton=nicEditorAdvancedButton.extend({width:"220px",addPane:function(){var a=(new Date).getTime();this.addForm({"":{type:"title",txt:"\u63d2\u5165\u56fe\u7247\u57df"},src:{type:"text",txt:"\u8def\u5f84",value:"http://",style:{width:"150px"}},alt1:{type:"title",txt:'<iframe id="oEditUploadify'+a+'" frameborder="0" style="width:25px; height:19px; border:0px; float:right; margin-top:-2px;" src="'+
_ROOT_URL+oFileManagerMainDir+"/include/uploadify/iframeIndex.php\"></iframe><font style=\"font-weight:normal; font-size:12px; cursor:pointer; margin-left:5px; float:right;\" onclick=\"selectFile('src','jpg;png;gif;bmp','"+this.ne.CustomConfig.oFileManager.browseDir.img+"');\" >\u9009\u62e9\u56fe\u7247</font>",p_css:{textAlign:"right",height:"15px"}},width:{type:"text",txt:"\u5bbd",style:{width:"40px"},p_css:{clear:"none","float":"left"},s_css:{width:"60px"}},height:{type:"text",txt:"\u9ad8",style:{width:"40px"},
p_css:{clear:"none","float":"left"}},alt:{type:"text",txt:"\u63cf\u8ff0",style:{width:"100px"}},Description:{type:"content",txt:"\u6ce8\u660e",value:"",style:{width:"150px"}}});document.getElementById("oEditUploadify"+a).contentWindow.config={uploadifyId:"uploadify",onAllCompleteFun:function(a){document.getElementById("src").value=a},fileExt:"jpg;png;gif;bmp",swfConfig:{folder:this.ne.CustomConfig.oFileManager.quickUploadDir.img}}},submit:function(){var a=this.inputs.src.value,b=this.inputs.alt.value,
c=this.inputs.width.value,d=this.inputs.height.value,e=this.ne.Text_HTML(this.inputs.Description.value);if(e==""||a==""||a=="http://"){alert("\u56fe\u7247\u5730\u5740\u548c\u6ce8\u660e\u5fc5\u987b\u586b");return false}/^\d+(?:px|%)$/i.test(c)||(c=/^\d+$/i.test(c)?c+"px":"100px");/^\d+(?:px|%)$/i.test(d)||(d=/^\d+$/i.test(d)?d+"px":"100px");this.removePane();a='<div style=" position:absolute; z-index:-100; width:'+c+"; height:"+d+';">                    <img src="'+a+'" alt="'+b+'" style="height:80%; width:100%;" onerror=\'if(this.defaultSrc==null){this.defaultSrc="'+
a+'"}else{this.defaultSrc="http:"+this.defaultSrc}if(!window._ROOT_URL){window._ROOT_URL=""}if(!/^http:/.test(this.defaultSrc)){this.onload=function(){this.removeAttribute("defaultSrc")};this.src=window._ROOT_URL+this.defaultSrc}else{if(this.src.indexOf(window._ROOT_URL+"'+oFileManagerMainDir+'/include/oEditor/resources/onerror.gif")<0){this.src=window._ROOT_URL+"'+oFileManagerMainDir+'/include/oEditor/resources/onerror.gif"}else{this.removeAttribute("defaultSrc")}}\' />                    <div style="overflow:auto; height:20%; width:100%;">'+
e+"</div>                </div>";if(bkLib.isMSIE&&bkLib.version<9)try{this.ne.selectedInstance.getRng().pasteHTML('<div AnswerType="ImageArea" eval="this.getElementsByTagName(\'div\')[0].style.zIndex=0;" style=" float:left;width:'+c+"; height:"+d+";\" onmousedown=\"window.CustomConfig['ImageArea']['mousedownObj']=this;\">"+a+"</div>")}catch(f){alert("\u6587\u672c\u57df\u4e0d\u53ef\u4ee5\u8986\u76d6")}else{c=(new bkElement("div")).setContent(a);c.style.cssText="float:left; width:100px; height:100px;";
c.setAttribute("AnswerType","ImageArea");c.setAttribute("eval","this.getElementsByTagName('div')[0].style.zIndex=0;");c.setAttribute("onmousedown","window.CustomConfig['ImageArea']['mousedownObj']=this;");c.onmousedown=function(){window.CustomConfig.ImageArea.mousedownObj=this};this.ne.selectedInstance.getRng().insertNode(c)}}});nicEditors.registerPlugin(nicPlugin,nicImageOptions);
var nicMediaButton={buttons:{media:{name:"\u63d2\u5165\u5a92\u4f53",type:"nicEditorMediaButton",tags:["OBJECT","EMBED"]}}},nicEditorMediaButton=nicEditorAdvancedButton.extend({width:"240px",addPane:function(){var a=(new Date).getTime(),b={src:"http://",AutoPlay:false,Ctn:false,ProgressBar:false,PlayCount:"0",width:250,height:250},c=this.ne.selectedInstance.selElm();if(this.ln=this.ne.selectedInstance.selElm().parentTag("OBJECT")){var c=this.ln.getElementsByTagName("param"),d;for(d in c)if(c[d].name==
"flashvars"){d=c[d].value.split("&");for(c=0;c<d.length;c++){var e=d[c].split("=");switch(e[0]){case "file":b.src=e[1].substr(0,7)==="http://"?e[1]:e[1].substr((window._ROOT_URL||"").length);break;case "AutoPlay":b.AutoPlay=eval(e[1]);break;case "Ctn":b.Ctn=eval(e[1])}}break}b.ProgressBar=eval(this.ln.getAttribute("ProgressBar"));b.PlayCount=this.ln.getAttribute("playcount")==null?"0":this.ln.getAttribute("playcount");b.width=this.ln.width;b.height=this.ln.height}else if(c.nodeName=="EMBED"){this.ln=
c;b.src=this.ln.src;b.AutoPlay=eval(this.ln.getAttribute("autostart"));b.Ctn=eval(this.ln.getAttribute("loop"));b.width=this.ln.width;b.height=this.ln.height}this.addForm({"":{type:"title",txt:"\u63d2\u5165\u5a92\u4f53"},src:{type:"text",txt:"\u8def\u5f84",value:b.src,style:{width:"150px"}},alt1:{type:"title",txt:'<iframe id="oEditUploadify'+a+'" frameborder="0" style="width:25px; height:19px; border:0px; float:right; margin-top:-2px;" src="'+_ROOT_URL+oFileManagerMainDir+"/include/uploadify/iframeIndex.php\"></iframe><font style=\"font-weight:normal; font-size:12px; cursor:pointer; margin-left:5px; float:right;margin-top:-5px;\" onclick=\"selectFile('src','swf;flv;mp3;wmv','"+
this.ne.CustomConfig.oFileManager.browseDir.media+"');\">\u9009\u62e9\u5a92\u4f53</font>",p_css:{textAlign:"right",height:"15px"}},AutoPlay:{type:"checkbox",txt:"\u81ea\u52a8\u64ad\u653e",checked:b.AutoPlay,s_css:{width:"60px"},p_css:{"float":"left",width:"95px",display:"inline"}},Ctn:{type:"checkbox",txt:"\u5faa\u73af\u64ad\u653e",checked:b.Ctn,s_css:{width:"60px"},p_css:{clear:"none","float":"left"}},ProgressBar:{type:"checkbox",txt:"\u7981\u7528\u8fdb\u5ea6",checked:b.ProgressBar,s_css:{width:"60px"},
p_css:{"float":"left",width:"95px"}},PlayCount:{type:"text",txt:"\u64ad\u653e\u6b21\u6570",value:b.PlayCount,style:{width:"30px",height:"18px",lineHeight:"18px"},s_css:{width:"60px"},p_css:{clear:"none",width:"110px","float":"left"}},width:{type:"text",txt:"\u97f3/\u89c6\u9891\u5bbd",value:b.width,style:{width:"30px"},p_css:{width:"110px","float":"left"},s_css:{width:"60px"}},height:{type:"text",txt:"\u97f3/\u89c6\u9891\u9ad8",value:b.height,style:{width:"30px"},p_css:{clear:"none",width:"110px",
"float":"left"}},palySwf:{type:"checkbox",txt:"SWF\u5355\u72ec\u64ad\u653e",checked:true,s_css:{width:"90px"}}});document.getElementById("oEditUploadify"+a).contentWindow.config={uploadifyId:"uploadify",onAllCompleteFun:function(a){document.getElementById("src").value=a},fileExt:"wmv;mp3;flv;swf",swfConfig:{folder:this.ne.CustomConfig.oFileManager.quickUploadDir.media}}},submit:function(){var a=this.inputs.src.value,b=this.inputs.AutoPlay.checked?"true":"false",c=this.inputs.Ctn.checked?"true":"false",
d=this.inputs.ProgressBar.checked?"true":"false",e=this.inputs.PlayCount.value.replace(/(^\s*)|(\s*$)/g,"").match(/^\d+/),f=this.inputs.palySwf.checked?true:false,g="",k=parseInt(this.inputs.width.value)>250?parseInt(this.inputs.width.value):250,m=27,l="skin/Audio.zip",h=true,n=a.substr(a.lastIndexOf(".")+1);if(a.lastIndexOf(".")==-1){alert("\u975e\u6cd5\u5a92\u4f53\u8def\u5f84");return false}if(n.toUpperCase()=="FLV"||n.toUpperCase()=="SWF"||n.toUpperCase()=="WMV"){l=n.toUpperCase()=="SWF"?"skin/defaultSWF.zip":
"skin/defaultSE.zip";m=parseInt(this.inputs.height.value)>220?parseInt(this.inputs.height.value):220}else if(n.toUpperCase()!="MP3"){alert("\u6682\u53ea\u652f\u6301MP3,FLV,SWF,WMV");return false}/^http:\/\//i.test(a)&&(h=false);this.removePane();if(!bkLib.isChrome&&this.ln)this.ln.outerHTML="";var j="player_id"+(new Date).getTime();d=="true"&&(g='document.getElementById("'+j+'").ProgressBarInterval=setInterval(function(){try {if(document.getElementById("'+j+'").getAttribute("JSenable")!="false"){JS_OFplayer("'+
j+'", "adjust", "progress","prop","");}clearInterval(document.getElementById("'+j+'").ProgressBarInterval);} catch(e) {}},500);');l="JSenable=true&Ctn="+c+"&AutoPlay="+b+"&SkinURL="+l+"&file=";g='<script language=javascript >var object_ofplayer_temp=document.getElementById("'+j+'");if(object_ofplayer_temp!=null){try{if(object_ofplayer_temp.movie!=window._ROOT_URL+"'+oFileManagerMainDir+"/include/player/ofplayer.swf?"+l+(h?'"+window._ROOT_URL+"':"")+a+'"){object_ofplayer_temp.flashvars="'+l+(h?'"+window._ROOT_URL+"':
"")+a+'";object_ofplayer_temp.movie=window._ROOT_URL+"'+oFileManagerMainDir+"/include/player/ofplayer.swf?"+l+(h?'"+window._ROOT_URL+"':"")+a+'";}if(object_ofplayer_temp.getElementsByTagName("embed")[0].src!=window._ROOT_URL+"'+oFileManagerMainDir+'/include/player/ofplayer.swf"){object_ofplayer_temp.getElementsByTagName("embed")[0].setAttribute("flashvars","'+l+(h?'"+window._ROOT_URL+"':"")+a+'");object_ofplayer_temp.getElementsByTagName("embed")[0].src=window._ROOT_URL+"'+oFileManagerMainDir+'/include/player/ofplayer.swf";}}catch(e){}'+
g+"}<\/script>";d="<object id="+j+' classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" '+(""+e=="0"||e==""?"":'PlayCount="'+e+'"')+' ProgressBar="'+(d=="true"?"true":"false")+'" width="'+k+'" height="'+m+'" AnswerType="media" eval="this.outerHTML+=unescape(\''+escape(g)+'\');" >                            <param name="movie" value="'+window._ROOT_URL+oFileManagerMainDir+"/include/player/ofplayer.swf?"+l+(h?window._ROOT_URL:"")+a+'" />                            <param name="allowFullScreen" value="true" />                            <param name="allowScriptAccess" value="always" />                            <param name="quality" value="high" />                            <param name="wmode" value="opaque" />                            <param name="flashvars" value="'+
l+(h?window._ROOT_URL:"")+a+'" />                            <embed name="'+j+'" type="application/x-shockwave-flash" '+(""+e=="0"||e==""?"":'PlayCount="'+e+'"')+' ProgressBar="'+(d=="true"?"true":"false")+'" width="'+k+'" height="'+m+'" src="'+window._ROOT_URL+oFileManagerMainDir+'/include/player/ofplayer.swf" allowfullscreen="true" allowscriptaccess="always" quality="high" wmode="opaque" flashvars="'+l+(h?window._ROOT_URL:"")+a+'"></embed>                    </object>';if(n.toUpperCase()=="WMV"){g=
'<script language=javascript >var embedObj=document.getElementById("'+j+'");if(embedObj!=null&&embedObj.src!="'+(h?'"+window._ROOT_URL+"':"")+encodeURI(a)+'"){var newEmbedObj=document.createElement("EMBED");newEmbedObj.setAttribute("autostart",'+b+');newEmbedObj.setAttribute("loop",'+c+');newEmbedObj.setAttribute("width",'+(k>290?k:290)+');newEmbedObj.setAttribute("height",'+m+');newEmbedObj.setAttribute("src","'+(h?'"+window._ROOT_URL+"':"")+encodeURI(a)+'");newEmbedObj.setAttribute("flename","mp");newEmbedObj.setAttribute("type","application/x-oleobject");newEmbedObj.setAttribute("codeBase","http://activex.microsoft.com/activex/controls/mplayer/en/nsmp2inf.cab#version=10,0,0,0");embedObj.parentNode.insertBefore(newEmbedObj,embedObj.nextSibling);embedObj.parentNode.removeChild(embedObj);}<\/script>';
d="<embed id="+j+' width="'+(k>290?k:290)+'" height="'+m+'" src="'+(h?window._ROOT_URL:"")+a+'" autostart="'+b+'" loop="'+c+'" AnswerType="media" type=audio/mpeg controls="smallconsole" eval="this.outerHTML+=unescape(\''+escape(g)+"');\" ></embed>"}else n.toUpperCase()=="SWF"&&f&&(d="<object id="+j+' height="'+m+'" width="'+k+'" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" >                    <param value="'+(h?window._ROOT_URL:"")+a+'" name="movie">                    <param value="true" name="allowFullScreen">                    <param value="always" name="allowScriptAccess">                    <param value="high" name="quality">                    <param value="opaque" name="wmode">                    <param value="undefined" name="flashvars">                    <embed name="'+
j+'" height="'+m+'" width="'+k+'" flashvars="undefined" wmode="opaque" quality="high" allowscriptaccess="always" allowfullscreen="true" src="'+(h?window._ROOT_URL:"")+a+'" type="application/x-shockwave-flash">                </object>');if(bkLib.isMSIE&&bkLib.version<9)this.ne.selectedInstance.getRng().pasteHTML(d);else{a=new bkElement("div");a.innerHTML=d;this.ne.selectedInstance.getRng().insertNode(a.firstChild)}if(bkLib.isChrome&&this.ln){this.ln.parentNode.insertBefore($BK(j),this.ln.nextSibling);
this.ln.outerHTML=""}}});nicEditors.registerPlugin(nicPlugin,nicMediaButton);
